// i18n - English UI strings
export const en = {
  nav: {
    search: 'Search...',
    darkMode: 'Dark mode',
    lightMode: 'Light mode',
    language: 'Language',
    home: 'Home',
    back: 'Back',
    tableOfContents: 'On this page',
    related: 'Related articles',
    tags: 'Tags',
    allTopics: 'All topics',
    readingTime: 'min read',
    copyLink: 'Copy link',
    copied: 'Copied!',
    copyDefinition: 'Copy definition',
    expandAll: 'Expand all',
    collapseAll: 'Collapse all',
  },
  sections: {
    introduction: 'Introduction',
    glossary: 'Glossary',
    'internet-generations': 'Internet Generations',
    blockchain: 'Blockchain Technology',
    security: 'Security',
    nfts: 'NFTs',
    communities: 'NFT Communities',
    platforms: 'Platforms',
    communication: 'Communication',
    marketing: 'Marketing',
    references: 'References',
  },
  home: {
    eyebrow: 'Educational wiki',
    title: 'Computers\nMake Art',
    subtitle: 'A knowledge space about Blockchain, Web3, NFTs, and digital art communities.',
    explore: 'Explore the wiki',
    by: 'by',
    topics: 'topics',
    terms: 'glossary terms',
    free: 'free and open',
  },
  callout: {
    info: 'Info',
    concept: 'Concept',
    warning: 'Note',
  }
}
