// Wiki content in English

const intro = [
  "To start talking about NFTs, we first need to think about some key terms that are part of this universe. This curriculum covers the techniques and practices for creating artworks in the NFT market.",
  "",
  "This project's main goal is to encourage more people to learn how to use Blockchain technology — and to foster a serious conversation about how virtual communities should be more conscious and thereby contribute socially to physical space.",
  "",
  "---",
  "",
  "We'll talk about **Blockchain**, **crypto**, **digital communities**, and other basic concepts so you have the autonomy and initial encouragement to create your own NFT works and projects.",
  "",
  "> Computers advance / Artists hitch a ride / Scientists create the new / Artists take the fame — Fred Zero Quatro",
  "",
  "## Why this matters",
  "",
  "This is not just a technical manual. It's an invitation to think critically about technology, art, and community. The NFT space is still fertile ground — largely unexplored. It's up to us to navigate it consciously: planting good ideas, without clearing the forest.",
  "",
  "## Who made this?",
  "",
  "This educational material was developed by **Numa** as an integral part of master's research in Digital Artifact Design at the Federal University of Pernambuco (UFPE), funded by CNPq's MAI/DAI program.",
  "",
  "The content is available for **free distribution**.",
].join("\n");

const internetGen = [
  "First of all, it's important to learn about the three existing generations of the internet. We live in a moment where Web 2 and Web3 exist simultaneously — each generation is not a separate thing, but just a continuation of the web we already know. You may find content referring to these as 'eras' in a more temporal sense, but it's more useful to think in terms of modes of interaction.",
  "",
  "<div style=\"overflow-x:auto;margin:2rem 0\"><table style=\"width:100%;border-collapse:collapse;text-align:center\">",
  "  <tr style=\"background:var(--white)\">",
  "    <td style=\"padding:0.5rem;border:none;width:33%\"><img src=\"/wiki/images/web1.svg\" alt=\"\" style=\"width:100%;height:auto;display:block\" /></td>",
  "    <td style=\"padding:0.5rem;border:none;width:33%\"><img src=\"/wiki/images/web2.svg\" alt=\"\" style=\"width:100%;height:auto;display:block\" /></td>",
  "    <td style=\"padding:0.5rem;border:none;width:33%\"><img src=\"/wiki/images/web3.svg\" alt=\"\" style=\"width:100%;height:auto;display:block\" /></td>",
  "  </tr>",
  "  <tr style=\"background:#0a0a0a;pointer-events:none\">",
  "    <td style=\"padding:0.6rem 1rem;font-family:'Instrument Sans',sans-serif;font-weight:700;font-size:1.1rem;letter-spacing:-0.02em;color:#fafaf8;border:none\">Web1</td>",
  "    <td style=\"padding:0.6rem 1rem;font-family:'Instrument Sans',sans-serif;font-weight:700;font-size:1.1rem;letter-spacing:-0.02em;color:#fafaf8;border:none\">Web2</td>",
  "    <td style=\"padding:0.6rem 1rem;font-family:'Instrument Sans',sans-serif;font-weight:700;font-size:1.1rem;letter-spacing:-0.02em;color:#fafaf8;border:none\">Web3</td>",
  "  </tr>",
  "  <tr style=\"background:var(--white)\">",
  "    <td style=\"padding:0.4rem 1rem;font-style:italic;font-size:0.85rem;color:var(--gray-500);border:none\">read-only</td>",
  "    <td style=\"padding:0.4rem 1rem;font-style:italic;font-size:0.85rem;color:var(--gray-500);border:none\">read-write</td>",
  "    <td style=\"padding:0.4rem 1rem;font-style:italic;font-size:0.85rem;color:var(--gray-500);border:none\">read-write-own</td>",
  "  </tr>",
  "  <tr style=\"background:var(--white)\">",
  "    <td style=\"padding:0.4rem 1rem 0.8rem;font-size:0.9rem;color:var(--gray-700);border:none\">Simple Internet</td>",
  "    <td style=\"padding:0.4rem 1rem 0.8rem;font-size:0.9rem;color:var(--gray-700);border:none\">Social Internet</td>",
  "    <td style=\"padding:0.4rem 1rem 0.8rem;font-size:0.9rem;color:var(--gray-700);border:none\">Semantic Internet</td>",
  "  </tr>",
  "</table></div>",
  "",
  "## Web 1.0 — The Simple Internet",
  "",
  "![Yahoo's old website](/wiki/images/web1.jpg)",
  "",
  "The first phase of the Internet emerged in the **1990s** and consisted of pages with hyperlinks. Sites were primarily informational with very basic layouts, very few multimedia resources, and most content text-based. Users could only access, read, and navigate between pages, with little or no interaction or feedback tools.",
  "",
  "<div class=\"callout callout-concept\"><span class=\"callout-icon\">📡</span><div><p class=\"callout-title\">Web 1.0 Characteristics</p><ul style=\"margin:0.5rem 0 0;padding-left:1.25rem\"><li>Limited bandwidth</li><li>Limited devices (desktop only)</li><li>No real interaction, read-only</li></ul></div></div>",
  "",
  "> **Bandwidth:** the concept that determines the measure of transmission capacity, especially of a connection or network.",
  "",
  "## Web 2.0 — The Social Internet",
  "",
  "![YouTube's old layout featuring the viral video Charlie Bit My Finger](/wiki/images/web2.jpg)",
  "",
  "Emerged around **2004** — a phase that brought more user-generated content and visual features (*front-end*). Users could share more information with each other and connect more easily. They could also access information and return it to the server for more personalized content.",
  "",
  "In summary, Web 2.0 is marked by greater interactivity and collaboration between users, as well as a richer user experience. This phase saw the growth of social media platforms, blogs, and other tools that allow users to create and share their own content. Large platforms — like Google, Facebook, and Instagram — centralized control over user data.",
  "",
  "<div class=\"callout callout-concept\"><span class=\"callout-icon\">📱</span><div><p class=\"callout-title\">Web 2.0 Characteristics</p><ul style=\"margin:0.5rem 0 0;padding-left:1.25rem\"><li>Visual features (<em>front-end</em>)</li><li>User-generated content</li><li>Rise of social networks</li><li>Mobile devices</li></ul></div></div>",
  "",
  "<div style=\"display:grid;grid-template-columns:1fr 1fr;gap:1rem;margin:1.5rem 0\">",
  "  <div class=\"callout callout-info\"><span class=\"callout-icon\">🖥️</span><div><p class=\"callout-title\">Front-end</p>The part users interact with directly: the visible interface — layout, design, animations. Uses HTML, CSS and JavaScript.</div></div>",
  "  <div class=\"callout callout-info\"><span class=\"callout-icon\">⚙️</span><div><p class=\"callout-title\">Back-end</p>The invisible logic layer: data processing, storage and authentication. Uses Python, Ruby, Java, Rust.</div></div>",
  "</div>",
  "",
  "> You can find job openings for front-end, back-end, and **full-stack** developers — a professional capable of working in both areas.",
  "",
  "## Web3 — The Semantic Internet",
  "",
  "<div style=\"overflow:hidden\"><img src=\"/wiki/images/web3.jpg\" alt=\"Solflare wallet and Solscan blockchain explorer\" style=\"float:left;width:140px;height:auto;margin:0 1.25rem 0.75rem 0;border-radius:8px\" /><p>Starting from <strong>2008</strong>, when Blockchain technology came into play through Bitcoin. The principles of Web3 intend to allow users to own their own data, instead of companies — facilitating digital transactions of information and value in a secure, decentralized way.</p><p>Also known as the <strong>Semantic Web</strong>, as it aims to make information 'understandable' to computers through <em>machine learning</em>.</p><blockquote><strong>Semantics</strong> is the branch of linguistics that studies what words really mean.</blockquote><p>In the crypto world, it's common to refer to it simply as <strong>'web3'</strong> — without the '.0' — especially when talking about decentralized projects, NFTs, and DeFi.</p><p><strong>Beyond blockchain</strong>, Web3 encompasses other technologies: IPFS (decentralized storage), smart contracts, DAOs (decentralized autonomous organizations), sovereign digital identity, and distributed computing networks like Filecoin and Render.</p><p>The concept of <strong>trustless</strong> in Blockchains means that instead of trusting people or institutions, you trust the technology entirely — which is seen as impartial and capable of promoting greater freedom.</p></div>",
  "",
  "<div class=\"callout callout-concept\"><span class=\"callout-icon\">🌐</span><div><p class=\"callout-title\">Web3 Characteristics</p><ul style=\"margin:0.5rem 0 0;padding-left:1.25rem\"><li>Data decentralization</li><li>Machine learning and automation</li><li>Smart data</li></ul></div></div>",
  "",
  "## Decades of Web Development",
  "",
  "<div style=\"display:grid;grid-template-columns:1fr 1fr;gap:1.5rem;align-items:center;margin:2rem 0\">",
  "  <figure style=\"margin:0\"><img src=\"/wiki/images/web-evolution-en.svg\" alt=\"Internet evolution chart\" style=\"width:100%\" /><p style=\"font-family:'Space Mono',monospace;font-size:0.6rem;text-transform:uppercase;letter-spacing:0.08em;color:var(--gray-400);margin-top:0.5rem;text-align:center\">Reinterpretation from <a href=\"https://www.mdpi.com/1999-5903/4/3/852\" target=\"_blank\">'When the Social meets the Semantic'</a> — Fernandez-Llatas & Traver.</p></figure>",
  "  <div style=\"display:flex;flex-direction:column;gap:0.75rem\">",
  "    <div style=\"border-left:3px solid var(--orange);padding:0.75rem 1rem;background:var(--gray-50);border-radius:0 8px 8px 0\">",
  "      <p style=\"font-family:'Space Mono',monospace;font-size:0.7rem;text-transform:uppercase;letter-spacing:0.08em;color:var(--orange);margin:0 0 0.25rem\">1980 – 1990</p>",
  "      <p style=\"font-family:'Instrument Sans',sans-serif;font-weight:600;font-size:0.95rem;color:var(--gray-900);margin:0\">Web Technology</p>",
  "    </div>",
  "    <div style=\"border-left:3px solid var(--orange);padding:0.75rem 1rem;background:var(--gray-50);border-radius:0 8px 8px 0\">",
  "      <p style=\"font-family:'Space Mono',monospace;font-size:0.7rem;text-transform:uppercase;letter-spacing:0.08em;color:var(--orange);margin:0 0 0.25rem\">1990 – 2000</p>",
  "      <p style=\"font-family:'Instrument Sans',sans-serif;font-weight:600;font-size:0.95rem;color:var(--gray-900);margin:0\">Networks and Multimedia</p>",
  "    </div>",
  "    <div style=\"border-left:3px solid var(--orange);padding:0.75rem 1rem;background:var(--gray-50);border-radius:0 8px 8px 0\">",
  "      <p style=\"font-family:'Space Mono',monospace;font-size:0.7rem;text-transform:uppercase;letter-spacing:0.08em;color:var(--orange);margin:0 0 0.25rem\">2010 – 2020</p>",
  "      <p style=\"font-family:'Instrument Sans',sans-serif;font-weight:600;font-size:0.95rem;color:var(--gray-900);margin:0\">Broadband, Semantic Technologies, Mobile Computing and Cloud Storage</p>",
  "    </div>",
  "  </div>",
  "</div>",
].join("\n");

const blockchain = [
  "## What is Blockchain?",
  "",
  "Blockchains are like **decentralized digital ledgers**. Online networks where data is saved on each user's computer, not just on a single server.",
  "",
  "To understand what this means in practice, think of two real-world situations:",
  "",
  "**The notary office:** When you buy a property, the contract needs to be registered with a notary — a central entity that authenticates, stores, and validates the document. Without it, the transaction has no legal standing. Blockchain works in a similar way, but without any notary: the record is made in a distributed way by thousands of computers simultaneously, and each one confirms that the transaction is legitimate. Nobody controls the notary — the entire system is the notary.",
  "",
  "**The HR or financial ledger of a company:** Every company has a ledger — physical or digital — where all entries and exits are recorded: payments, hires, expenses. This ledger is managed by a specific person or department. If that person alters a record without authorization, it can be hard to detect. In blockchain, that ledger exists as identical copies on all computers in the network. To alter any record, you would need to alter all of those computers simultaneously — which is computationally unfeasible.",
  "",
  "In short: blockchain is a way to record information so that anyone can verify it, nobody can erase it, and no central authority needs to guarantee it.",
  "",
  "## History",
  "",
  "Blockchain is not a new concept — but it's not as old as it might seem either. It was born from **cryptography**, a field of mathematics and computer science that has existed for centuries, but took computational form in the 1970s. When Ralph Merkle published his Merkle Tree in 1979, there were already decades of accumulated research on how to protect and verify digital information. Merkle simply made public something that took years to think through.",
  "",
  "Throughout the 1980s and 90s, researchers like David Chaum, Stuart Haber, Scott Stornetta, and Hal Finney were building, piece by piece, the foundations of what would become blockchain: tamper-proof records, digital signatures, proof of work, electronic cash. None of them were trying to create a cryptocurrency — they were solving problems of trust, privacy, and authenticity in digital systems.",
  "",
  "In 2008, Satoshi Nakamoto assembled these pieces into a whitepaper and created Bitcoin — not inventing from scratch, but synthesizing decades of research into a working system. The logic is the same as the internet itself: the public web emerged in the 90s, but the protocols that made it possible had been in development since the 60s.",
  "",
  "![bitcoin.org website when it launched](/wiki/images/bitcoin-dot-org-10-years.gif)",
  "",
  "Since then, evolution has been rapid. Ethereum (2015) expanded blockchain beyond currencies, introducing smart contracts. DeFi, NFTs, and DAOs transformed the technology into infrastructure for decentralized applications of all kinds. Today, governments, companies, and communities around the world use blockchain for supply chain, digital identity, voting, art, and much more — and the field is still far from its limits.",
  "",
  "| Year | Event |",
  "|------|-------|",
  "| **1979** | Ralph Merkle creates and patents the concept of the Merkle Tree. |",
  "| **1982** | David Chaum at Berkeley describes the foundations of blockchain technology, except for proof of work. Chaum is also credited with inventing digital cash and founded DigiCash in 1989. |",
  "| **1991** | Stuart Haber and Scott Stornetta publish *How to Time-Stamp a Digital Document* — the first concept of Blockchain, using a Merkle Tree. |",
  "| **1992** | The Merkle Tree is introduced into cryptography and computer science. Creation of the **cypherpunk** mailing list, a group that advocates for privacy and individual freedom using cryptography as a tool for social change. |",
  "| **1993** | Cynthia Dwork and Moni Naor publish the foundations of Proof of Work (PoW). |",
  "| **1997** | Adam Black introduces hashcash, a PoW algorithm for denial-of-service countermeasures. |",
  "| **1999** | Markus Jakobsson and Ari Juels publish the term *proof of work*. The P2P network is popularized by Napster. |",
  "| **2000** | Stefan Konst proposes cryptographically secured chains in *Secure Log Files Based on Cryptographically Concatenated Entries*. |",
  "| **2002** | David Mazières and Dennis Shasha propose how to store data using blocks with the SUNDR structure. |",
  "| **2004** | Hal Finney introduces Reusable Proof of Work (RPoW), a precursor mechanism to Bitcoin mining. |",
  "| **2005** | Nick Szabo proposes a cryptocurrency called *Bitgold*. |",
  "| **2008** | Satoshi Nakamoto publishes *Bitcoin: A Peer-to-Peer Electronic Cash System*, introducing the concept of blockchain and cryptocurrency. Nakamoto's real identity remains a mystery. |",
  "| **2009** | The first Bitcoin is mined — the Genesis block (block 0), containing 50 BTC. Nakamoto sends 10 BTC to Hal Finney in the first Bitcoin transaction. Bitcoin v0.1 is released as open source software. |",
  "| **2010** | **Bitcoin Pizza Day** — on May 22nd, Laszlo Hanyecz trades 10,000 BTC for 2 Papa John's pizzas in the US. The first recorded real-world purchase paid with cryptocurrency. Mt. Gox is founded as a Bitcoin exchange. |",
  "| **2011** | 1/4 of the 21 million BTC already mined. Bitcoin reaches parity with the US dollar. Litecoin is launched, one of the first alternative cryptocurrencies. |",
  "| **2012** | The Bitcoin Foundation is established. Coinbase raises over $600K in seed funding. The Ripple protocol for real-time payments is born. |",
  "| **2013** | Bitcoin market surpasses $1 billion. First Bitcoin ATM launched in Vancouver. Vitalik Buterin publishes the Ethereum whitepaper. |",
  "| **2014** | Vitalik Buterin publishes the Ethereum whitepaper. Mt. Gox files for bankruptcy. Ethereum holds a crowdsale: 60 million ETH sold for ~$18 million. **R3** is founded, a banking consortium to bring blockchain to the corporate world. |",
  "| **2015** | The Ethereum network officially launches with its first block mined. The Linux Foundation launches **Hyperledger**. Nasdaq initiates a blockchain trial. Nine major banks form the R3 consortium, which grows to over 40 financial institutions in six months. |",
  "| **2016** | The term *blockchain* gains acceptance as a single word. R3 launches **Corda**, the first blockchain platform for enterprises. The Ethereum DAO is hacked due to a code vulnerability — causing a hard fork in the network. |",
  "| **2017** | Bitcoin hits a record high of nearly $20,000. Japan recognizes Bitcoin as legal currency. Dan Larimer launches **EOS**. About 15% of global banks used blockchain technology in some capacity. |",
  "| **2018** | The European Commission launches the Blockchain Observatory and Forum. Google, Twitter and Facebook ban cryptocurrency advertising. Forbes highlights 9 blockchain companies among the top 50 fintechs of the year. |",
  "| **2019** | Walmart launches a supply chain system based on Hyperledger. Amazon makes managed blockchain available on AWS. Ethereum network transactions exceed 1 million per day. |",
  "| **2020** | 40% of companies surveyed by Deloitte already using blockchain in production. Ethereum launches the Beacon Chain in preparation for Ethereum 2.0. |",
  "| **2021** | Bitcoin reaches an all-time high of $68,789. DeFi grows 600% to $200 billion. NFT artwork sells for $69 million at Christie's. NFT boom with digital artworks selling for record values. Launch of **hic et nunc**, a platform created by Brazilian developer Rafael and a small team in Brasília. |",
  "| **2022** | Collapse of the FTX exchange and arrest of Sam Bankman-Fried. Ethereum migrates to Proof of Stake. Bitcoin mining approaches 19 million of the 21 million limit. |",
  "| **2023** | SEC indicts executives at Coinbase and Binance. Companies continue adopting blockchain with greater caution. Bitcoin stabilizes in the $25,000–$30,000 range. |",
  "",
  "## How does a Blockchain work?",
  "",
  "Imagine you want to send money to someone without going through a bank. On the blockchain, this happens in four steps — no intermediaries, no central server, no possibility of fraud.",
  "",
  "![How Blockchain works — diagram with 4 steps](/wiki/images/how-blockchain-works.svg)",
  "",
  "**① You request a transaction**",
  "Your request is encoded in a block containing: who sends, who receives, and the value. Think of it as a sealed envelope with all the necessary information.",
  "",
  "**② The entire network finds out**",
  "That block is broadcast to thousands of computers around the world — the network's *nodes*. Each one independently verifies whether the transaction is valid.",
  "",
  "**③ The nodes reach consensus**",
  "The network needs to agree on which block will be added. This process — called *consensus* — can happen through mining (PoW) or validation (PoS). Learn more at [Consensus Mechanisms](consensus-mechanisms).",
  "",
  "**④ The transaction is recorded forever**",
  "The approved block is added to the chain permanently and immutably. No one can erase, alter, or reverse it — not even the creator of the transaction.",
  "",
  "## Block Explorers",
  "",
  "A **block explorer** is a platform where anyone can publicly consult the blockchain in real time — viewing transactions, addresses, blocks, and other network data. Think of it as a search engine for the blockchain.",
  "",
  "![Solscan — Solana network block explorer](/wiki/images/solscan.png)",
  "",
  "Each network has its own explorer. Some examples:",
  "",
  "| Blockchain | Explorer |",
  "|------------|---------|",
  "| Bitcoin | [mempool.space](https://mempool.space) · [blockchain.com](https://www.blockchain.com/explorer) |",
  "| Ethereum | [Etherscan](https://etherscan.io) |",
  "| Solana | [Solscan](https://solscan.io) · [Solana Explorer](https://explorer.solana.com) |",
  "| Tezos | [TzKT](https://tzkt.io) · [tzstats](https://tzstats.com) |",
  "| Polygon | [Polygonscan](https://polygonscan.com) |",
  "| Avalanche | [Snowtrace](https://snowtrace.io) |",
  "| Stellar | [Stellar Expert](https://stellar.expert) |",
  "",
  "## Consensus Mechanisms",
  "",
  "For all computers on the network to agree on which transactions are valid, the blockchain uses **consensus mechanisms** — protocols that ensure security and integrity without a central authority.",
  "",
  "The main mechanisms are Proof of Work (PoW), Proof of Stake (PoS), Proof of Authority (PoA), and Proof of History (PoH) — each with different ways of mining and validating blocks.",
  "",
  "> See the full article: [Consensus Mechanisms](consensus-mechanisms)",
  "",
  "## Blockchain Properties",
  "",
  "**Decentralization:** In traditional centralized systems, transactions go through an intermediary — like a bank. In blockchain, the goal is to eliminate this central authority. The network is made up of multiple computers (*nodes*) working simultaneously and in a distributed way, with no single entity in control.",
  "",
  "**Transparency:** All transactions are public and traceable via block explorers. Even if users are anonymous, their transactions can be seen through their public addresses.",
  "",
  "**Immutability:** Once recorded on the blockchain, data cannot be altered. If incorrect information is added, a new record must be created — and the incorrect one burned. Validated transactions cannot be removed or reversed.",
  "",
  "**Anonymity:** Users have public addresses (not personal identity). It's not possible to identify who is using an address, since personal data like name, documents, and physical address are not required. The level of anonymity varies — networks like [Monero](https://www.getmonero.org) and [Zcash](https://z.cash) offer full anonymity, while others use only pseudonyms.",
  "",
  "**Auditability:** All transactions can be verified and traced using a block explorer. Private blockchains are being considered for commercial and governmental use cases.",
  "",
  "## Types of Blockchains",
  "",
  "**Public Blockchain:** Open access — anyone can join the network without restrictions. Most transactions have a cost (transaction fees), used to incentivize nodes to validate and include transactions in blocks. They are transparent, decentralized, and secure. Examples: Bitcoin, Ethereum, Solana.",
  "",
  "**Private Blockchain:** Access is restricted to authorized participants. Useful for companies that want to share sensitive information with partners. They tend to have better performance since the number of nodes is smaller, but can be more vulnerable if the controlling entity is compromised.",
  "",
  "**Consortium Blockchain:** A partnership between companies that join to build a shared blockchain network. More common in sectors like finance, healthcare, and logistics. Example: R3 Corda.",
  "",
  "## Blockchain Layers",
  "",
  "Layers are a way to organize the complexity of the technology behind cryptocurrencies and decentralized applications.",
  "",
  "| Layer | Function | Examples |",
  "|-------|----------|---------|",
  "| **L0** | Infrastructure and interoperability between blockchains | Polkadot, Cosmos, Chainlink |",
  "| **L1** | Main blockchains — foundation for all projects built on top | Bitcoin, Ethereum, Solana, BNB Chain |",
  "| **L2** | Scalability and fee reduction — networks on top of L1 | Optimism, Polygon, Arbitrum |",
  "| **L3** | Cross-chain solutions and interoperability between blockchains | IBC Protocol, Quant, ICON |",
  "",
  "> **Network latency** is the delay in network communication — the time it takes for data to be transferred. L2 solutions help reduce latency and fees on the main network.",
  "",
  "## Blockchain Applications",
  "",
  "**DeFi — Decentralized Finance:** Cryptocurrencies enable global transactions without intermediaries like banks. Blockchain makes possible peer-to-peer financial services such as lending, payments, and investments.",
  "",
  "**Smart Contracts:** Self-executing programs that run on the blockchain. Agreements are fulfilled automatically once predefined conditions are met — eliminating intermediaries. Used in logistics, real estate, insurance, and much more.",
  "",
  "**Voting and Governance:** Blockchain enables secure, fraud-proof electronic voting systems with reliable and immutable results. Decentralized governance allows communities to actively participate in decisions.",
  "",
  "**Digital Asset Ownership:** Through tokenization, blockchain enables decentralized markets for buying, selling, and trading assets like art, music, intellectual property, and physical goods.",
  "",
  "**Digital Identity:** Blockchain-based digital identities can become more secure, user-controlled, and globally accessible — without relying on a central entity.",
].join("\n");

const miningValidation = [
  "Consensus mechanisms are protocols that allow a decentralized network of computers to agree on the state of the blockchain — that is, which transactions are valid and in what order they should be added.",
  "",
  "These mechanisms are crucial for ensuring the security, integrity, and reliability of the blockchain, preventing fraud and ensuring that all network participants have an identical and up-to-date copy of the ledger.",
  "",
  "## Proof of Work (PoW)",
  "",
  "**Mining:** Miners compete to solve a complex mathematical problem (cryptographic hash). The first miner to find the solution *proves* their work, adds the block to the blockchain, and is rewarded with cryptocurrency.",
  "",
  "**Validation:** If the majority of other nodes agree with the miner's work, the block is added to the blockchain.",
  "",
  "**Examples:** Bitcoin (BTC) · Litecoin (LTC) · Monero (XMR)",
  "",
  "## Proof of Stake (PoS)",
  "",
  "**Mining:** No mining. Validators are chosen to propose and validate blocks based on the amount of cryptocurrency they hold and are willing to *stake*. The larger the stake, the higher the chance of being selected.",
  "",
  "**Validation:** Other validators verify the validity of the block. If the majority agrees, the block is added to the blockchain.",
  "",
  "**Examples:** Ethereum (ETH) · Cardano (ADA) · Tezos (XTZ) · Avalanche (AVAX) · Algorand (ALGO)",
  "",
  "## Proof of Authority (PoA)",
  "",
  "**Mining:** No mining. Validators are pre-selected and authorized to create and validate blocks.",
  "",
  "**Validation:** Authorized validators verify transactions and add them to the blockchain.",
  "",
  "**Examples:** Binance Coin (BNB) · VeChain (VET) · XRP",
  "",
  "## Proof of History (PoH)",
  "",
  "**Mining:** No mining. The system uses an immutable record of past events (hashgraph) to determine the order of transactions and the validity of blocks.",
  "",
  "**Validation:** Validation is performed by a group of nodes that verify the order of transactions and the integrity of the hashgraph.",
  "",
  "**Examples:** Hedera Hashgraph (HBAR)",
  "",
  "## The special case of Solana",
  "",
  "Solana combines two mechanisms: **PoH + PoS**. PoH acts as an internal clock — each event on the network receives a cryptographic timestamp, creating a verifiable order of transactions before validation even begins. This historical record allows validators (selected by PoS) to work in parallel, without waiting for each other to confirm block order.",
  "",
  "The result is a much faster network: while Ethereum processes ~15 transactions per second, Solana can reach tens of thousands.",
  "",
  "## Comparison",
  "",
  "| Mechanism | Mining | Validation | Examples |",
  "|-----------|--------|------------|---------|",
  "| **PoW** | Competition via cryptographic hash | Majority of nodes agree | Bitcoin, Litecoin, Monero |",
  "| **PoS** | No mining — selection by stake | Majority of validators agree | Ethereum, Cardano, Tezos |",
  "| **PoA** | No mining — pre-authorized validators | Authorized validators | Binance Coin, VeChain, XRP |",
  "| **PoH** | No mining — historical record (hashgraph) | Nodes verify order and integrity | Hedera Hashgraph |",
  "| **PoH + PoS** | No mining — cryptographic clock + stake | Validators in parallel | Solana |",
  "",
  "> Back to: [Blockchain Technology](blockchain)",
].join("\n");

const cryptography = [
  "**Cryptography** is the transformation of readable data into encoded data — which can only be deciphered with the right key. It is the technology that makes blockchain possible: without it, there would be no way to guarantee that transactions are authentic, that data hasn't been tampered with, or that a digital coin hasn't been spent twice.",
  "",
  "## Why crypto is called crypto",
  "",
  "The prefix *crypto* comes from the Greek *kryptós* — hidden, secret. **Cryptocurrency** literally means currency protected by cryptography. It's not just a name — it's a description of what it is: a currency whose security and authenticity depend entirely on cryptographic functions.",
  "",
  "## The Merkle Tree",
  "",
  "One of the most important structures for the blockchain is the **Merkle Tree**, created by Ralph Merkle in 1979.",
  "",
  "Here's how it works: each transaction generates a unique code called a *hash*. These hashes are grouped in pairs and combined into new hashes — and so on, until a single hash remains at the top, called the **Merkle Root**.",
  "",
  "This process creates a fingerprint of the entire block. If any transaction is altered — even slightly — the Merkle Root changes completely. This makes tampering immediately detectable by any node on the network.",
  "",
  "This is why the blockchain is **immutable**: not because it's physically impossible to alter data, but because any change breaks the chain of hashes and is rejected by the network.",
  "",
  "> See the full timeline of how this led to the creation of Bitcoin in [Blockchain Technology](blockchain).",
  "",
  "## How cryptography protects the blockchain",
  "",
  "**Authenticity:** Each transaction is signed with the sender's private key. Only the key holder can authorize a transfer — but anyone can verify the signature is legitimate using the public key.",
  "",
  "**Integrity:** The hash of each block includes the hash of the previous block. Altering any old block invalidates all subsequent blocks — making fraud computationally unfeasible.",
  "",
  "**Decentralization:** Because verification is mathematical, there's no need for a central authority. Any node can confirm a transaction is valid using only cryptographic rules.",
].join("\n");

const security = [
  "A **wallet** is like a bank account for your digital currencies. Made to store crypto obtained through purchase, transfer, or mining/validation. It is the main way to interact with Web3 sites and applications.",
  "",
  "Wallets work in different ways depending on the type: **extension wallets** run directly in your browser — you install them as a plugin and access them via an icon in the browser bar, connecting to any Web3 site with one click. **Mobile wallets** work as smartphone apps, using QR codes to make transactions easier. **Desktop wallets** are programs installed on your computer. **Hardware wallets** are physical devices you connect to your computer to sign transactions with maximum security.",
  "",
  "> **Tip:** Use the [Brave](https://brave.com) browser — it's privacy-focused, blocks ads natively, and has a built-in crypto wallet compatible with Ethereum, Solana, and other networks.",
  "",
  "## Security Keys",
  "",
  "**Public Keys:** Like bank account numbers — a sequence of numbers and letters randomly generated when creating a wallet. It's the information needed to transfer or receive digital assets. Safe to share.",
  "",
  "**Private Keys / Seed Phrase:** Must be kept secret and in a safe physical location. The seed phrase is the most important part of security — with it you can recover the same account on different devices.",
  "",
  "![Seed phrase — paper with secret words](/wiki/images/seed-phrase.png)",
  "",
  "> Warning: These keys should never be kept in digital files or emails. Once you lose your seed phrase, it is impossible to recover your wallet. There is no recovery system.",
  "",
  "## Types of Wallets",
  "",
  "### Digital Wallet (Hot Wallet)",
  "",
  "Software wallets used on desktop and mobile apps. These are non-custodial — no central institution or third party holds the wallet's funds. Commonly linked to trading platforms, allowing users to monitor their crypto balance while keeping their private keys.",
  "",
  "Desktop wallets are typically free and many use open-source programming. Most desktop wallets have mobile equivalents, allowing users to switch from a desktop to a mobile device.",
  "",
  "### Hardware Wallet (Cold Wallet)",
  "",
  "Hardware wallets are physical devices for managing your crypto — they come in various formats and also contain public and private keys. To perform operations, you connect the hardware to a computer via cable or wirelessly using the model's specific software.",
  "",
  "They are often called cold wallets, but it is possible to connect them to the internet — which is not recommended if you want to use them as a storage method.",
  "",
  "They can be purchased directly from the brands that produce them or from specialized resellers. **Always use official brand websites to buy — avoid purchasing from unauthorized resellers and unknown individuals for security reasons.**",
  "",
  "Known brands: [Ledger](https://www.ledger.com) · [Trezor](https://trezor.io) · [Ngrave](https://www.ngrave.io) · [BC Vault](https://bc-vault.com) · [Ellipal](https://www.ellipal.com)",
  "",
  "![Hardware wallets — Trezor, Ledger and Ngrave physical devices](/wiki/images/hardware-wallets.png)",
  "",
  "## Wallets by Blockchain",
  "",
  "| Blockchain | Wallets |",
  "|------------|---------|",
  "| **Bitcoin** | [Phantom](https://phantom.app) · [Nightly](https://nightly.app) · [Xverse](https://xverse.app) |",
  "| **Solana** | [Phantom](https://phantom.app) · [Solflare](https://solflare.com) · [Nightly](https://nightly.app) |",
  "| **Tezos** | [Temple](https://templewallet.com) · [Kukai](https://kukai.app) |",
  "| **Ethereum** | [MetaMask](https://metamask.io) · [Rainbow](https://rainbow.me) · [Rabby](https://rabby.io) · [Brave Wallet](https://brave.com/wallet) |",
  "| **Ethereum L2s** (Optimism, Arbitrum, Base) | [MetaMask](https://metamask.io) · [Rainbow](https://rainbow.me) · [Rabby](https://rabby.io) |",
  "| **Scroll** | [MetaMask](https://metamask.io) · [Rabby](https://rabby.io) |",
  "| **Monad** | [MetaMask](https://metamask.io) · [Phantom](https://phantom.app) |",
  "| **Avalanche** | [Core](https://core.app) · [MetaMask](https://metamask.io) |",
  "| **Algorand** | [Pera](https://perawallet.app) · [Defly](https://defly.app) |",
  "| **Stellar** | [Hana](https://www.hana.money) · [Lobstr](https://lobstr.co) · [Freighter](https://freighter.app) |",
  "| **NEAR** | [MyNearWallet](https://mynearwallet.com) · [Meteor](https://meteorwallet.app) |",
  "| **Sui** | [Sui Wallet](https://suiwallet.com) · [Suiet](https://suiet.app) |",
  "",
  "> This table covers the main networks, but there are many other blockchains. Explore [DappRadar](https://dappradar.com) to discover more networks and wallets.",
  "",
  "## Common Scams",
  "",
  "<div class=\"callout callout-info\"><span class=\"callout-icon\">⚠️</span><div><p class=\"callout-title\">Fake Instagram Profiles</p>Pretend to be collectors and offer high prices for your work, then ask for a fee to finalize the sale — which never happens.</div></div>",
  "",
  "<div class=\"callout callout-info\"><span class=\"callout-icon\">⚠️</span><div><p class=\"callout-title\">Fake Job Proposals</p>Offer commissions or game tests with files infected with malware that scan your computer to invade your wallets.</div></div>",
  "",
  "<div class=\"callout callout-info\"><span class=\"callout-icon\">⚠️</span><div><p class=\"callout-title\">Fraudulent Sites</p>Clones of popular projects. When you connect your wallet, they drain all your funds instantly.</div></div>",
  "",
  "## Security Measures",
  "",
  "<div class=\"callout callout-concept\"><span class=\"callout-icon\">🔑</span><div><p class=\"callout-title\">Never share your keys</p>Your private key and seed phrase must never be typed into any website, app, or message. No legitimate platform will ever ask for them.</div></div>",
  "",
  "<div class=\"callout callout-concept\"><span class=\"callout-icon\">🔗</span><div><p class=\"callout-title\">Don't click on unknown links</p>Links sent via DM, email, or social media may be traps. Always access sites by typing the address directly into your browser.</div></div>",
  "",
  "<div class=\"callout callout-concept\"><span class=\"callout-icon\">📎</span><div><p class=\"callout-title\">Don't open attachments from unknown profiles</p>Files sent by strangers may contain malware designed to steal your wallet data.</div></div>",
  "",
  "<div class=\"callout callout-concept\"><span class=\"callout-icon\">🌐</span><div><p class=\"callout-title\">Don't connect your wallet to just any site</p>Before connecting, carefully verify the site address. Fake sites can drain your wallet instantly.</div></div>",
  "",
  "<div class=\"callout callout-concept\"><span class=\"callout-icon\">💰</span><div><p class=\"callout-title\">Be skeptical of exorbitant proposals</p>Offers that sound too good to be true usually are. In the crypto world, FOMO is one of scammers' main tools.</div></div>",
  "",
  "<div class=\"callout callout-concept\"><span class=\"callout-icon\">📦</span><div><p class=\"callout-title\">Store keys in a safe physical location</p>Write your seed phrase on paper and keep it somewhere secure, away from cameras and other people. Never in digital files.</div></div>",
  "",
  "<div class=\"callout callout-concept\"><span class=\"callout-icon\">🛡️</span><div><p class=\"callout-title\">Use anti-phishing extensions</p>Install extensions like <a href=\"https://www.pocketuniverse.app\" target=\"_blank\">Pocket Universe</a> and <a href=\"https://www.walletguard.app\" target=\"_blank\">Wallet Guard</a> for real-time alerts on suspicious sites and transactions.</div></div>",
].join("\n");

const nfts = [
  "## What are NFTs?",
  "",
  "We can understand an **NFT** as the **digital certificate of ownership of an item**. This certificate is created and registered on a Blockchain network and can contain files, links, text, or code.",
  "",
  "NFT stands for **Non-Fungible Token**. Fungible = replaceable (money, cars). Non-fungible = unique, irreplaceable (artworks, real estate).",
  "",
  "## Metadata",
  "",
  "NFT metadata is like labels with the properties of a digital asset: file description, name, categories, transaction history, date and time.",
  "",
  "**On-chain:** The information is stored directly on the Blockchain network, integrated into the NFT itself.",
  "",
  "**Off-chain:** The information is stored on servers or cloud storage systems (IPFS). Most metadata is stored off-chain as a JSON file.",
  "",
  "## Dynamic NFTs (dNFTs)",
  "",
  "NFTs whose characteristics can change — also known as semi-fungible or living NFTs. Widely used in DeFi games (evolving badges) and in art (pieces that change according to rules defined by the artist).",
  "",
  "Example: Basketball player LaMelo Ball's NFTs incorporate sports data on the network and change depending on game results.",
  "",
  "## How to make an NFT",
  "",
  "**Step 1:** Choose the Blockchain (Ethereum, Solana, Tezos...)",
  "",
  "**Step 2:** Choose the Platform (see Platforms section)",
  "",
  "**Step 3:** Generate a file (your art, music, video, code...)",
  "",
  "**Step 4:** Mint the file on the Platform",
  "",
  "**Step 5:** List the NFT (price, edition, conditions)",
  "",
  "**Step 6:** Promotion — build visibility through your community",
].join("\n");

const communities = [
  "An **NFT community** is a digital group of people interested in NFTs, who gather to discuss, create, buy, sell, and trade these tokens. Communities are crucial — it's impossible to thrive without community in this environment.",
  "",
  "## Types of NFT Communities",
  "",
  "**Project communities:** Centered around a specific NFT project, such as a digital art collection.",
  "",
  "**Collector communities:** Bring together people interested in collecting NFTs, regardless of the project.",
  "",
  "**Artist communities:** Focused on digital artists who create NFTs.",
  "",
  "**Investor communities:** Made up of people who invest in NFTs for profit.",
  "",
  "## How to participate",
  "",
  "Use common social platforms: Discord, Twitter/X, and Warpcast. Be consistent and patient — building a loyal community takes time and effort. Be authentic and transparent about your goals.",
  "",
  "## Tips for beginners",
  "",
  "1. Don't trust easy money — don't expect to be a millionaire in 2 weeks.",
  "2. Use NFTs as a tool to showcase your work.",
  "3. Don't believe in posts like 'drop your NFT here' (engagement farming).",
  "4. Never create the same art on different Blockchains.",
  "5. Don't flood chats with too many messages.",
  "",
  "## Social Initiatives",
  "",
  "The **Balot NFT** initiative, led by the Congolese Plantation Workers Art League (CATPC), used NFT technology to reclaim cultural heritage and buy back lands stolen by plantations in the Congo. Each Balot NFT represents one hectare of land, and the funds are used to replant forests.",
  "",
  "## Critical Perspective",
  "",
  "> The virtual environment is just an extension of our physical world — it obviously reflects and reproduces the social problems that exist in real life. The NFT landscape is not free of politics. All technology is a tool. The outcome of its use depends on who is using it.",
].join("\n");

const platforms = [
  "Below is an overview of platforms available on different blockchains. Explore **DappRadar** to discover platforms on many other networks.",
  "",
  "## Ethereum and its L2s",
  "",
  "**Zora** — creator-focused, free minting",
  "**Super Rare** — curated 1/1 artwork marketplace",
  "**Foundation** — invite-curated platform",
  "**Manifold** — tools for custom smart contracts",
  "**Rarible** — multi-chain, focus on creator royalties",
  "",
  "## Solana",
  "",
  "**3.land** — community and exhibitions",
  "**Exchange Art** — curated digital art",
  "**Magic Eden** — largest Solana marketplace",
  "**Tensor** — trading and analytics",
  "",
  "## Tezos",
  "",
  "**Objkt** — largest Tezos marketplace",
  "**(fx)hash** — generative art",
  "**teia** — community-owned, artist-centered",
  "",
  "## Bitcoin Ordinals",
  "",
  "**Gamma** · **Magic Eden** · **Ordzaa**",
  "",
  "## How to choose a platform?",
  "",
  "**Fees:** Tezos and Solana have very low fees; Ethereum is higher.",
  "",
  "**Community:** Different platforms attract different collector communities.",
  "",
  "**Curation:** Open (Objkt, Magic Eden) vs. curated (Super Rare, Foundation).",
  "",
  "**Mission:** teia is community-owned; other platforms are commercial.",
  "",
  "> Remember: platforms can change and even shut down — but NFTs remain on the blockchain. Always be prepared to adapt.",
].join("\n");

const communication = [
  "NFT communities are built on essential social networks. These spaces are necessary to connect artists and collectors.",
  "",
  "## X (formerly Twitter)",
  "",
  "One of the most used platforms for promoting NFTs. Many artists, traders, and people in the crypto space have dedicated profiles on this topic. Despite recent changes, it's still an important network for the NFT world.",
  "",
  "## Discord",
  "",
  "Another essential place for NFT communities. Artists, investors, and collectors can connect, organize, and chat. Many NFT platforms, artists, and projects have their own Discord servers.",
  "",
  "## Warpcast / Farcaster",
  "",
  "An app made by the Farcaster project team — a **decentralized social network**. Focused on crypto users. Annual fee to use the platform.",
  "",
  "## Nostr",
  "",
  "A simple, open protocol that enables global, decentralized, and censorship-resistant social media. Several networks use this protocol.",
  "",
  "## Choosing your platforms",
  "",
  "You don't need to be everywhere. Start with 1-2 platforms and build genuine connections before expanding. **Consistency and authenticity matter more than volume.**",
].join("\n");

const marketing = [
  "## 1. Build a Strong Identity",
  "",
  "Develop a visual identity and maintain a consistent voice that represents your personality.",
  "",
  "## 2. Be Active on Social Media",
  "",
  "Engage with your audience, share your work, and participate in conversations related to your field.",
  "",
  "## 3. Organization is Key",
  "",
  "Use post scheduling tools, maintain a release calendar, and always stay on top of deadlines and opportunities.",
  "",
  "## 4. Build Meaningful Connections",
  "",
  "Comment genuinely on other people's work. Participate in collaborative projects. Show up consistently in communities you care about. Offer help before asking for it.",
  "",
  "## 5. Release Frequency",
  "",
  "Find a sustainable rhythm for yourself. Burnout doesn't help anyone.",
  "",
  "## 6. Pricing Strategies",
  "",
  "**Don't undervalue yourself!** Consider scarcity, demand, currency value, and your time and craft.",
  "",
  "## 7. Stay Creative and Connected",
  "",
  "Even during slower sales periods, keep creating and staying connected with your audience.",
  "",
  "## 8. Be Prepared for Change",
  "",
  "Platforms can change and even close — which doesn't make NFTs disappear, as they're on the blockchain. It's crucial to always be experimenting with new possibilities.",
  "",
  "> Good marketing in the NFT space is about being genuinely present, sharing authentically, building relationships before transactions, and maintaining consistency over time.",
].join("\n");

const about = [
  "**Computadores Fazem Arte** is an educational wiki about Blockchain, Web3, and NFTs — developed as an integral part of master's research in **Digital Artifact Design** at the Federal University of Pernambuco (UFPE), funded by CNPq's MAI/DAI program.",
  "",
  "## The Name",
  "",
  "The project's name comes from a verse by **Fred Zero Quatro**, vocalist of the legendary Recife band Mundo Livre S/A, from the song *Computadores Fazem Arte*.",
  "",
  "> Computers advance / Artists hitch a ride / Scientists create the new / Artists take the fame — Fred Zero Quatro",
  "",
  "The song is both an observation and a provocation — and gave its name to a project that tries to think critically about what it means for artists to inhabit technological spaces.",
  "",
  "Watch the song: https://www.youtube.com/watch?v=KZg_m0z4NLI",
  "",
  "## Undergraduate Research",
  "",
  "As part of the research, three undergraduate students were supervised in different fields of knowledge — a deliberate interdisciplinary choice that reflects the project's own values.",
  "",
  "### Milena — Pedagogy",
  "Brought an educational perspective to the project, helping think about how complex technological concepts can be made accessible to diverse audiences.",
  "",
  "### Vitória — Design",
  "Contributed a visual and communicational perspective, essential for shaping how the wiki and its materials are presented.",
  "",
  "### Artur — Computer Science · in memoriam",
  "Artur joined the research as a volunteer — driven entirely by his own curiosity and enthusiasm. He was one of the most engaged and active participants in the project, bringing technical rigor and genuine excitement to every meeting. His presence left a mark on this research that cannot be measured. This project carries a piece of him.",
  "",
  "## In-Person Course — CTG/UFPE, 2024",
  "",
  "In 2024, a four-week in-person course was held at the Center for Technology and Geosciences (CTG) at UFPE — bringing together students from different fields to learn about Blockchain, NFTs, and digital art communities.",
  "",
  "The course closing was interrupted by the **Twitter/X ban in Brazil** — a moment that became part of the project's own history and a live case study: a reminder that the same platforms that host digital art communities are subject to political decisions, regulatory pressures, and corporate power.",
  "",
  "The regulation of social media platforms is not a secondary topic — it is central to any honest conversation about digital rights, freedom of expression, and the conditions under which artists create and distribute their work. Platforms must be held accountable for guaranteeing users' fundamental rights.",
  "",
  "## Publication — WebMedia 2024",
  "",
  "The material developed in this research was published and presented at **WebMedia 2024**, held at the Federal University of Juiz de Fora (UFJF).",
  "",
  "[Access the publication](https://books-sol.sbc.org.br/index.php/sbc/catalog/view/177/779/1513)",
  "",
  "## Course — Design for Web3, UFPE 2025",
  "",
  "In 2025, the research led to an invitation from **Professor Leonardo Castillo** to teach the course *Design for Web3* in UFPE's Design program.",
  "",
  "## Contact",
  "",
  "**Numa** · [@numadessas](https://twitter.com/numadessas) · [contato@numadessas.com.br](mailto:contato@numadessas.com.br) · [numadessas.com.br](https://numadessas.com.br)",
].join("\n");

const references = [
  "## Academic Works",
  "",
  "**ASSANGE, Julian et al.** Cypherpunks: Freedom and the Future of the Internet. New York: OR Books, 2012.",
  "",
  "**PANDA, Sandeep Kumar et al.** Bitcoin and Blockchain: History and Current Applications. 2020, CRC Press.",
  "",
  "**AL-SAQAF, Walid; SEIDLER, Nicolas.** Blockchain technology for social impact. 2017, Journal of Cyber Policy.",
  "",
  "**KENT, Charlotte.** Blockchain manifestos: fighting for the imagination of a culture. 2021, Burlington Contemporary Journal.",
  "",
  "**LIMA, Júnior César de; CARVALHO, Cedric L. de.** Uma Visão da Web Semântica. 2004, UFG.",
  "",
  "## Online Resources",
  "",
  "- [CoinMarketCap Glossary](https://coinmarketcap.com/academy/en/glossary)",
  "- [Web3 Foundation](https://web3.foundation/)",
  "- [Chainlink — What is a Dynamic NFT?](https://chain.link/education-hub/what-is-dynamic-nft)",
  "- [DappRadar](https://dappradar.com/)",
  "- [Solana: A Primer — Shinobi Systems](https://www.shinobi-systems.com/primer.html)",
  "- [When the Social meets the Semantic: Social Semantic Web or Web 2.5 — Fernandez-Llatas & Traver](https://www.mdpi.com/1999-5903/4/3/852)",
  "- [A Timeline and History of Blockchain Technology — TechTarget](https://www.techtarget.com/whatis/feature/A-timeline-and-history-of-blockchain-technology)",
  "",
  "## About this Project",
  "",
  "This wiki was developed by **Numa** as an integral part of master's research in Digital Artifact Design at UFPE, funded by CNPq's MAI/DAI program.",
  "",
  "Contact: [contato@numadessas.com.br](mailto:contato@numadessas.com.br)",
  "",
  "*Content available for free distribution.*",
].join("\n");

export const wikiSections = [
  {
    id: "introduction",
    slug: "introduction",
    title: "Introduction",
    subtitle: "About this wiki",
    tags: ["overview", "web3", "nft"],
    description: "What is Computadores Fazem Arte and why this knowledge matters.",
    related: ["glossary", "internet-generations"],
    content: intro,
  },
  {
    id: "glossary",
    slug: "glossary",
    title: "Glossary",
    subtitle: "Essential terms",
    tags: ["reference", "terminology"],
    description: "Essential vocabulary for navigating the Web3 and NFT space.",
    related: ["introduction", "blockchain"],
    isGlossary: true,
    content: "Essential vocabulary for navigating the Web3 and NFT space. Click on any term to expand its definition.",
    glossaryTerms: [
      { term: "DYOR", definition: "Do Your Own Research — an expression meaning everyone needs to do their own research, as investing in crypto is very volatile. What works for one person doesn't necessarily work for another." },
      { term: "Flood", definition: "Sending many messages about the same thing, becoming visual pollution in chats and servers." },
      { term: "FOMO", definition: "Fear Of Missing Out — fear of missing an opportunity. Very common in volatile markets, it can lead to impulsive decisions." },
      { term: "WAGMI", definition: "We Are All Gonna Make It — an optimistic expression used in NFT communities, meaning we're all going to succeed." },
      { term: "Genesis", definition: "The first NFT someone launches on a network/platform. Term inspired by the genesis block, which is the first block mined on a blockchain." },
      { term: "Hash", definition: "A unique sequence of characters generated from transaction data using a special mathematical function. In blockchains, hashes verify data integrity and securely connect blocks." },
      { term: "Node", definition: "A computer that is part of a Blockchain network's structure. Each node has an identical copy of all transactions that have occurred on the network." },
      { term: "Nonce", definition: "Short for number used once — a randomly generated number used only once in a cryptographic transaction." },
      { term: "Burn NFT", definition: "The process of making an NFT unusable. It's not possible to delete an NFT from the blockchain, so this action is used when there's a need to remove an NFT from circulation." },
      { term: "Scam", definition: "A fraud or swindle. Very common in the crypto space — always be skeptical of proposals that seem too good to be true." },
      { term: "Phishing", definition: "A type of virtual scam that steals personal and financial information, usually through fake websites or messages that imitate legitimate services." },
      { term: "NFA", definition: "No Financial Advice — an expression used when someone talks about a project/coin, indicating that each person should make their own financial assessment." },
      { term: "IRL", definition: "In Real Life — used to refer to life that happens outside the internet." },
      { term: "Block Explorer", definition: "A platform where a blockchain can be accessed publicly in real time. Each network has one or more block explorers." },
      { term: "Whitepaper", definition: "A document that explains the goals and technologies of a crypto project. It is a crucial requirement for projects to be considered genuine and professional." },
      { term: "Minting", definition: "The process of creating and registering an NFT on a blockchain — making it an official and verifiable digital asset." },
      { term: "GM / GN", definition: "Good Morning / Good Night — common greetings in NFT and crypto communities to create daily connection." },
    ],
  },
  {
    id: "internet-generations",
    slug: "internet-generations",
    title: "Internet Generations",
    subtitle: "Web1, Web2, Web3",
    tags: ["web3", "history", "technology"],
    description: "From static pages to semantic and decentralized networks.",
    related: ["blockchain", "introduction"],
    content: internetGen,
  },
  {
    id: "blockchain",
    slug: "blockchain",
    title: "Blockchain Technology",
    subtitle: "How it works",
    tags: ["blockchain", "technology", "history"],
    description: "Decentralized digital ledgers, consensus mechanisms, block structure, and applications.",
    related: ["consensus", "crypto-wallets", "nfts", "internet-generations"],
    content: blockchain,
  },
  {
    id: "consensus-mechanisms",
    slug: "consensus-mechanisms",
    title: "Consensus Mechanisms",
    subtitle: "Mining and Validation",
    tags: ["blockchain", "technology", "consensus"],
    description: "How decentralized networks agree on transactions: PoW, PoS, PoA, and PoH.",
    related: ["blockchain", "cryptography", "crypto-wallets"],
    content: miningValidation,
  },
  {
    id: "cryptography",
    slug: "cryptography",
    title: "Cryptography",
    subtitle: "The foundation of blockchain",
    tags: ["blockchain", "technology", "cryptography"],
    description: "How cryptography makes blockchain possible — and why crypto is called crypto.",
    related: ["blockchain", "consensus-mechanisms"],
    content: cryptography,
  },
  {
    id: "crypto-wallets",
    slug: "crypto-wallets",
    title: "Crypto Wallets",
    subtitle: "Wallets, private keys and security",
    tags: ["crypto-wallets", "wallets", "scam"],
    description: "How cryptocurrency wallets work, what are private keys, and how to protect yourself from scams.",
    related: ["blockchain", "nfts"],
    content: security,
  },
  {
    id: "nfts",
    slug: "nfts",
    title: "NFTs",
    subtitle: "Non-fungible tokens",
    tags: ["nft", "art", "blockchain"],
    description: "What NFTs are, how they work, metadata, dynamic NFTs, and how to create one.",
    related: ["blockchain", "platforms", "communities"],
    content: nfts,
  },
  {
    id: "communities",
    slug: "communities",
    title: "NFT Communities",
    subtitle: "Building connections",
    tags: ["community", "nft", "culture"],
    description: "Types of communities, how to participate, social initiatives, and critical perspective.",
    related: ["platforms", "communication", "marketing"],
    content: communities,
  },
  {
    id: "platforms",
    slug: "platforms",
    title: "Platforms",
    subtitle: "NFT Marketplaces",
    tags: ["nft", "platforms", "tools"],
    description: "An overview of NFT platforms across different blockchains.",
    related: ["nfts", "communication", "blockchain"],
    content: platforms,
  },
  {
    id: "communication",
    slug: "communication",
    title: "Communication Platforms",
    subtitle: "Where communities live",
    tags: ["community", "social", "tools"],
    description: "The social networks and communication tools that NFT communities use.",
    related: ["communities", "marketing"],
    content: communication,
  },
  {
    id: "marketing",
    slug: "marketing",
    title: "Marketing",
    subtitle: "Promoting your work",
    tags: ["marketing", "community", "strategy"],
    description: "Strategies for promoting your NFT work ethically and effectively.",
    related: ["communities", "communication", "platforms"],
    content: marketing,
  },
  {
    id: "about",
    slug: "about",
    title: "About the Project",
    subtitle: "Research and history",
    tags: ["research", "ufpe", "about"],
    description: "The origin of the project, the research behind it, and the people who built it.",
    related: ["introduction", "references"],
    hideFromHome: true,
    content: about,
  },
  {
    id: "references",
    slug: "references",
    title: "References & Further Reading",
    subtitle: "Bibliography",
    tags: ["research", "bibliography"],
    description: "Academic and online references used in this wiki.",
    related: ["introduction"],
    content: references,
  },
];

export const allTags = [...new Set(wikiSections.flatMap(s => s.tags))];
export const getSectionBySlug = (slug) => wikiSections.find(s => s.slug === slug);
export const getRelatedSections = (slugs) => slugs.map(slug => wikiSections.find(s => s.slug === slug)).filter(Boolean);