// Wiki content in English

const intro = [
  "# Introduction",
  "",
  "To start talking about NFTs, we first need to think about some key terms that are part of this universe. This curriculum covers the techniques and practices for creating artworks in the NFT market.",
  "",
  "This project's main goal is to encourage more people to learn how to use Blockchain technology — and to foster a serious conversation about how virtual communities should be more conscious and thereby contribute socially to physical space.",
  "",
  "---",
  "",
  "We'll talk about **Blockchain**, **crypto**, **digital communities**, and other basic concepts so you have the autonomy and initial encouragement to create your own NFT works and projects.",
  "",
  "> Computers advance / Artists hitch a ride / Scientists create the new / Artists take the fame — Fred Zero Quatro",
  "",
  "## Why this matters",
  "",
  "This is not just a technical manual. It's an invitation to think critically about technology, art, and community. The NFT space is still fertile ground — largely unexplored. It's up to us to navigate it consciously: planting good ideas, without clearing the forest.",
  "",
  "## Who made this?",
  "",
  "This educational material was developed by **Numa** as an integral part of master's research in Digital Artifact Design at the Federal University of Pernambuco (UFPE), funded by CNPq's MAI/DAI program.",
  "",
  "The content is available for **free distribution**.",
].join("\n");

const internetGen = [
  "# Internet Generations",
  "",
  "First of all, it's important to learn about the three existing generations of the internet. We live in a moment where Web 2 and Web3 exist simultaneously — each generation is not a separate thing, but just a continuation of the web we already know.",
  "",
  "---",
  "",
  "## Web 1.0 — The Simple Internet",
  "",
  "The first phase of the Internet emerged in the **1990s** and consisted of pages with hyperlinks. Sites were primarily informational with very basic layouts and most content text-based. Users could only access, read, and navigate between pages.",
  "",
  "Characteristics: limited bandwidth, limited devices (desktop only), no real interaction.",
  "",
  "## Web 2.0 — The Social Internet",
  "",
  "Emerged around **2004** — a phase that brought more user-generated content and visual features. Users could share more information with each other and connect more easily. Marked by greater interactivity and collaboration, but with **centralized platforms** (Google, Facebook, Instagram) holding user data.",
  "",
  "## Web3 — The Semantic Internet",
  "",
  "Starting from **2008**, when Blockchain technology came into play through Bitcoin. The principles of Web3 intend to allow users to own their own data, instead of companies.",
  "",
  "Also known as the **Semantic Web**, as it aims to make information understandable to computers — through machine learning.",
  "",
  "> Despite this, many discourses around Blockchain are tied to neoliberal ideas. Even with the ideal of decentralization, Blockchains in practice concentrate power in the hands of a few developers and miners. — MENOTTI, 2021",
].join("\n");

const blockchain = [
  "# Blockchain Technology",
  "",
  "## What is Blockchain?",
  "",
  "Blockchains are like **decentralized digital ledgers**. Online networks where data is saved on each user's computer, not just on a single server.",
  "",
  "A useful analogy: the blockchain is like a large **shared spreadsheet** replicated across thousands of computers. This spreadsheet is constantly updated and each node verifies each new entry.",
  "",
  "---",
  "",
  "## History",
  "",
  "Blockchain technology had its origins in **1991**, when Stuart Haber and W. Scott Stornetta published a paper on how to securely timestamp digital documents using a cryptographically chained series of blocks.",
  "",
  "| Year | Event |",
  "|------|-------|",
  "| **1979** | Ralph Merkle creates and patents the concept of the Merkle Tree. |",
  "| **1982** | David Chaum at Berkeley describes the foundations of blockchain technology, except for proof of work. |",
  "| **1991** | Stuart Haber and Scott Stornetta publish *How to Time-Stamp a Digital Document* — the first concept of Blockchain, using a Merkle Tree. |",
  "| **1992** | The Merkle Tree is introduced into cryptography and computer science. Creation of the **cypherpunk** mailing list, a group that advocates for privacy and individual freedom in the digital age using cryptography as a tool for social change. |",
  "| **2002** | David Mazières and Dennis Shasha propose how to store data using blocks with the SUNDR structure. |",
  "| **2005** | Nick Szabo proposes a cryptocurrency called *Bitgold*. |",
  "| **2008** | Satoshi Nakamoto publishes *Bitcoin: A Peer-to-Peer Electronic Cash System*. |",
  "| **2009** | The first Bitcoin is mined and users begin using it. |",
  "| **2010** | **Bitcoin Pizza Day** — on May 22nd, Laszlo Hanyecz trades 10,000 BTC for 2 pizzas in the US. The first recorded real-world purchase paid with cryptocurrency, celebrated annually. |",
  "| **2013** | The Bitcoin market surpasses $1 million. Vitalik Buterin launches the Ethereum whitepaper. |",
  "| **2014** | **R3** is founded, a consortium of banks to bring blockchain to the corporate world. Ethereum holds a crowdsale: 60 million ETH sold for ~$18 million. |",
  "| **2015** | The Ethereum network officially launches with its first block mined. The Linux Foundation launches **Hyperledger**. |",
  "| **2016** | R3 launches **Corda**, the first blockchain platform for enterprises. The Ethereum DAO is hacked due to a code vulnerability. |",
  "| **2017** | Dan Larimer launches **EOS**, a smart contract platform with no transaction fees. |",
  "| **2018** | Forbes highlights 9 blockchain companies among the top 50 fintechs of the year. |",
  "| **2021** | NFT boom with digital artworks selling for record values. Launch of **hic et nunc**, a platform created by Brazilian developer Rafael and a small team in Brasília. |",
  "",
  "---",
  "",
  "## How does a Blockchain work?",
  "",
  "Imagine you want to send money to someone without going through a bank. On the blockchain, this happens in four steps — no intermediaries, no central server, no possibility of fraud.",
  "",
  "![How Blockchain works — diagram with 4 steps](/images/how-blockchain-works.svg)",
  "",
  "**① You request a transaction**",
  "Your request is encoded in a block containing: who sends, who receives, and the value. Think of it as a sealed envelope with all the necessary information.",
  "",
  "**② The entire network finds out**",
  "That block is broadcast to thousands of computers around the world — the network's *nodes*. Each one independently verifies whether the transaction is valid.",
  "",
  "**③ The nodes reach consensus**",
  "The network needs to agree on which block will be added. This process — called *consensus* — can happen through mining (PoW) or validation (PoS). Learn more at [Mining and Validation](mining-and-validation).",
  "",
  "**④ The transaction is recorded forever**",
  "The approved block is added to the chain permanently and immutably. No one can erase, alter, or reverse it — not even the creator of the transaction.",
  "",
  "---",
  "",
  "## Consensus Mechanisms",
  "",
  "For all computers on the network to agree on which transactions are valid, the blockchain uses **consensus mechanisms** — protocols that ensure security and integrity without a central authority.",
  "",
  "The main mechanisms are Proof of Work (PoW), Proof of Stake (PoS), Proof of Authority (PoA), and Proof of History (PoH) — each with different ways of mining and validating blocks.",
  "",
  "> See the full article: [Mining and Validation](mining-and-validation)",
  "",
  "---",
  "",
  "## Blockchain Properties",
  "",
  "**Decentralization:** No central authority — control is distributed among all network participants.",
  "",
  "**Transparency:** All transactions are public and traceable via block explorers.",
  "",
  "**Immutability:** Once recorded, data cannot be altered.",
  "",
  "**Anonymity:** Users have public addresses (not personal identity).",
  "",
  "---",
  "",
  "## Blockchain Layers",
  "",
  "| Layer | Function | Examples |",
  "|-------|----------|---------|",
  "| L0 | Infrastructure, interoperability | Polkadot, Cosmos |",
  "| L1 | Main blockchains, consensus | Bitcoin, Ethereum, Solana |",
  "| L2 | Scalability, fee reduction | Optimism, Polygon, Arbitrum |",
  "| L3 | Cross-chain application layer | IBC Protocol, Quant |",
].join("\n");

const miningValidation = [
  "# Consensus Mechanisms, Mining and Validation",
  "",
  "Consensus mechanisms are protocols that allow a decentralized network of computers to agree on the state of the blockchain — that is, which transactions are valid and in what order they should be added.",
  "",
  "These mechanisms are crucial for ensuring the security, integrity, and reliability of the blockchain, preventing fraud and ensuring that all network participants have an identical and up-to-date copy of the ledger.",
  "",
  "---",
  "",
  "## Proof of Work (PoW)",
  "",
  "**Mining:** Miners compete to solve a complex mathematical problem (cryptographic hash). The first miner to find the solution *proves* their work, adds the block to the blockchain, and is rewarded with cryptocurrency.",
  "",
  "**Validation:** If the majority of other nodes agree with the miner's work, the block is added to the blockchain.",
  "",
  "**Examples:** Bitcoin (BTC) · Litecoin (LTC) · Monero (XMR)",
  "",
  "---",
  "",
  "## Proof of Stake (PoS)",
  "",
  "**Mining:** No mining. Validators are chosen to propose and validate blocks based on the amount of cryptocurrency they hold and are willing to *stake*. The larger the stake, the higher the chance of being selected.",
  "",
  "**Validation:** Other validators verify the validity of the block. If the majority agrees, the block is added to the blockchain.",
  "",
  "**Examples:** Ethereum (ETH) · Cardano (ADA) · Tezos (XTZ) · Avalanche (AVAX) · Algorand (ALGO)",
  "",
  "---",
  "",
  "## Proof of Authority (PoA)",
  "",
  "**Mining:** No mining. Validators are pre-selected and authorized to create and validate blocks.",
  "",
  "**Validation:** Authorized validators verify transactions and add them to the blockchain.",
  "",
  "**Examples:** Binance Coin (BNB) · VeChain (VET) · XRP",
  "",
  "---",
  "",
  "## Proof of History (PoH)",
  "",
  "**Mining:** No mining. The system uses an immutable record of past events (hashgraph) to determine the order of transactions and the validity of blocks.",
  "",
  "**Validation:** Validation is performed by a group of nodes that verify the order of transactions and the integrity of the hashgraph.",
  "",
  "**Examples:** Hedera Hashgraph (HBAR)",
  "",
  "---",
  "",
  "## The special case of Solana",
  "",
  "Solana combines two mechanisms: **PoH + PoS**. PoH acts as an internal clock — each event on the network receives a cryptographic timestamp, creating a verifiable order of transactions before validation even begins. This historical record allows validators (selected by PoS) to work in parallel, without waiting for each other to confirm block order.",
  "",
  "The result is a much faster network: while Ethereum processes ~15 transactions per second, Solana can reach tens of thousands.",
  "",
  "---",
  "",
  "## Comparison",
  "",
  "| Mechanism | Mining | Validation | Examples |",
  "|-----------|--------|------------|---------|",
  "| **PoW** | Competition via cryptographic hash | Majority of nodes agree | Bitcoin, Litecoin, Monero |",
  "| **PoS** | No mining — selection by stake | Majority of validators agree | Ethereum, Cardano, Tezos |",
  "| **PoA** | No mining — pre-authorized validators | Authorized validators | Binance Coin, VeChain, XRP |",
  "| **PoH** | No mining — historical record (hashgraph) | Nodes verify order and integrity | Hedera Hashgraph |",
  "| **PoH + PoS** | No mining — cryptographic clock + stake | Validators in parallel | Solana |",
  "",
  "> Back to: [Blockchain Technology](blockchain)",
].join("\n");

const cryptography = [
  "# Cryptography",
  "",
  "**Cryptography** is the transformation of readable data into encoded data — which can only be deciphered with the right key. It is the technology that makes blockchain possible: without it, there would be no way to guarantee that transactions are authentic, that data hasn't been tampered with, or that a digital coin hasn't been spent twice.",
  "",
  "---",
  "",
  "## Why crypto is called crypto",
  "",
  "The prefix *crypto* comes from the Greek *kryptós* — hidden, secret. **Cryptocurrency** literally means currency protected by cryptography. It's not just a name — it's a description of what it is: a currency whose security and authenticity depend entirely on cryptographic functions.",
  "",
  "---",
  "",
  "## The Merkle Tree",
  "",
  "One of the most important structures for the blockchain is the **Merkle Tree**, created by Ralph Merkle in 1979.",
  "",
  "Here's how it works: each transaction generates a unique code called a *hash*. These hashes are grouped in pairs and combined into new hashes — and so on, until a single hash remains at the top, called the **Merkle Root**.",
  "",
  "This process creates a fingerprint of the entire block. If any transaction is altered — even slightly — the Merkle Root changes completely. This makes tampering immediately detectable by any node on the network.",
  "",
  "This is why the blockchain is **immutable**: not because it's physically impossible to alter data, but because any change breaks the chain of hashes and is rejected by the network.",
  "",
  "> See the full timeline of how this led to the creation of Bitcoin in [Blockchain Technology](blockchain).",
  "",
  "---",
  "",
  "## How cryptography protects the blockchain",
  "",
  "**Authenticity:** Each transaction is signed with the sender's private key. Only the key holder can authorize a transfer — but anyone can verify the signature is legitimate using the public key.",
  "",
  "**Integrity:** The hash of each block includes the hash of the previous block. Altering any old block invalidates all subsequent blocks — making fraud computationally unfeasible.",
  "",
  "**Decentralization:** Because verification is mathematical, there's no need for a central authority. Any node can confirm a transaction is valid using only cryptographic rules.",
].join("\n");

const security = [
  "# Security",
  "",
  "## Cryptocurrency Wallets",
  "",
  "A **wallet** is like a bank account for your digital currencies. Made to store crypto obtained through purchase, transfer, or mining/validation. It is the main way to interact with Web3 sites and applications.",
  "",
  "---",
  "",
  "## Security Keys",
  "",
  "**Public Keys:** Like bank account numbers — a sequence of numbers and letters randomly generated when creating a wallet. It's the information needed to transfer or receive digital assets. Safe to share.",
  "",
  "**Private Keys / Seed Phrase:** Must be kept secret and in a safe physical location. The seed phrase is the most important part of security — with it you can recover the same account on different devices.",
  "",
  "> Warning: These keys should never be kept in digital files or emails. Once you lose your seed phrase, it is impossible to recover your wallet. There is no recovery system.",
  "",
  "---",
  "",
  "## Types of Wallets",
  "",
  "**Digital Wallet (Hot Wallet):** Software used on desktop and mobile, connected to the internet. Suitable for casual interactions and operations. Examples: Phantom (Solana), MetaMask (Ethereum), Temple (Tezos).",
  "",
  "**Hardware Wallet (Cold Wallet):** Physical device not connected to the internet. Recommended for long-term storage. Brands: Ledger, Trezor, Ngrave.",
  "",
  "---",
  "",
  "## Common Scams",
  "",
  "**Fake Instagram Profiles:** Pretend to be collectors and offer high prices for your work, then ask for a fee to finalize the sale — which never happens.",
  "",
  "**Fake Job Proposals:** Offer commissions or game tests with files infected with malware that scan the computer to invade wallets.",
  "",
  "**Fraudulent Sites:** Clones of popular projects. When you connect your wallet, they drain all funds.",
  "",
  "---",
  "",
  "## Security Measures",
  "",
  "- Don't click on unknown links",
  "- Don't open attachments from unknown profiles",
  "- Don't connect your wallet to just any site",
  "- Be skeptical of exorbitant proposals",
  "- Never share your keys",
  "- Store in a safe physical location",
  "- Use anti-phishing extensions (Pocket Universe, Wallet Guard)",
].join("\n");

const nfts = [
  "# NFTs",
  "",
  "## What are NFTs?",
  "",
  "We can understand an **NFT** as the **digital certificate of ownership of an item**. This certificate is created and registered on a Blockchain network and can contain files, links, text, or code.",
  "",
  "NFT stands for **Non-Fungible Token**. Fungible = replaceable (money, cars). Non-fungible = unique, irreplaceable (artworks, real estate).",
  "",
  "---",
  "",
  "## Metadata",
  "",
  "NFT metadata is like labels with the properties of a digital asset: file description, name, categories, transaction history, date and time.",
  "",
  "**On-chain:** The information is stored directly on the Blockchain network, integrated into the NFT itself.",
  "",
  "**Off-chain:** The information is stored on servers or cloud storage systems (IPFS). Most metadata is stored off-chain as a JSON file.",
  "",
  "---",
  "",
  "## Dynamic NFTs (dNFTs)",
  "",
  "NFTs whose characteristics can change — also known as semi-fungible or living NFTs. Widely used in DeFi games (evolving badges) and in art (pieces that change according to rules defined by the artist).",
  "",
  "Example: Basketball player LaMelo Ball's NFTs incorporate sports data on the network and change depending on game results.",
  "",
  "---",
  "",
  "## How to make an NFT",
  "",
  "**Step 1:** Choose the Blockchain (Ethereum, Solana, Tezos...)",
  "",
  "**Step 2:** Choose the Platform (see Platforms section)",
  "",
  "**Step 3:** Generate a file (your art, music, video, code...)",
  "",
  "**Step 4:** Mint the file on the Platform",
  "",
  "**Step 5:** List the NFT (price, edition, conditions)",
  "",
  "**Step 6:** Promotion — build visibility through your community",
].join("\n");

const communities = [
  "# NFT Communities",
  "",
  "An **NFT community** is a digital group of people interested in NFTs, who gather to discuss, create, buy, sell, and trade these tokens. Communities are crucial — it's impossible to thrive without community in this environment.",
  "",
  "---",
  "",
  "## Types of NFT Communities",
  "",
  "**Project communities:** Centered around a specific NFT project, such as a digital art collection.",
  "",
  "**Collector communities:** Bring together people interested in collecting NFTs, regardless of the project.",
  "",
  "**Artist communities:** Focused on digital artists who create NFTs.",
  "",
  "**Investor communities:** Made up of people who invest in NFTs for profit.",
  "",
  "---",
  "",
  "## How to participate",
  "",
  "Use common social platforms: Discord, Twitter/X, and Warpcast. Be consistent and patient — building a loyal community takes time and effort. Be authentic and transparent about your goals.",
  "",
  "---",
  "",
  "## Tips for beginners",
  "",
  "1. Don't trust easy money — don't expect to be a millionaire in 2 weeks.",
  "2. Use NFTs as a tool to showcase your work.",
  "3. Don't believe in posts like 'drop your NFT here' (engagement farming).",
  "4. Never create the same art on different Blockchains.",
  "5. Don't flood chats with too many messages.",
  "",
  "---",
  "",
  "## Social Initiatives",
  "",
  "The **Balot NFT** initiative, led by the Congolese Plantation Workers Art League (CATPC), used NFT technology to reclaim cultural heritage and buy back lands stolen by plantations in the Congo. Each Balot NFT represents one hectare of land, and the funds are used to replant forests.",
  "",
  "---",
  "",
  "## Critical Perspective",
  "",
  "> The virtual environment is just an extension of our physical world — it obviously reflects and reproduces the social problems that exist in real life. The NFT landscape is not free of politics. All technology is a tool. The outcome of its use depends on who is using it.",
].join("\n");

const platforms = [
  "# NFT Platforms",
  "",
  "Below is an overview of platforms available on different blockchains. Explore **DappRadar** to discover platforms on many other networks.",
  "",
  "---",
  "",
  "## Ethereum and its L2s",
  "",
  "**Zora** — creator-focused, free minting",
  "**Super Rare** — curated 1/1 artwork marketplace",
  "**Foundation** — invite-curated platform",
  "**Manifold** — tools for custom smart contracts",
  "**Rarible** — multi-chain, focus on creator royalties",
  "",
  "## Solana",
  "",
  "**3.land** — community and exhibitions",
  "**Exchange Art** — curated digital art",
  "**Magic Eden** — largest Solana marketplace",
  "**Tensor** — trading and analytics",
  "",
  "## Tezos",
  "",
  "**Objkt** — largest Tezos marketplace",
  "**(fx)hash** — generative art",
  "**teia** — community-owned, artist-centered",
  "",
  "## Bitcoin Ordinals",
  "",
  "**Gamma** · **Magic Eden** · **Ordzaa**",
  "",
  "---",
  "",
  "## How to choose a platform?",
  "",
  "**Fees:** Tezos and Solana have very low fees; Ethereum is higher.",
  "",
  "**Community:** Different platforms attract different collector communities.",
  "",
  "**Curation:** Open (Objkt, Magic Eden) vs. curated (Super Rare, Foundation).",
  "",
  "**Mission:** teia is community-owned; other platforms are commercial.",
  "",
  "> Remember: platforms can change and even shut down — but NFTs remain on the blockchain. Always be prepared to adapt.",
].join("\n");

const communication = [
  "# Communication Platforms",
  "",
  "NFT communities are built on essential social networks. These spaces are necessary to connect artists and collectors.",
  "",
  "---",
  "",
  "## X (formerly Twitter)",
  "",
  "One of the most used platforms for promoting NFTs. Many artists, traders, and people in the crypto space have dedicated profiles on this topic. Despite recent changes, it's still an important network for the NFT world.",
  "",
  "---",
  "",
  "## Discord",
  "",
  "Another essential place for NFT communities. Artists, investors, and collectors can connect, organize, and chat. Many NFT platforms, artists, and projects have their own Discord servers.",
  "",
  "---",
  "",
  "## Warpcast / Farcaster",
  "",
  "An app made by the Farcaster project team — a **decentralized social network**. Focused on crypto users. Annual fee to use the platform.",
  "",
  "---",
  "",
  "## Nostr",
  "",
  "A simple, open protocol that enables global, decentralized, and censorship-resistant social media. Several networks use this protocol.",
  "",
  "---",
  "",
  "## Choosing your platforms",
  "",
  "You don't need to be everywhere. Start with 1-2 platforms and build genuine connections before expanding. **Consistency and authenticity matter more than volume.**",
].join("\n");

const marketing = [
  "# Marketing",
  "",
  "## 1. Build a Strong Identity",
  "",
  "Develop a visual identity and maintain a consistent voice that represents your personality.",
  "",
  "---",
  "",
  "## 2. Be Active on Social Media",
  "",
  "Engage with your audience, share your work, and participate in conversations related to your field.",
  "",
  "---",
  "",
  "## 3. Organization is Key",
  "",
  "Use post scheduling tools, maintain a release calendar, and always stay on top of deadlines and opportunities.",
  "",
  "---",
  "",
  "## 4. Build Meaningful Connections",
  "",
  "Comment genuinely on other people's work. Participate in collaborative projects. Show up consistently in communities you care about. Offer help before asking for it.",
  "",
  "---",
  "",
  "## 5. Release Frequency",
  "",
  "Find a sustainable rhythm for yourself. Burnout doesn't help anyone.",
  "",
  "---",
  "",
  "## 6. Pricing Strategies",
  "",
  "**Don't undervalue yourself!** Consider scarcity, demand, currency value, and your time and craft.",
  "",
  "---",
  "",
  "## 7. Stay Creative and Connected",
  "",
  "Even during slower sales periods, keep creating and staying connected with your audience.",
  "",
  "---",
  "",
  "## 8. Be Prepared for Change",
  "",
  "Platforms can change and even close — which doesn't make NFTs disappear, as they're on the blockchain. It's crucial to always be experimenting with new possibilities.",
  "",
  "> Good marketing in the NFT space is about being genuinely present, sharing authentically, building relationships before transactions, and maintaining consistency over time.",
].join("\n");

const about = [
  "# About the Project",
  "",
  "**Computadores Fazem Arte** is an educational wiki about Blockchain, Web3, and NFTs — developed as an integral part of master's research in **Digital Artifact Design** at the Federal University of Pernambuco (UFPE), funded by CNPq's MAI/DAI program.",
  "",
  "---",
  "",
  "## The Name",
  "",
  "The project's name comes from a verse by **Fred Zero Quatro**, vocalist of the legendary Recife band Mundo Livre S/A, from the song *Computadores Fazem Arte*.",
  "",
  "> Computers advance / Artists hitch a ride / Scientists create the new / Artists take the fame — Fred Zero Quatro",
  "",
  "The song is both an observation and a provocation — and gave its name to a project that tries to think critically about what it means for artists to inhabit technological spaces.",
  "",
  "Watch the song: https://www.youtube.com/watch?v=KZg_m0z4NLI",
  "",
  "---",
  "",
  "## Undergraduate Research",
  "",
  "As part of the research, three undergraduate students were supervised in different fields of knowledge — a deliberate interdisciplinary choice that reflects the project's own values.",
  "",
  "### Milena — Pedagogy",
  "Brought an educational perspective to the project, helping think about how complex technological concepts can be made accessible to diverse audiences.",
  "",
  "### Vitória — Design",
  "Contributed a visual and communicational perspective, essential for shaping how the wiki and its materials are presented.",
  "",
  "### Artur — Computer Science · in memoriam",
  "Artur joined the research as a volunteer — driven entirely by his own curiosity and enthusiasm. He was one of the most engaged and active participants in the project, bringing technical rigor and genuine excitement to every meeting. His presence left a mark on this research that cannot be measured. This project carries a piece of him.",
  "",
  "---",
  "",
  "## In-Person Course — CTG/UFPE, 2024",
  "",
  "In 2024, a four-week in-person course was held at the Center for Technology and Geosciences (CTG) at UFPE — bringing together students from different fields to learn about Blockchain, NFTs, and digital art communities.",
  "",
  "The course closing was interrupted by the **Twitter/X ban in Brazil** — a moment that became part of the project's own history and a live case study: a reminder that the same platforms that host digital art communities are subject to political decisions, regulatory pressures, and corporate power.",
  "",
  "The regulation of social media platforms is not a secondary topic — it is central to any honest conversation about digital rights, freedom of expression, and the conditions under which artists create and distribute their work. Platforms must be held accountable for guaranteeing users' fundamental rights.",
  "",
  "---",
  "",
  "## Publication — WebMedia 2024",
  "",
  "The material developed in this research was published and presented at **WebMedia 2024**, held at the Federal University of Juiz de Fora (UFJF).",
  "",
  "[Access the publication](https://books-sol.sbc.org.br/index.php/sbc/catalog/view/177/779/1513)",
  "",
  "---",
  "",
  "## Course — Design for Web3, UFPE 2025",
  "",
  "In 2025, the research led to an invitation from **Professor Leonardo Castillo** to teach the course *Design for Web3* in UFPE's Design program.",
  "",
  "---",
  "",
  "## Contact",
  "",
  "**Numa** · [@numadessas](https://twitter.com/numadessas) · [contato@numadessas.com.br](mailto:contato@numadessas.com.br) · [numadessas.com.br](https://numadessas.com.br)",
].join("\n");

const references = [
  "# References",
  "",
  "## Academic Works",
  "",
  "**MENOTTI, Gabriel.** Criptoarte: A Metafísica do NFT e a Tecnocolonização da Autenticidade. 2021, Revista do Centro de Pesquisa e Formação / No 13.",
  "",
  "**ASSANGE, Julian et al.** Cypherpunks: Freedom and the Future of the Internet. New York: OR Books, 2012.",
  "",
  "**PANDA, Sandeep Kumar et al.** Bitcoin and Blockchain: History and Current Applications. 2020, CRC Press.",
  "",
  "**AL-SAQAF, Walid; SEIDLER, Nicolas.** Blockchain technology for social impact. 2017, Journal of Cyber Policy.",
  "",
  "**KENT, Charlotte.** Blockchain manifestos: fighting for the imagination of a culture. 2021, Burlington Contemporary Journal.",
  "",
  "**LIMA, Júnior César de; CARVALHO, Cedric L. de.** Uma Visão da Web Semântica. 2004, UFG.",
  "",
  "---",
  "",
  "## Online Resources",
  "",
  "- [CoinMarketCap Glossary](https://coinmarketcap.com/academy/en/glossary)",
  "- [Web3 Foundation](https://web3.foundation/)",
  "- [Chainlink — What is a Dynamic NFT?](https://chain.link/education-hub/what-is-dynamic-nft)",
  "- [DappRadar](https://dappradar.com/)",
  "",
  "---",
  "",
  "## About this Project",
  "",
  "This wiki was developed by **Numa** as an integral part of master's research in Digital Artifact Design at UFPE, funded by CNPq's MAI/DAI program.",
  "",
  "Contact: [contato@numadessas.com.br](mailto:contato@numadessas.com.br)",
  "",
  "*Content available for free distribution.*",
].join("\n");

export const wikiSections = [
  {
    id: "introduction",
    slug: "introduction",
    title: "Introduction",
    subtitle: "About this wiki",
    tags: ["overview", "web3", "nft"],
    description: "What is Computadores Fazem Arte and why this knowledge matters.",
    related: ["glossary", "internet-generations"],
    content: intro,
  },
  {
    id: "glossary",
    slug: "glossary",
    title: "Glossary",
    subtitle: "Essential terms",
    tags: ["reference", "terminology"],
    description: "Essential vocabulary for navigating the Web3 and NFT space.",
    related: ["introduction", "blockchain"],
    isGlossary: true,
    content: "Essential vocabulary for navigating the Web3 and NFT space. Click on any term to expand its definition.",
    glossaryTerms: [
      { term: "DYOR", definition: "Do Your Own Research — an expression meaning everyone needs to do their own research, as investing in crypto is very volatile. What works for one person doesn't necessarily work for another." },
      { term: "Flood", definition: "Sending many messages about the same thing, becoming visual pollution in chats and servers." },
      { term: "FOMO", definition: "Fear Of Missing Out — fear of missing an opportunity. Very common in volatile markets, it can lead to impulsive decisions." },
      { term: "WAGMI", definition: "We Are All Gonna Make It — an optimistic expression used in NFT communities, meaning we're all going to succeed." },
      { term: "Genesis", definition: "The first NFT someone launches on a network/platform. Term inspired by the genesis block, which is the first block mined on a blockchain." },
      { term: "Hash", definition: "A unique sequence of characters generated from transaction data using a special mathematical function. In blockchains, hashes verify data integrity and securely connect blocks." },
      { term: "Node", definition: "A computer that is part of a Blockchain network's structure. Each node has an identical copy of all transactions that have occurred on the network." },
      { term: "Nonce", definition: "Short for number used once — a randomly generated number used only once in a cryptographic transaction." },
      { term: "Burn NFT", definition: "The process of making an NFT unusable. It's not possible to delete an NFT from the blockchain, so this action is used when there's a need to remove an NFT from circulation." },
      { term: "Scam", definition: "A fraud or swindle. Very common in the crypto space — always be skeptical of proposals that seem too good to be true." },
      { term: "Phishing", definition: "A type of virtual scam that steals personal and financial information, usually through fake websites or messages that imitate legitimate services." },
      { term: "NFA", definition: "No Financial Advice — an expression used when someone talks about a project/coin, indicating that each person should make their own financial assessment." },
      { term: "IRL", definition: "In Real Life — used to refer to life that happens outside the internet." },
      { term: "Block Explorer", definition: "A platform where a blockchain can be accessed publicly in real time. Each network has one or more block explorers." },
      { term: "Whitepaper", definition: "A document that explains the goals and technologies of a crypto project. It is a crucial requirement for projects to be considered genuine and professional." },
      { term: "Minting", definition: "The process of creating and registering an NFT on a blockchain — making it an official and verifiable digital asset." },
      { term: "GM / GN", definition: "Good Morning / Good Night — common greetings in NFT and crypto communities to create daily connection." },
    ],
  },
  {
    id: "internet-generations",
    slug: "internet-generations",
    title: "Internet Generations",
    subtitle: "Web1, Web2, Web3",
    tags: ["web3", "history", "technology"],
    description: "From static pages to semantic and decentralized networks.",
    related: ["blockchain", "introduction"],
    content: internetGen,
  },
  {
    id: "blockchain",
    slug: "blockchain",
    title: "Blockchain Technology",
    subtitle: "How it works",
    tags: ["blockchain", "technology", "history"],
    description: "Decentralized digital ledgers, consensus mechanisms, block structure, and applications.",
    related: ["consensus", "security", "nfts", "internet-generations"],
    content: blockchain,
  },
  {
    id: "consensus",
    slug: "mining-and-validation",
    title: "Consensus Mechanisms",
    subtitle: "Mining and Validation",
    tags: ["blockchain", "technology", "consensus"],
    description: "How decentralized networks agree on transactions: PoW, PoS, PoA, and PoH.",
    related: ["blockchain", "cryptography", "security"],
    content: miningValidation,
  },
  {
    id: "cryptography",
    slug: "cryptography",
    title: "Cryptography",
    subtitle: "The foundation of blockchain",
    tags: ["blockchain", "technology", "cryptography"],
    description: "How cryptography makes blockchain possible — and why crypto is called crypto.",
    related: ["blockchain", "mining-and-validation"],
    content: cryptography,
  },
  {
    id: "security",
    slug: "security",
    title: "Security",
    subtitle: "Wallets and protection",
    tags: ["security", "wallets", "scam"],
    description: "Cryptocurrency wallets, private keys, and how to protect yourself from scams.",
    related: ["blockchain", "nfts"],
    content: security,
  },
  {
    id: "nfts",
    slug: "nfts",
    title: "NFTs",
    subtitle: "Non-fungible tokens",
    tags: ["nft", "art", "blockchain"],
    description: "What NFTs are, how they work, metadata, dynamic NFTs, and how to create one.",
    related: ["blockchain", "platforms", "communities"],
    content: nfts,
  },
  {
    id: "communities",
    slug: "communities",
    title: "NFT Communities",
    subtitle: "Building connections",
    tags: ["community", "nft", "culture"],
    description: "Types of communities, how to participate, social initiatives, and critical perspective.",
    related: ["platforms", "communication", "marketing"],
    content: communities,
  },
  {
    id: "platforms",
    slug: "platforms",
    title: "Platforms",
    subtitle: "NFT Marketplaces",
    tags: ["nft", "platforms", "tools"],
    description: "An overview of NFT platforms across different blockchains.",
    related: ["nfts", "communication", "blockchain"],
    content: platforms,
  },
  {
    id: "communication",
    slug: "communication",
    title: "Communication Platforms",
    subtitle: "Where communities live",
    tags: ["community", "social", "tools"],
    description: "The social networks and communication tools that NFT communities use.",
    related: ["communities", "marketing"],
    content: communication,
  },
  {
    id: "marketing",
    slug: "marketing",
    title: "Marketing",
    subtitle: "Promoting your work",
    tags: ["marketing", "community", "strategy"],
    description: "Strategies for promoting your NFT work ethically and effectively.",
    related: ["communities", "communication", "platforms"],
    content: marketing,
  },
  {
    id: "about",
    slug: "about",
    title: "About the Project",
    subtitle: "Research and history",
    tags: ["research", "ufpe", "about"],
    description: "The origin of the project, the research behind it, and the people who built it.",
    related: ["introduction", "references"],
    content: about,
  },
  {
    id: "references",
    slug: "references",
    title: "References",
    subtitle: "Bibliography",
    tags: ["research", "bibliography"],
    description: "Academic and online references used in this wiki.",
    related: ["introduction"],
    content: references,
  },
];

export const allTags = [...new Set(wikiSections.flatMap(s => s.tags))];
export const getSectionBySlug = (slug) => wikiSections.find(s => s.slug === slug);
export const getRelatedSections = (slugs) => slugs.map(slug => wikiSections.find(s => s.slug === slug)).filter(Boolean);