// Content registry - English
// Uses regular strings to avoid template literal parsing issues

const intro = [
  "# Introduction",
  "",
  "To begin talking about NFTs, we first need to think about some key terms that make up this universe. This formation covers the techniques and practices for creating artworks in the NFT market.",
  "",
  "This project main objective is to encourage more people to learn how to use Blockchain technology — and also to spark a serious conversation about how virtual communities can become more conscious and thereby contribute socially to physical spaces.",
  "",
  "---",
  "",
  "We will cover **Blockchain**, **crypto**, **digital communities**, and other foundational concepts so that you have the autonomy and initial courage to create your NFT works and projects.",
  "",
  '> "Computers advance / Artists hitchhike / Scientists create the new / Artists take the fame" — *Fred Zero Quatro*',
  "",
  "## Why this matters",
  "",
  "This is not just a technical manual. It is an invitation to think critically about technology, art, and community. The NFT space is fertile ground — still largely unexplored. It is up to us to navigate it consciously: planting good ideas without deforestation.",
  "",
  "## Who made this?",
  "",
  "This educational material was developed by **Numa** as part of a masters research in Digital Artifact Design at the Universidade Federal de Pernambuco (UFPE), funded by the MAI/DAI program of the CNPq with support from the NFT art community.",
  "",
  "The content is available for **free distribution**.",
].join("\n");

const internetGen = [
  "# Internet Generations",
  "",
  "Before diving into NFTs, it is important to understand the three generations of the internet. We currently live in a moment where Web2 and Web3 **coexist simultaneously** — these are not separate periods but continuations.",
  "",
  "---",
  "",
  "## Web 1.0 — The Simple Internet",
  "",
  "The first phase emerged in the **1990s**. Sites were primarily informational with basic layouts and text content. Only possible to access and read — *read-only*.",
  "",
  "Characteristics: limited bandwidth, desktop only, no real interaction.",
  "",
  "## Web 2.0 — The Social Internet",
  "",
  "Emerged around **2004**. Brought user-generated content and visual resources. Users could share, comment, and connect. Marked by greater interactivity and the rise of social media platforms — but with **centralized platforms** (Google, Facebook, Instagram) owning user data.",
  "",
  "## Web3 — The Semantic Internet",
  "",
  "Starting from **2008**, when Blockchain technology came into action through Bitcoin. Also called the **Semantic Web** — aiming to make information understandable to computers through machine learning.",
  "",
  '> Warning: Despite ideals of decentralization, many discourses around Blockchain are tied to neoliberal ideas. In practice, blockchains concentrate power in the hands of a few developers and miners. — *MENOTTI, 2021*',
  "",
  "The idea of **trustless** blockchains: instead of trusting people or institutions, trust the technology itself.",
].join("\n");

const blockchain = [
  "# Blockchain Technology",
  "",
  "## What is Blockchain?",
  "",
  "Blockchains are like **digital, decentralized record books**. Data is saved on each user computer in the network — not just on a single server, like Web 2.0 platforms.",
  "",
  "Think of it as a large **shared spreadsheet** replicated across thousands of computers. This spreadsheet is constantly updated and every node verifies each new entry.",
  "",
  "---",
  "",
  "## History",
  "",
  "Blockchain technology had its origins in **1991**, when Stuart Haber and W. Scott Stornetta published an article on securely timestamping digital documents. In 2008, *Satoshi Nakamoto* published the Bitcoin whitepaper, and in 2009 the first block was mined.",
  "",
  "---",
  "",
  "## How Does a Blockchain Work?",
  "",
  "**1. User requests a transaction** — encoded in a block with sender, recipient, and value.",
  "",
  "**2. Transaction broadcast to the network** — all nodes verify validity.",
  "",
  "**3. Consensus process** — nodes agree which block to add (mining/validation).",
  "",
  "**4. Transaction finalized** — immutably added to the chain. Cannot be altered or reversed.",
  "",
  "---",
  "",
  "## Consensus Mechanisms",
  "",
  "| Mechanism | Description | Examples |",
  "|-----------|-------------|---------|",
  "| **Proof of Work (PoW)** | Miners compete to solve complex math problems | Bitcoin, Litecoin |",
  "| **Proof of Stake (PoS)** | Validators chosen by amount of crypto staked | Ethereum, Solana, Cardano |",
  "| **Proof of Authority (PoA)** | Pre-selected validators | Binance Coin, XRP |",
  "",
  "---",
  "",
  "## Blockchain Properties",
  "",
  "**Decentralization:** No central authority — control is distributed among all network participants.",
  "",
  "**Transparency:** All transactions are public and traceable via block explorers.",
  "",
  "**Immutability:** Once recorded, data cannot be altered.",
  "",
  "**Anonymity:** Users have public addresses (not personal identity).",
  "",
  "---",
  "",
  "## Blockchain Layers",
  "",
  "| Layer | Role | Examples |",
  "|-------|------|---------|",
  "| L0 | Software infrastructure, interoperability | Polkadot, Cosmos |",
  "| L1 | Core blockchains, handle consensus | Bitcoin, Ethereum, Solana |",
  "| L2 | Scalability solutions, reduce fees | Optimism, Polygon, Arbitrum |",
  "| L3 | Cross-chain application layer | IBC Protocol, Quant |",
].join("\n");

const security = [
  "# Security",
  "",
  "## Cryptocurrency Wallets",
  "",
  "A **wallet** is like a bank account for your digital currencies — used to store crypto obtained through purchase, transfer, or mining. It is your primary way to interact with Web3 sites and applications.",
  "",
  "---",
  "",
  "## Security Keys",
  "",
  "**Public Keys:** Like bank account numbers — a sequence of numbers and letters generated randomly when creating a wallet. Needed to receive assets. Safe to share.",
  "",
  "**Private Keys / Seed Phrase:** Must be kept completely secret in a safe physical location. The *seed phrase* is the most important security element — with it you can recover your wallet on any device.",
  "",
  "> Warning: These keys must NEVER be stored in digital files, emails, or apps. Once you lose your seed phrase, it is impossible to recover your wallet. There is no recovery system.",
  "",
  "---",
  "",
  "## Types of Wallets",
  "",
  "**Hot Wallet (Digital):** Software on desktop or mobile, connected to the internet. Used for active trading and minting. Examples: Phantom (Solana), MetaMask (Ethereum), Temple (Tezos).",
  "",
  "**Cold Wallet (Hardware):** Physical device not connected to the internet. Recommended for long-term storage. Brands: Ledger, Trezor, Ngrave.",
  "",
  "---",
  "",
  "## Common Scams",
  "",
  "**Fake Collector Profiles:** Pretend to offer high prices for your work, then ask you to pay a fee to complete the sale. There was never a real sale.",
  "",
  "**Fake Work Proposals:** Offer commissions or game tests with malware-infected files that scan your computer to steal wallet credentials.",
  "",
  "**Fraudulent Sites:** Clone popular NFT projects. When you connect your wallet, they drain all funds.",
  "",
  "---",
  "",
  "## Security Measures",
  "",
  "- Do not click unknown links",
  "- Do not open attachments from unknown sources",
  "- Do not connect your wallet to just any site",
  "- Be skeptical of exorbitant proposals",
  "- Never share your seed phrase",
  "- Store keys only in physical, secure locations",
  "- Use anti-phishing browser extensions (Pocket Universe, Wallet Guard)",
].join("\n");

const nfts = [
  "# NFTs",
  "",
  "## What Are NFTs?",
  "",
  "We can understand an NFT as the **digital certificate of ownership of an item**. This certificate is created and recorded on a blockchain network and can contain files, links, text, or code.",
  "",
  "NFT stands for **Non-Fungible Token**. Fungible = replaceable (money, cars). Non-fungible = unique, irreplaceable (artworks, real estate).",
  "",
  "---",
  "",
  "## Metadata",
  "",
  "NFT metadata is like labels with the properties of a digital asset: file description, name, categories, transaction history, date/time.",
  "",
  "**On-chain:** The NFT information lives directly on the blockchain, integrated into the NFT itself.",
  "",
  "**Off-chain:** Information lives on servers or cloud storage (IPFS). Most metadata is stored off-chain as a JSON file.",
  "",
  "---",
  "",
  "## Dynamic NFTs (dNFTs)",
  "",
  "NFTs whose characteristics can change — also called semi-fungible or living NFTs. Used in DeFi games (badges that evolve) and art (pieces that change by artist-defined rules).",
  "",
  "Example: basketball player LaMelo Ball dynamic NFTs incorporate real sports data and update based on game results.",
  "",
  "---",
  "",
  "## How to Create an NFT",
  "",
  "**Step 1:** Choose the Blockchain (Ethereum, Solana, Tezos...)",
  "",
  "**Step 2:** Choose a Platform (see Platforms section)",
  "",
  "**Step 3:** Generate your file (artwork, music, video, code...)",
  "",
  "**Step 4:** Mint the file on the platform",
  "",
  "**Step 5:** List the NFT (price, edition, conditions)",
  "",
  "**Step 6:** Share through your community",
].join("\n");

const communities = [
  "# NFT Communities",
  "",
  "An NFT community is a digital group gathering to discuss, create, buy, sell, and exchange these tokens. Communities are crucial — it is impossible to thrive without community in this environment.",
  "",
  "---",
  "",
  "## Types of Communities",
  "",
  "**Project Communities:** Centered around a specific NFT project or collection.",
  "",
  "**Collector Communities:** People interested in collecting NFTs across projects.",
  "",
  "**Artist Communities:** Focused on digital artists creating NFTs.",
  "",
  "**Investor Communities:** People investing in NFTs for profit.",
  "",
  "---",
  "",
  "## How to Participate",
  "",
  "Use platforms like Discord, Twitter/X, and Warpcast. Be consistent and patient — building loyal community takes time. Be authentic and transparent about your goals.",
  "",
  "---",
  "",
  "## Tips for Beginners",
  "",
  "1. Do not trust easy money — do not expect millions in 2 weeks.",
  "2. Use NFT as a tool to showcase your work.",
  "3. Do not believe 'drop your NFT here' posts (engagement farming).",
  "4. Never create the same artwork on different blockchains.",
  "5. Do not flood chats with too many messages.",
  "",
  "---",
  "",
  "## Social Initiatives",
  "",
  "The **Balot NFT** initiative by the Congolese Plantation Workers Art League (CATPC) used NFT technology to reclaim cultural heritage and buy back lands in the Congo. Each NFT Balot represents one hectare of land, with funds used to replant forests.",
  "",
  "---",
  "",
  "## Critical Perspective",
  "",
  "> The virtual environment is only an extension of our physical world — it reflects and reproduces the social problems that exist in real life. The NFT scene is not exempt from politics. Every technology is a tool; the result depends on who is using it.",
].join("\n");

const platforms = [
  "# NFT Platforms",
  "",
  "Below is an overview of platforms across different blockchains. Explore **DappRadar** to discover platforms across many other networks.",
  "",
  "---",
  "",
  "## Ethereum and its L2s",
  "",
  "**Zora** — creator-focused, free minting",
  "**Super Rare** — curated 1/1 marketplace",
  "**Foundation** — invite-only curated platform",
  "**Manifold** — tools for creating custom smart contracts",
  "**Rarible** — multi-chain, creator royalties focus",
  "",
  "## Solana",
  "",
  "**3.land** — community and exhibition platform",
  "**Exchange Art** — curated digital art",
  "**Magic Eden** — largest Solana marketplace",
  "**Tensor** — trading and analytics",
  "",
  "## Tezos",
  "",
  "**Objkt** — largest Tezos marketplace",
  "**(fx)hash** — generative art platform",
  "**teia** — community-owned, artist-centered",
  "",
  "## Bitcoin Ordinals",
  "",
  "**Gamma** · **Magic Eden** · **Ordzaa**",
  "",
  "---",
  "",
  "## How to Choose?",
  "",
  "**Fees:** Tezos and Solana have very low fees; Ethereum is higher.",
  "",
  "**Community:** Different platforms attract different collector communities.",
  "",
  "**Curation:** Open (Objkt, Magic Eden) vs. curated (Super Rare, Foundation).",
  "",
  "**Mission:** teia is community-owned; other platforms are for-profit.",
  "",
  "> Platforms can change and close — but NFTs remain on the blockchain. Always be prepared to adapt.",
].join("\n");

const communication = [
  "# Communication Platforms",
  "",
  "NFT communities are built on essential social networks. These spaces connect artists and collectors.",
  "",
  "---",
  "",
  "## X (formerly Twitter)",
  "",
  "One of the most used platforms for NFT promotion. Many artists, traders, and crypto people maintain dedicated profiles. Despite changes, it remains important for discovering projects and participating in conversations.",
  "",
  "---",
  "",
  "## Discord",
  "",
  "Essential for community building. Artists, investors, and collectors connect, organize, and converse. Many NFT platforms and projects have their own Discord servers.",
  "",
  "---",
  "",
  "## Warpcast / Farcaster",
  "",
  "A **decentralized social network** with strong crypto-native audience. Annual subscription fee. Growing art community with Channels for organized topics.",
  "",
  "---",
  "",
  "## Nostr",
  "",
  "A simple, open protocol enabling global, decentralized, censorship-resistant social media. Multiple networks use this protocol.",
  "",
  "---",
  "",
  "## Choosing Your Platforms",
  "",
  "You do not need to be everywhere. Start with 1-2 platforms and build genuine connections before expanding. **Consistency and authenticity matter more than volume.**",
].join("\n");

const marketing = [
  "# Marketing",
  "",
  "## 1. Build a Solid Identity",
  "",
  "Develop a visual identity and a consistent voice that represents your personality — profile, bio, aesthetic palette, and your artistic narrative.",
  "",
  "---",
  "",
  "## 2. Be Active on Social Media",
  "",
  "Interact with your audience, share your work, and participate in conversations. Share works in progress, behind-the-scenes, and announcements for drops.",
  "",
  "---",
  "",
  "## 3. Organization is Fundamental",
  "",
  "Use post scheduling tools, maintain a launch calendar, and stay attentive to deadlines and opportunities.",
  "",
  "---",
  "",
  "## 4. Build Meaningful Connections",
  "",
  "Comment genuinely on others work. Participate in shared projects. Show up consistently in communities you care about. Offer help before asking for it.",
  "",
  "---",
  "",
  "## 5. Launch Frequency",
  "",
  "Find a sustainable rhythm. Burnout helps no one.",
  "",
  "---",
  "",
  "## 6. Pricing Strategies",
  "",
  "**Do not devalue yourself!** Consider scarcity, demand, currency value, and your time and craft.",
  "",
  "---",
  "",
  "## 7. Stay Creative and Connected",
  "",
  "Even in slower periods, keep creating and staying connected. Consistency and experimentation are essential.",
  "",
  "---",
  "",
  "## 8. Be Prepared for Change",
  "",
  "Platforms may change and close — this does not make NFTs disappear (they live on the blockchain). Keep experimenting with new possibilities.",
  "",
  "> Good marketing in the NFT space is about being genuinely present, sharing authentically, building relationships before transactions, and maintaining consistency over time.",
].join("\n");

const about = [
  "# About the Project",
  "",
  "**Computadores Fazem Arte** is an educational wiki about Blockchain, Web3, and NFTs — developed as part of a masters research in **Digital Artifact Design** at the Universidade Federal de Pernambuco (UFPE), funded by the MAI/DAI program of the CNPq.",
  "",
  "---",
  "",
  "## The Name",
  "",
  "The project name comes from a verse by **Fred Zero Quatro**, frontman of the legendary Recife band Mundo Livre S/A, from the song *Computadores Fazem Arte*.",
  "",
  "> Computadores avancam / Artistas pegam carona / Cientistas criam o novo / Artistas levam a fama — Fred Zero Quatro",
  "",
  "The song is both an observation and a provocation — and gave name to a project that tries to think critically about what it means for artists to inhabit technological spaces.",
  "",
  "Watch the song: https://www.youtube.com/watch?v=KZg_m0z4NLI",
  "",
  "---",
  "",
  "## Scientific Initiation — Undergraduate Researchers",
  "",
  "As part of the research, three undergraduate students were mentored across different areas of knowledge.",
  "",
  "### Milena — Pedagogy",
  "Brought an educational lens to the project, helping think through how complex technological concepts could be made accessible to diverse audiences.",
  "",
  "### Vitoria — Design",
  "Contributed a visual and communicational perspective, essential for shaping how the wiki and its materials are presented.",
  "",
  "### Artur — Computer Science · in memoriam",
  "Artur joined the research as a volunteer — entirely out of his own curiosity and enthusiasm. He was one of the most engaged and active participants in the project, bringing technical rigor and genuine excitement to every meeting. His presence left a mark on this research that cannot be measured. This project carries a piece of him.",
  "",
  "---",
  "",
  "## Presential Course — CTG/UFPE, 2024",
  "",
  "In 2024, a four-week presential course was held at the Centro de Tecnologia e Geociencias (CTG) of UFPE — bringing together students from different areas to learn about Blockchain, NFTs, and digital art communities.",
  "",
  "The course closing was interrupted by the **blocking of Twitter/X in Brazil** — a moment that became part of the project story and a live case study: a reminder that the same platforms that host digital art communities are subject to political decisions, regulatory pressures, and corporate power.",
  "",
  "The regulation of social media platforms is not a secondary topic — it is central to any honest conversation about digital rights, freedom of expression, and the conditions under which artists create and distribute their work. Platforms must be held accountable for guaranteeing users fundamental rights.",
  "",
  "---",
  "",
  "## Publication — WebMedia 2024",
  "",
  "The material developed in this research was published and presented at **WebMedia 2024**, held at the Universidade Federal de Juiz de Fora (UFJF).",
  "",
  "[Access the publication](https://books-sol.sbc.org.br/index.php/sbc/catalog/view/177/779/1513)",
  "",
  "---",
  "",
  "## Guest Lecture — Design for Web3, UFPE 2025",
  "",
  "In 2025, an invitation from **Professor Leonardo Castillo** led to a module called *Design para Web3* within the Design undergraduate course at UFPE.",
  "",
  "---",
  "",
  "## Contact",
  "",
  "**Numa** · [@numadessas](https://twitter.com/numadessas) · [contato@numadessas.com.br](mailto:contato@numadessas.com.br) · [numadessas.com.br](https://numadessas.com.br)",
].join("\n");

const references = [
  "# References",
  "",
  "## Academic Works",
  "",
  "**MENOTTI, Gabriel.** Criptoarte: A Metafisica do NFT e a Tecnocolonizacao da Autenticidade. 2021, Revista do Centro de Pesquisa e Formacao / No 13.",
  "",
  "**ASSANGE, Julian et al.** Cypherpunks: Liberdade e o Futuro da Internet. Sao Paulo: Boitempo, 2013.",
  "",
  "**PANDA, Sandeep Kumar et al.** Bitcoin and Blockchain: History and Current Applications. 2020, CRC Press.",
  "",
  "**AL-SAQAF, Walid; SEIDLER, Nicolas.** Blockchain technology for social impact. 2017, Journal of Cyber Policy.",
  "",
  "**KENT, Charlotte.** Blockchain manifestos: fighting for the imagination of a culture. 2021, Burlington Contemporary Journal.",
  "",
  "**LIMA, Junior Cesar de; CARVALHO, Cedric L. de.** Uma Visao da Web Semantica. 2004, UFG.",
  "",
  "---",
  "",
  "## Online Resources",
  "",
  "- [CoinMarketCap Glossary](https://coinmarketcap.com/academy/en/glossary)",
  "- [Web3 Foundation](https://web3.foundation/)",
  "- [Chainlink — What is a Dynamic NFT?](https://chain.link/education-hub/what-is-dynamic-nft)",
  "- [DappRadar](https://dappradar.com/)",
  "",
  "---",
  "",
  "## About this Project",
  "",
  "This wiki was developed by **Numa** as part of masters research in Digital Artifact Design at UFPE, funded by CNPq MAI/DAI program.",
  "",
  "Contact: [contato@numadessas.com.br](mailto:contato@numadessas.com.br)",
  "",
  "*Content is freely available for distribution.*",
].join("\n");

export const wikiSections = [
  {
    id: "introduction",
    slug: "introduction",
    title: "Introduction",
    subtitle: "About this wiki",
    tags: ["overview", "web3", "nft"],
    description: "What is Computadores Fazem Arte and why this knowledge matters.",
    related: ["glossary", "internet-generations"],
    content: intro,
  },
  {
    id: "glossary",
    slug: "glossary",
    title: "Glossary",
    subtitle: "Key terms",
    tags: ["reference", "terminology"],
    description: "Essential vocabulary for navigating the Web3 and NFT space.",
    related: ["introduction", "blockchain"],
    isGlossary: true,
    content: "Essential vocabulary for navigating the Web3 and NFT space. Click any term to expand its definition.",
    glossaryTerms: [
      { term: "DYOR", definition: "Do Your Own Research — an expression reminding everyone that investing in crypto is highly volatile. What works for one person does not necessarily work for another. Always stay attentive and keep updating your knowledge." },
      { term: "Flood", definition: "Sending too many messages about the same topic, creating visual pollution in chats and channels." },
      { term: "FOMO", definition: "Fear Of Missing Out — the anxiety of missing an opportunity, often driving impulsive decisions in volatile markets." },
      { term: "GM / GN", definition: "Good Morning / Good Night — common greetings used in NFT and crypto communities, often used to build daily connection." },
      { term: "Genesis", definition: "The first NFT someone launches on a network or platform. Inspired by the genesis block — the first block mined on a blockchain." },
      { term: "Hash", definition: "A unique sequence of characters generated from transaction data using a special mathematical function. Hashes verify data integrity, connect blockchain blocks securely, and enable mining." },
      { term: "IRL", definition: "In Real Life — used to describe life and events that happen outside the internet." },
      { term: "Block Explorer", definition: "A platform where you can access and read a blockchain publicly in real time. Each network has one or more explorers." },
      { term: "NFA", definition: "No Financial Advice — similar to DYOR. Used when discussing a project/coin to clarify that each person must evaluate for themselves what is appropriate for their financial situation." },
      { term: "Node", definition: "A computer that is part of a blockchain network structure. Each node holds an identical copy of all transactions that have occurred on the network." },
      { term: "Nonce", definition: "Short for number used once — a randomly generated number used only once in a cryptographic transaction." },
      { term: "Burn NFT", definition: "A process to render an NFT unusable. Since NFTs cannot be deleted from a blockchain, burning is used when one needs to effectively remove an NFT from circulation." },
      { term: "Scam", definition: "A fraudulent scheme designed to deceive users and steal assets or information." },
      { term: "Phishing", definition: "A type of cyber attack that steals personal and financial information, often through fake websites or messages that impersonate legitimate services." },
      { term: "WAGMI", definition: "We Are All Gonna Make It — an optimistic expression of collective encouragement common in NFT and crypto communities." },
      { term: "Whitepaper", definition: "A document explaining the objectives and technology of a crypto project. A crucial element for projects to be considered genuine and professional." },
      { term: "Engagement Farm", definition: "A manipulative strategy to increase visibility on social networks by encouraging people to post their content in exchanges that provide no real value." },
      { term: "Minting", definition: "The process of creating and registering an NFT on a blockchain. Minting an NFT makes it an official, verifiable digital asset." },
    ],
  },
  {
    id: "internet-generations",
    slug: "internet-generations",
    title: "Internet Generations",
    subtitle: "Web1, Web2, Web3",
    tags: ["web3", "history", "technology"],
    description: "From static pages to semantic, decentralized networks.",
    related: ["blockchain", "introduction"],
    content: internetGen,
  },
  {
    id: "blockchain",
    slug: "blockchain",
    title: "Blockchain Technology",
    subtitle: "How it works",
    tags: ["blockchain", "technology", "history"],
    description: "Digital ledgers, consensus mechanisms, block structure, and applications.",
    related: ["security", "nfts", "internet-generations"],
    content: blockchain,
  },
  {
    id: "security",
    slug: "security",
    title: "Security",
    subtitle: "Wallets and protection",
    tags: ["security", "wallets", "scam"],
    description: "Cryptocurrency wallets, private keys, and how to protect yourself from scams.",
    related: ["blockchain", "nfts"],
    content: security,
  },
  {
    id: "nfts",
    slug: "nfts",
    title: "NFTs",
    subtitle: "Non-fungible tokens",
    tags: ["nft", "art", "blockchain"],
    description: "What NFTs are, how they work, metadata, dynamic NFTs, and how to create one.",
    related: ["blockchain", "platforms", "communities"],
    content: nfts,
  },
  {
    id: "communities",
    slug: "communities",
    title: "NFT Communities",
    subtitle: "Building connections",
    tags: ["community", "nft", "culture"],
    description: "Types of communities, how to join, social initiatives, and critical perspectives.",
    related: ["platforms", "communication", "marketing"],
    content: communities,
  },
  {
    id: "platforms",
    slug: "platforms",
    title: "Platforms",
    subtitle: "NFT marketplaces",
    tags: ["nft", "platforms", "tools"],
    description: "An overview of NFT platforms across different blockchains.",
    related: ["nfts", "communication", "blockchain"],
    content: platforms,
  },
  {
    id: "communication",
    slug: "communication",
    title: "Communication",
    subtitle: "Where communities live",
    tags: ["community", "social", "tools"],
    description: "The social networks and communication tools that NFT communities use.",
    related: ["communities", "marketing"],
    content: communication,
  },
  {
    id: "marketing",
    slug: "marketing",
    title: "Marketing",
    subtitle: "Sharing your work",
    tags: ["marketing", "community", "strategy"],
    description: "Strategies for promoting your NFT work ethically and effectively.",
    related: ["communities", "communication", "platforms"],
    content: marketing,
  },
  {
    id: "about",
    slug: "about",
    title: "About the Project",
    subtitle: "Research and history",
    tags: ["research", "ufpe", "about"],
    description: "The origin of the project, the research behind it, and the people who built it.",
    related: ["introduction", "references"],
    content: about,
  },
  {
    id: "references",
    slug: "references",
    title: "References",
    subtitle: "Bibliography",
    tags: ["research", "bibliography"],
    description: "Academic and online references used in this wiki.",
    related: ["introduction"],
    content: references,
  },
];

export const allTerms = wikiSections
  .filter(s => s.glossaryTerms)
  .flatMap(s => s.glossaryTerms);

export const allTags = [...new Set(wikiSections.flatMap(s => s.tags))];

export const getSectionBySlug = (slug) => wikiSections.find(s => s.slug === slug);
export const getRelatedSections = (slugs) => slugs.map(slug => wikiSections.find(s => s.slug === slug)).filter(Boolean);
