// i18n - Portuguese UI strings
export const pt = {
  nav: {
    search: 'Buscar...',
    darkMode: 'Modo escuro',
    lightMode: 'Modo claro',
    language: 'Idioma',
    home: 'Início',
    back: 'Voltar',
    tableOfContents: 'Neste artigo',
    related: 'Artigos relacionados',
    tags: 'Tags',
    allTopics: 'Todos os tópicos',
    readingTime: 'min de leitura',
    copyLink: 'Copiar link',
    copied: 'Copiado!',
    copyDefinition: 'Copiar definição',
    expandAll: 'Expandir todos',
    collapseAll: 'Recolher todos',
  },
  sections: {
    introduction: 'Introdução',
    glossary: 'Glossário',
    'internet-generations': 'Gerações da Internet',
    blockchain: 'Tecnologia Blockchain',
    security: 'Segurança',
    nfts: 'NFTs',
    communities: 'Comunidades NFT',
    platforms: 'Plataformas',
    communication: 'Plataformas de Comunicação',
    marketing: 'Marketing',
    references: 'Referências',
  },
  home: {
    eyebrow: 'Wiki educacional',
    title: 'Computadores\nFazem Arte',
    subtitle: 'Um espaço de conhecimento sobre Blockchain, Web3, NFTs e comunidades digitais de arte.',
    explore: 'Explorar o wiki',
    by: 'por',
    topics: 'tópicos',
    terms: 'termos',
    free: 'livre e gratuito',
  },
  callout: {
    info: 'Informação',
    concept: 'Conceito',
    warning: 'Atenção',
  }
}
