// Conteúdo do wiki em Português
// Usa arrays de strings para evitar problemas com template literals

const intro = [
  "Para começar a conversar sobre NFTs, precisamos pensar antes em alguns termos-chave que fazem parte deste universo. Nesta formação, tem conteúdo das técnicas e práticas para criar obras de arte no mercado de NFTs.",
  "",
  "Esse projeto tem como principal objetivo incentivar mais pessoas a aprenderem a utilizar tecnologia Blockchain — também encorajar uma conversa séria sobre como as comunidades virtuais devem ser mais conscientes e dessa forma contribuir socialmente para o espaço físico.",
  "",
  "---",
  "",
  "Vamos falar sobre **Blockchain**, **cripto**, **comunidades digitais** e outros conceitos básicos para que você tenha autonomia e encorajamento inicial para criar suas obras e projetos NFTs.",
  "",
  "> Computadores avançam / Artistas pegam carona / Cientistas criam o novo / Artistas levam a fama — Fred Zero Quatro",
  "",
  "## Por que isso importa",
  "",
  "Este não é apenas um manual técnico. É um convite para pensar criticamente sobre tecnologia, arte e comunidade. O espaço das NFTs ainda é uma terra fértil — pouco explorada. Cabe a nós navegar nela de forma consciente: plantando boas ideias, sem desmatar.",
  "",
  "## Quem fez isso?",
  "",
  "Este material didático foi desenvolvido por **Numa** como parte integrante da pesquisa de mestrado em Design de Artefatos Digitais na Universidade Federal de Pernambuco (UFPE), financiada pelo programa MAI/DAI do CNPq.",
  "",
  "O conteúdo está disponível para **distribuição livre e gratuita**.",
].join("\n");

const internetGen = [
  "Antes de tudo, é importante aprender sobre as três gerações existentes da internet. Vivemos em um momento onde a Web 2 e a Web3 existem simultaneamente — cada geração não são coisas à parte, mas apenas continuações da web que já conhecemos. É possível encontrar conteúdo sobre isso se referindo como 'eras', em um sentido mais temporal, mas é mais interessante pensar em termos de formas de interação.",
  "",
  "<div style=\"overflow-x:auto;margin:2rem 0\"><table style=\"width:100%;border-collapse:collapse;text-align:center\">",
  "  <tr>",
  "    <td style=\"padding:1rem;background:transparent\"><img src=\"/wiki/images/web1.svg\" alt=\"\" style=\"height:80px;width:auto\" /></td>",
  "    <td style=\"padding:1rem;background:transparent\"><img src=\"/wiki/images/web2.svg\" alt=\"\" style=\"height:80px;width:auto\" /></td>",
  "    <td style=\"padding:1rem;background:transparent\"><img src=\"/wiki/images/web3.svg\" alt=\"\" style=\"height:80px;width:auto\" /></td>",
  "  </tr>",
  "  <tr style=\"background:#0a0a0a;color:#fafaf8\">",
  "    <td style=\"padding:0.6rem 1rem;font-family:Instrument Sans,sans-serif;font-weight:700;font-size:1.1rem;letter-spacing:-0.02em\">Web1</td>",
  "    <td style=\"padding:0.6rem 1rem;font-family:Instrument Sans,sans-serif;font-weight:700;font-size:1.1rem;letter-spacing:-0.02em\">Web2</td>",
  "    <td style=\"padding:0.6rem 1rem;font-family:Instrument Sans,sans-serif;font-weight:700;font-size:1.1rem;letter-spacing:-0.02em\">Web3</td>",
  "  </tr>",
  "  <tr style=\"background:#0a0a0a;color:#fafaf8\">",
  "    <td style=\"padding:0.4rem 1rem;font-style:italic;font-size:0.85rem\">read-only</td>",
  "    <td style=\"padding:0.4rem 1rem;font-style:italic;font-size:0.85rem\">read-write</td>",
  "    <td style=\"padding:0.4rem 1rem;font-style:italic;font-size:0.85rem\">read-write-own</td>",
  "  </tr>",
  "  <tr style=\"background:#0a0a0a;color:#fafaf8\">",
  "    <td style=\"padding:0.4rem 1rem 0.8rem;font-size:0.9rem\">Internet Simples</td>",
  "    <td style=\"padding:0.4rem 1rem 0.8rem;font-size:0.9rem\">Internet Social</td>",
  "    <td style=\"padding:0.4rem 1rem 0.8rem;font-size:0.9rem\">Internet Semântica</td>",
  "  </tr>",
  "</table></div>",
  "",
  "## Web 1.0 — A Internet Simples",
  "",
  "<figure style=\"margin:1.5rem 0\"><img src=\"/wiki/images/web1.jpg\" alt=\"Site antigo do Yahoo\" style=\"width:100%;border-radius:8px\" /><figcaption style=\"font-family:'Space Mono',monospace;font-size:0.65rem;text-transform:uppercase;letter-spacing:0.08em;color:var(--gray-400);margin-top:0.5rem;text-align:center\">Site antigo do Yahoo</figcaption></figure>",
  "",
  "A primeira fase da Internet surgiu nos **anos 90** e consistia em páginas com hiperlinks. Os sites eram principalmente informativos com layouts muito básicos, pouquíssimos recursos multimídia e a maioria do conteúdo baseado em texto. Só era possível acessar, ler e mudar de página, com pouca ou nenhuma interação ou ferramenta de feedback.",
  "",
  "<div class=\"callout callout-concept\"><span class=\"callout-icon\">📡</span><div><p class=\"callout-title\">Características da Web 1.0</p><ul style=\"margin:0.5rem 0 0;padding-left:1.25rem\"><li>Largura de banda limitada</li><li>Dispositivos limitados (somente desktop)</li><li>Nenhuma interação real, apenas leitura (<em>read-only</em>)</li></ul></div></div>",
  "",
  "> **Largura de banda (bandwidth):** é o conceito que determina a medida da capacidade de transmissão, em especial de conexão ou rede.",
  "",
  "## Web 2.0 — A Internet Social",
  "",
  "<figure style=\"margin:1.5rem 0\"><img src=\"/wiki/images/web2.jpg\" alt=\"Layout antigo do YouTube com o vídeo viral Charlie bit me\" style=\"width:100%;border-radius:8px\" /><figcaption style=\"font-family:'Space Mono',monospace;font-size:0.65rem;text-transform:uppercase;letter-spacing:0.08em;color:var(--gray-400);margin-top:0.5rem;text-align:center\">Layout antigo do YouTube com o vídeo viral <em>Charlie Bit My Finger</em></figcaption></figure>",
  "",
  "Surgiu por volta de **2004** — é a fase da Internet que trouxe mais conteúdo gerado pelo usuário e recursos visuais (*front-end*). Os usuários puderam compartilhar mais informações entre si e se conectar mais facilmente. Além disso, os usuários podem acessar informações e devolvê-las ao servidor para obter conteúdo mais personalizado.",
  "",
  "Em resumo, a Web 2.0 é marcada por maior interatividade e colaboração entre usuários, além de uma experiência mais rica. Essa fase viu o crescimento de plataformas de mídia social, blogs e outras ferramentas que permitem que os usuários criem e compartilhem seu próprio conteúdo. As grandes plataformas — como Google, Facebook e Instagram — centralizaram o controle dos dados dos usuários.",
  "",
  "<div class=\"callout callout-concept\"><span class=\"callout-icon\">📱</span><div><p class=\"callout-title\">Características da Web 2.0</p><ul style=\"margin:0.5rem 0 0;padding-left:1.25rem\"><li>Recursos visuais (<em>front-end</em>)</li><li>Conteúdo gerado pelos usuários</li><li>Ascensão das redes sociais</li><li>Dispositivos mobile</li></ul></div></div>",
  "",
  "<div style=\"display:grid;grid-template-columns:1fr 1fr;gap:1rem;margin:1.5rem 0\">",
  "  <div class=\"callout callout-info\"><span class=\"callout-icon\">🖥️</span><div><p class=\"callout-title\">Front-end</p>A parte com a qual os usuários interagem: a interface visível — layout, design, animações. Utiliza HTML, CSS e JavaScript.</div></div>",
  "  <div class=\"callout callout-info\"><span class=\"callout-icon\">⚙️</span><div><p class=\"callout-title\">Back-end</p>A parte que lida com a lógica invisível: processamento, armazenamento e autenticações. Utiliza Python, Ruby, Java, Rust.</div></div>",
  "</div>",
  "",
  "> É possível encontrar vagas de emprego para desenvolvedores de front-end, back-end e **full-stack** — um profissional capaz de atuar em ambas as áreas.",
  "",
  "## Web3 — A Internet Semântica",
  "",
  "<figure style=\"float:left;margin:0 1.5rem 1rem 0;width:200px\"><img src=\"/wiki/images/web3.jpg\" alt=\"Carteira Solflare\" style=\"width:100%;border-radius:8px\" /><figcaption style=\"font-family:'Space Mono',monospace;font-size:0.65rem;text-transform:uppercase;letter-spacing:0.08em;color:var(--gray-400);margin-top:0.5rem;text-align:center\">Carteira Solflare</figcaption></figure>",
  "",
  "A partir de **2008**, quando a tecnologia Blockchain entrou em ação através do Bitcoin. Os princípios da Web3 têm a intenção de permitir que os usuários possuam seus próprios dados, ao invés de empresas — facilitando transações digitais de informações e valores de forma segura e descentralizada.",
  "",
  "Conhecida também como **Web Semântica**, pois tem o objetivo de tornar a informação 'compreensível' para o computador através do *machine learning* (aprendizado de máquina).",
  "",
  "> **Semântica** é a parte da linguística que estuda o que as palavras realmente querem dizer.",
  "",
  "No universo cripto, é comum referir-se a ela simplesmente como **'web3'** — sem o '.0' — especialmente ao falar de projetos descentralizados, NFTs e DeFi.",
  "",
  "**Além da blockchain**, a Web3 engloba outras tecnologias: IPFS (armazenamento descentralizado), contratos inteligentes, DAOs (organizações autônomas descentralizadas), identidade digital soberana e redes de computação distribuída como Filecoin e Render.",
  "",
  "A ideia de **trustless** das Blockchains é, ao invés de confiar em pessoas ou instituições, confiar totalmente na tecnologia, que é vista como imparcial e capaz de promover mais liberdade.",
  "",
  "<div style=\"clear:both\"></div>",
  "",
  "<div class=\"callout callout-concept\"><span class=\"callout-icon\">🌐</span><div><p class=\"callout-title\">Características da Web3</p><ul style=\"margin:0.5rem 0 0;padding-left:1.25rem\"><li>Descentralização de dados</li><li>Machine learning e automação</li><li>Dados Inteligentes</li></ul></div></div>",
  "",
  "## Décadas do desenvolvimento web",
  "",
  "<figure style=\"margin:2rem 0\"><img src=\"/wiki/images/web-evolution-pt.svg\" alt=\"Gráfico de evolução da internet\" style=\"width:100%\" /><figcaption style=\"font-family:'Space Mono',monospace;font-size:0.65rem;text-transform:uppercase;letter-spacing:0.08em;color:var(--gray-400);margin-top:0.5rem;text-align:center\">Releitura do Gráfico de Evolução da Internet do artigo <a href=\"https://www.mdpi.com/1999-5903/4/3/852\" target=\"_blank\">'When the Social meets the Semantic: Social Semantic Web or Web 2.5'</a> de Carlos Fernandez-Llatas e Vicente Traver.</figcaption></figure>",
  "",
  "<div style=\"display:flex;flex-direction:column;gap:0.5rem;margin:2rem 0\">",
  "  <div style=\"background:var(--gray-900);color:var(--white);border-radius:8px;padding:1rem 1.25rem\">",
  "    <p style=\"font-family:'Space Mono',monospace;font-size:0.7rem;text-transform:uppercase;letter-spacing:0.08em;color:var(--orange);margin:0 0 0.25rem\">1980 – 1990</p>",
  "    <p style=\"font-family:'Instrument Sans',sans-serif;font-weight:600;font-size:1rem;margin:0\">Tecnologia da Web</p>",
  "  </div>",
  "  <div style=\"background:var(--gray-900);color:var(--white);border-radius:8px;padding:1rem 1.25rem\">",
  "    <p style=\"font-family:'Space Mono',monospace;font-size:0.7rem;text-transform:uppercase;letter-spacing:0.08em;color:var(--orange);margin:0 0 0.25rem\">1990 – 2000</p>",
  "    <p style=\"font-family:'Instrument Sans',sans-serif;font-weight:600;font-size:1rem;margin:0\">Redes e Multimídia</p>",
  "  </div>",
  "  <div style=\"background:var(--gray-900);color:var(--white);border-radius:8px;padding:1rem 1.25rem\">",
  "    <p style=\"font-family:'Space Mono',monospace;font-size:0.7rem;text-transform:uppercase;letter-spacing:0.08em;color:var(--orange);margin:0 0 0.25rem\">2010 – 2020</p>",
  "    <p style=\"font-family:'Instrument Sans',sans-serif;font-weight:600;font-size:1rem;margin:0\">Banda Larga, Tecnologias Semânticas, Computação Móvel e Armazenamento em Nuvem</p>",
  "  </div>",
  "</div>",
].join("\n");

const blockchain = [
  "## O que é Blockchain?",
  "",
  "As Blockchains são como **livros de registros digitais e descentralizados**. Redes online onde os dados são salvos nos computadores de cada usuário da Blockchain, não apenas em um só servidor.",
  "",
  "Uma analogia útil: a blockchain é como uma grande **planilha compartilhada** replicada em milhares de computadores. Essa planilha é atualizada constantemente e cada nó verifica cada nova entrada.",
  "",
  "## História",
  "",
  "A tecnologia Blockchain teve suas origens em **1991**, quando Stuart Haber e W. Scott Stornetta publicaram um artigo sobre como colocar um carimbo de data e hora em documentos digitais de forma segura, usando uma série criptografada de blocos.",
  "",
  "| Ano | Evento |",
  "|-----|--------|",
  "| **1979** | Ralph Merkle cria e patenteia o conceito de Árvore de Merkle. |",
  "| **1982** | David Chaum descreve em Berkeley os fundamentos da tecnologia blockchain, com exceção da prova de trabalho. |",
  "| **1991** | Stuart Haber e Scott Stornetta publicam *How to Time-Stamp a Digital Document* — o primeiro conceito de Blockchain, usando Merkle Tree. |",
  "| **1992** | A Merkle Tree é introduzida na criptografia e ciência da computação. Criação do mailing do movimento **cypherpunk**, grupo que defende privacidade e liberdade individual usando criptografia como ferramenta de mudança social. |",
  "| **2002** | David Mazières e Dennis Shasha propõem como armazenar dados em blocos com a estrutura SUNDR. |",
  "| **2005** | Nick Szabo propõe uma criptomoeda chamada *Bitgold*. |",
  "| **2008** | Satoshi Nakamoto publica *Bitcoin: A Peer-to-Peer Electronic Cash System*. |",
  "| **2009** | O primeiro Bitcoin é minerado e usuários começam a utilizá-lo. |",
  "| **2010** | **Bitcoin Pizza Day** — em 22 de maio, Laszlo Hanyecz troca 10.000 BTC por 2 pizzas nos EUA. Primeiro registro de uma compra real paga com criptomoeda, comemorado anualmente. |",
  "| **2013** | O mercado do Bitcoin ultrapassa US$ 1 milhão. Vitalik Buterin lança o whitepaper do Ethereum. |",
  "| **2014** | Nasce a **R3**, consórcio de bancos para levar blockchain ao mundo corporativo. Ethereum realiza crowdsale: 60 milhões de ETH por ~US$ 18 milhões. |",
  "| **2015** | Rede Ethereum lançada oficialmente, com seu primeiro bloco minerado. Linux Foundation lança a **Hyperledger**. |",
  "| **2016** | R3 lança a **Corda**, primeira plataforma blockchain para empresas. A Ethereum DAO é atacada por hackers por falha no código. |",
  "| **2017** | Dan Larimer lança a **EOS**, plataforma de contratos inteligentes sem taxas de transação. |",
  "| **2018** | Forbes destaca 9 empresas blockchain entre as 50 principais fintechs do ano. |",
  "| **2021** | Boom dos NFTs com obras vendidas por valores históricos. Lançamento da **hic et nunc**, plataforma criada pelo brasileiro Rafael e equipe em Brasília. |",
  "",
  "## Como funciona uma Blockchain?",
  "",
  "Imagine que você quer enviar dinheiro para alguém sem passar por um banco. Na blockchain, isso acontece em quatro etapas — sem intermediários, sem servidor central, sem possibilidade de fraude.",
  "",
  "![Como funciona a Blockchain — diagrama com 4 etapas](/wiki/images/how-blockchain-works.svg)",
  "",
  "**① Você solicita uma transação**",
  "Seu pedido é codificado em um bloco contendo: quem envia, quem recebe e qual o valor. É como um envelope lacrado com todas as informações necessárias.",
  "",
  "**② A rede inteira fica sabendo**",
  "Esse bloco é transmitido para milhares de computadores ao redor do mundo — os *nós* da rede. Cada um deles verifica de forma independente se a transação é válida.",
  "",
  "**③ Os nós chegam a um consenso**",
  "A rede precisa concordar sobre qual bloco será adicionado. Esse processo — chamado de *consenso* — pode acontecer por mineração (PoW) ou validação (PoS). Saiba mais em [Mecanismos de Consenso](consensus-mechanisms).",
  "",
  "**④ A transação é gravada para sempre**",
  "O bloco aprovado é adicionado à cadeia de forma permanente e imutável. Ninguém pode apagar, alterar ou reverter — nem o criador da transação.",
  "",
  "## Mecanismos de Consenso",
  "",
  "Para que todos os computadores da rede concordem sobre quais transações são válidas, a blockchain usa **mecanismos de consenso** — protocolos que garantem segurança e integridade sem uma autoridade central.",
  "",
  "Os principais mecanismos são Prova de Trabalho (PoW), Prova de Participação (PoS), Prova de Autoridade (PoA) e Prova de História (PoH) — cada um com formas diferentes de minerar e validar blocos.",
  "",
  "> Veja o artigo completo: [Mecanismos de Consenso](consensus-mechanisms)",
  "",
  "## Propriedades da Blockchain",
  "",
  "**Descentralização:** Sem autoridade central — o controle é distribuído entre todos os participantes da rede.",
  "",
  "**Transparência:** Todas as transações são públicas e rastreáveis via navegadores de blocos.",
  "",
  "**Imutabilidade:** Uma vez registrado, o dado não pode ser alterado.",
  "",
  "**Anonimato:** Usuários têm endereços públicos (não identidade pessoal).",
  "",
  "## Camadas das Blockchains",
  "",
  "| Camada | Função | Exemplos |",
  "|--------|--------|---------|",
  "| L0 | Infraestrutura, interoperabilidade | Polkadot, Cosmos |",
  "| L1 | Blockchains principais, consenso | Bitcoin, Ethereum, Solana |",
  "| L2 | Escalabilidade, redução de taxas | Optimism, Polygon, Arbitrum |",
  "| L3 | Camada de aplicação cross-chain | IBC Protocol, Quant |",
].join("\n");

const miningValidation = [
  "Os mecanismos de consenso são protocolos que permitem que uma rede descentralizada de computadores concorde com o estado da blockchain — ou seja, quais transações são válidas e em que ordem devem ser adicionadas.",
  "",
  "Esses mecanismos são cruciais para garantir a segurança, integridade e confiabilidade da blockchain, evitando fraudes e garantindo que todos os participantes da rede tenham uma cópia idêntica e atualizada do registro.",
  "",
  "## Prova de Trabalho — Proof of Work (PoW)",
  "",
  "**Mineração:** Mineradores competem para resolver um complexo problema matemático (hash criptográfico). O primeiro a encontrar a solução *prova* seu trabalho, adiciona o bloco à blockchain e é recompensado com criptomoedas.",
  "",
  "**Validação:** Se a maioria dos outros nós concordar com o trabalho do minerador, o bloco é adicionado à blockchain.",
  "",
  "**Exemplos:** Bitcoin (BTC) · Litecoin (LTC) · Monero (XMR)",
  "",
  "## Prova de Participação — Proof of Stake (PoS)",
  "",
  "**Mineração:** Não há mineração. Os validadores são escolhidos para propor e validar blocos com base na quantidade de criptomoedas que possuem e estão dispostos a *apostar* (staking). Quanto maior a participação, maior a chance de ser escolhido.",
  "",
  "**Validação:** Outros validadores verificam a validade do bloco. Se a maioria concordar, o bloco é adicionado à blockchain.",
  "",
  "**Exemplos:** Ethereum (ETH) · Cardano (ADA) · Tezos (XTZ) · Avalanche (AVAX) · Algorand (ALGO)",
  "",
  "## Prova de Autoridade — Proof of Authority (PoA)",
  "",
  "**Mineração:** Não há mineração. Validadores são pré-selecionados e autorizados a criar e validar blocos.",
  "",
  "**Validação:** Validadores autorizados verificam as transações e as adicionam à blockchain.",
  "",
  "**Exemplos:** Binance Coin (BNB) · VeChain (VET) · XRP",
  "",
  "## Prova de História — Proof of History (PoH)",
  "",
  "**Mineração:** Não há mineração. O sistema utiliza um registro imutável de eventos passados (hashgraph) para determinar a ordem das transações e a validade dos blocos.",
  "",
  "**Validação:** A validação é realizada por um grupo de nós que verificam a ordem das transações e a integridade do hashgraph.",
  "",
  "**Exemplos:** Hedera Hashgraph (HBAR)",
  "",
  "## O caso especial da Solana",
  "",
  "A Solana combina dois mecanismos: **PoH + PoS**. O PoH funciona como um relógio interno — cada evento na rede recebe um carimbo de tempo criptográfico, criando uma ordem verificável de transações antes mesmo da validação. Esse registro histórico permite que os validadores (escolhidos por PoS) trabalhem em paralelo, sem precisar esperar uns pelos outros para confirmar a ordem dos blocos.",
  "",
  "O resultado é uma rede muito mais rápida: enquanto o Ethereum processa ~15 transações por segundo, a Solana pode atingir dezenas de milhares.",
  "",
  "## Comparativo",
  "",
  "| Mecanismo | Mineração | Validação | Exemplos |",
  "|-----------|-----------|-----------|---------|",
  "| **PoW** | Competição por hash criptográfico | Maioria dos nós concorda | Bitcoin, Litecoin, Monero |",
  "| **PoS** | Sem mineração — seleção por stake | Maioria dos validadores concorda | Ethereum, Cardano, Tezos |",
  "| **PoA** | Sem mineração — validadores pré-autorizados | Validadores autorizados | Binance Coin, VeChain, XRP |",
  "| **PoH** | Sem mineração — registro histórico (hashgraph) | Nós verificam ordem e integridade | Hedera Hashgraph |",
  "| **PoH + PoS** | Sem mineração — relógio criptográfico + stake | Validadores em paralelo | Solana |",
  "",
  "> Voltar para: [Tecnologia Blockchain](blockchain)",
].join("\n");

const cryptography = [
  "**Criptografia** é a transformação de dados legíveis em dados codificados — que só podem ser decifrados com a chave certa. É a tecnologia que torna a blockchain possível: sem ela, não haveria como garantir que transações são autênticas, que dados não foram adulterados ou que uma moeda digital não foi gasta duas vezes.",
  "",
  "## Por que cripto se chama cripto",
  "",
  "O prefixo *cripto* vem do grego *kryptós* — oculto, secreto. **Criptomoeda** significa literalmente moeda protegida por criptografia. Não é só um nome — é uma descrição do que ela é: uma moeda cuja segurança e autenticidade dependem inteiramente de funções criptográficas.",
  "",
  "## A Árvore de Merkle",
  "",
  "Uma das estruturas mais importantes para a blockchain é a **Árvore de Merkle**, criada por Ralph Merkle em 1979.",
  "",
  "Funciona assim: cada transação gera um código único chamado *hash*. Esses hashes são agrupados aos pares e combinados em novos hashes — e assim sucessivamente, até restar um único hash no topo, chamado de **Merkle Root**.",
  "",
  "Esse processo cria uma impressão digital de todo o bloco. Se qualquer transação for alterada — mesmo que minimamente — o Merkle Root muda completamente. Isso torna a adulteração imediatamente detectável por qualquer nó da rede.",
  "",
  "É por isso que a blockchain é **imutável**: não porque seja fisicamente impossível alterar um dado, mas porque qualquer alteração quebra a cadeia de hashes e é rejeitada pela rede.",
  "",
  "> Veja a linha do tempo completa de como isso levou à criação do Bitcoin em [Tecnologia Blockchain](blockchain).",
  "",
  "## Como a criptografia protege a blockchain",
  "",
  "**Autenticidade:** Cada transação é assinada com a chave privada do remetente. Só quem tem a chave pode autorizar o envio — mas qualquer um pode verificar que a assinatura é legítima usando a chave pública.",
  "",
  "**Integridade:** O hash de cada bloco inclui o hash do bloco anterior. Alterar qualquer bloco antigo invalida todos os blocos seguintes — tornando a fraude computacionalmente inviável.",
  "",
  "**Descentralização:** Como a verificação é matemática, não há necessidade de uma autoridade central. Qualquer nó pode confirmar que uma transação é válida apenas com as regras criptográficas.",
].join("\n");

const security = [
  "A **carteira (wallet)** é como uma conta bancária para suas moedas digitais. Feita para armazenar cripto obtida através de compra, transferência ou mineração/validação. É o principal meio de interagir com sites e aplicativos da Web3.",
  "",
  "As carteiras funcionam de formas diferentes dependendo do tipo: as **carteiras de extensão** rodam diretamente no navegador — você as instala como um plugin e acessa via ícone na barra do navegador, conectando-se a qualquer site Web3 com um clique. As **carteiras mobile** funcionam como aplicativos no celular, com QR codes para facilitar transações. As **carteiras desktop** são programas instalados no computador. Já as **carteiras de hardware** são dispositivos físicos que você conecta ao computador para assinar transações com segurança máxima.",
  "",
  "> **Dica:** Use o navegador [Brave](https://brave.com) — ele é focado em privacidade, bloqueia anúncios nativamente e possui uma carteira cripto integrada compatível com Ethereum, Solana e outras redes.",
  "",
  "## Chaves de Segurança",
  "",
  "**Chaves Públicas:** Como os números das contas bancárias — uma sequência de números e letras gerada aleatoriamente ao criar uma carteira. É a informação necessária para transferir ou receber ativos digitais. Seguro compartilhar.",
  "",
  "**Chaves Privadas / Frase-Semente:** Devem ser mantidas em sigilo e local físico seguro. A frase-semente é a parte mais importante da segurança — com ela é possível recuperar a mesma conta em diferentes dispositivos.",
  "",
  "![Seed phrase — papel com palavras secretas](/wiki/images/seed-phrase.png)",
  "",
  "> Atenção: Essas chaves não devem ser mantidas de maneira nenhuma em arquivos digitais ou e-mails. Uma vez que você perder a seed-phrase, é impossível resgatar sua carteira. Não existe sistema de recuperação.",
  "",
  "## Tipos de Carteiras",
  "",
  "### Carteira Digital (Hot Wallet)",
  "",
  "São as carteiras usadas em desktop e aplicativos mobile. Softwares sem nenhuma instituição central ou terceiro que detenha os fundos da carteira. Comumente vinculadas a plataformas de negociação, permitindo que os usuários monitorem seu saldo criptográfico enquanto mantêm suas chaves privadas.",
  "",
  "As carteiras de desktop normalmente são gratuitas e muitas empregam programação de código aberto. A maioria das carteiras de desktop tem equivalentes móveis, permitindo que os usuários mudem de um desktop para um dispositivo móvel.",
  "",
  "### Carteira de Hardware (Cold Wallet)",
  "",
  "As carteiras de hardware são dispositivos físicos para fazer o gerenciamento de suas cripto — existem diversos formatos e também contêm chaves públicas e privadas. Para fazer operações, conecta-se o hardware ao computador via cabo ou wireless utilizando o software específico do modelo.",
  "",
  "São frequentemente chamadas de carteiras frias, porém existe a possibilidade de conectá-las à internet, o que não é recomendado caso você queira usá-las como meio de armazenamento.",
  "",
  "Podem ser adquiridas diretamente com as marcas que produzem ou revendas especializadas. **Utilize sites oficiais das marcas para comprar — evite comprar de revendas não autorizadas e pessoas desconhecidas por questão de segurança.** No Brasil tem a [KriptoBR](https://kriptobr.com).",
  "",
  "Algumas marcas conhecidas: [Ledger](https://www.ledger.com) · [Trezor](https://trezor.io) · [Ngrave](https://www.ngrave.io) · [BC Vault](https://bc-vault.com) · [Ellipal](https://www.ellipal.com)",
  "",
  "![Hardware wallets — dispositivos físicos Trezor, Ledger e Ngrave](/wiki/images/hardware-wallets.png)",
  "",
  "## Carteiras por Blockchain",
  "",
  "| Blockchain | Carteiras |",
  "|------------|-----------|",
  "| **Bitcoin** | [Phantom](https://phantom.app) · [Nightly](https://nightly.app) · [Xverse](https://xverse.app) |",
  "| **Solana** | [Phantom](https://phantom.app) · [Solflare](https://solflare.com) · [Nightly](https://nightly.app) |",
  "| **Tezos** | [Temple](https://templewallet.com) · [Kukai](https://kukai.app) |",
  "| **Ethereum** | [MetaMask](https://metamask.io) · [Rainbow](https://rainbow.me) · [Rabby](https://rabby.io) · [Brave Wallet](https://brave.com/wallet) |",
  "| **Ethereum L2s** (Optimism, Arbitrum, Base) | [MetaMask](https://metamask.io) · [Rainbow](https://rainbow.me) · [Rabby](https://rabby.io) |",
  "| **Scroll** | [MetaMask](https://metamask.io) · [Rabby](https://rabby.io) |",
  "| **Monad** | [MetaMask](https://metamask.io) · [Phantom](https://phantom.app) |",
  "| **Avalanche** | [Core](https://core.app) · [MetaMask](https://metamask.io) |",
  "| **Algorand** | [Pera](https://perawallet.app) · [Defly](https://defly.app) |",
  "| **Stellar** | [Hana](https://www.hana.money) · [Lobstr](https://lobstr.co) · [Freighter](https://freighter.app) |",
  "| **NEAR** | [MyNearWallet](https://mynearwallet.com) · [Meteor](https://meteorwallet.app) |",
  "| **Sui** | [Sui Wallet](https://suiwallet.com) · [Suiet](https://suiet.app) |",
  "",
  "> Esta tabela cobre as principais redes, mas existem muitas outras blockchains. Explore o [DappRadar](https://dappradar.com) para descobrir mais redes e carteiras.",
  "",
  "## Golpes Comuns",
  "",
  "<div class=\"callout callout-info\"><span class=\"callout-icon\">⚠️</span><div><p class=\"callout-title\">Perfis Falsos no Instagram</p>Se passam por colecionadores e oferecem preços altos pela sua obra, depois pedem uma taxa para finalizar a venda — que nunca acontece.</div></div>",
  "",
  "<div class=\"callout callout-info\"><span class=\"callout-icon\">⚠️</span><div><p class=\"callout-title\">Propostas de Trabalho Falsas</p>Oferecem comissões ou testes de jogos com arquivos infectados com malware que vasculham o computador para invadir carteiras.</div></div>",
  "",
  "<div class=\"callout callout-info\"><span class=\"callout-icon\">⚠️</span><div><p class=\"callout-title\">Sites Fraudulentos</p>Clones de projetos populares. Quando você conecta sua carteira, drenam todos os fundos.</div></div>",
  "",
  "## Medidas de Segurança",
  "",
  "<div class=\"callout callout-concept\"><span class=\"callout-icon\">🔑</span><div><p class=\"callout-title\">Nunca compartilhe suas chaves</p>Sua chave privada e seed phrase nunca devem ser digitadas em nenhum site, app ou mensagem. Nenhuma plataforma legítima vai pedir isso.</div></div>",
  "",
  "<div class=\"callout callout-concept\"><span class=\"callout-icon\">🔗</span><div><p class=\"callout-title\">Não clique em links desconhecidos</p>Links enviados por DM, e-mail ou redes sociais podem ser armadilhas. Acesse os sites sempre digitando o endereço diretamente.</div></div>",
  "",
  "<div class=\"callout callout-concept\"><span class=\"callout-icon\">📎</span><div><p class=\"callout-title\">Não abra anexos de perfis desconhecidos</p>Arquivos enviados por estranhos podem conter malware projetado para roubar dados da sua carteira.</div></div>",
  "",
  "<div class=\"callout callout-concept\"><span class=\"callout-icon\">🌐</span><div><p class=\"callout-title\">Não conecte sua carteira em qualquer site</p>Antes de conectar, verifique o endereço do site com atenção. Sites falsos podem drenar sua carteira instantaneamente.</div></div>",
  "",
  "<div class=\"callout callout-concept\"><span class=\"callout-icon\">💰</span><div><p class=\"callout-title\">Desconfie de propostas exorbitantes</p>Ofertas boas demais para ser verdade geralmente são golpes. No mundo cripto, o FOMO é uma das principais ferramentas dos golpistas.</div></div>",
  "",
  "<div class=\"callout callout-concept\"><span class=\"callout-icon\">📦</span><div><p class=\"callout-title\">Guarde suas chaves em local físico seguro</p>Anote sua seed phrase em papel e guarde em um lugar seguro, longe de câmeras e de outras pessoas. Nunca em arquivos digitais.</div></div>",
  "",
  "<div class=\"callout callout-concept\"><span class=\"callout-icon\">🛡️</span><div><p class=\"callout-title\">Use extensões anti-phishing</p>Instale extensões como <a href=\"https://www.pocketuniverse.app\" target=\"_blank\">Pocket Universe</a> e <a href=\"https://www.walletguard.app\" target=\"_blank\">Wallet Guard</a> para alertas em tempo real sobre sites e transações suspeitas.</div></div>",
].join("\n");

const nfts = [
  "## O que são NFTs?",
  "",
  "Podemos entender **NFT** como o **certificado digital de propriedade de um item**. Esse certificado é criado e registrado em uma rede Blockchain e pode conter arquivos, links, texto ou códigos.",
  "",
  "NFT significa **Non-Fungible Token** (ficha não fungível). Fungível = substituível (dinheiro, carros). Infungível = único, insubstituível (obras de arte, bens imóveis).",
  "",
  "## Metadados",
  "",
  "Metadados NFT são como etiquetas com as propriedades de um ativo digital: descrição do arquivo, nome, categorias, histórico de transações, data e hora.",
  "",
  "**On-chain:** A informação fica diretamente na rede Blockchain, integrada ao próprio NFT.",
  "",
  "**Off-chain:** A informação fica em servidores ou sistemas de armazenamento em nuvem (IPFS). A maioria dos metadados é armazenada off-chain como arquivo JSON.",
  "",
  "## NFTs Dinâmicos (dNFTs)",
  "",
  "NFTs cujas características podem mudar — também conhecidos como semi fungíveis ou NFT vivo. Bastante usados em jogos DeFi (insígnias que evoluem) e nas artes (peças que mudam conforme regras definidas pelo artista).",
  "",
  "Exemplo: Os NFTs do jogador de basquete LaMelo Ball incorporam dados esportivos na rede e mudam dependendo do resultado dos jogos.",
  "",
  "## Como fazer NFT",
  "",
  "**Passo 1:** Escolher a Blockchain (Ethereum, Solana, Tezos...)",
  "",
  "**Passo 2:** Escolher a Plataforma (veja seção Plataformas)",
  "",
  "**Passo 3:** Gerar um arquivo (sua arte, música, vídeo, código...)",
  "",
  "**Passo 4:** Mintar o arquivo na Plataforma",
  "",
  "**Passo 5:** Listar a NFT (preço, edição, condições)",
  "",
  "**Passo 6:** Divulgação — construa visibilidade pela sua comunidade",
].join("\n");

const communities = [
  "Uma **comunidade NFT** é um grupo digital de pessoas interessadas em NFTs, que se reúnem para discutir, criar, comprar, vender e trocar esses tokens. As comunidades são cruciais — é impossível prosperar sem comunidade nesse ambiente.",
  "",
  "## Tipos de Comunidades NFT",
  "",
  "**Comunidades de projeto:** Centradas em torno de um projeto NFT específico, como uma coleção de arte digital.",
  "",
  "**Comunidades de colecionadores:** Reúnem pessoas interessadas em colecionar NFTs, independentemente do projeto.",
  "",
  "**Comunidades de artistas:** Focadas em artistas digitais que criam NFTs.",
  "",
  "**Comunidades de investidores:** Compostas por pessoas que investem em NFTs com fins lucrativos.",
  "",
  "## Como participar",
  "",
  "Utilize as plataformas sociais comuns: Discord, Twitter/X e Warpcast. Seja consistente e paciente — construir uma comunidade leal leva tempo e esforço. Seja autêntico e transparente sobre seus objetivos.",
  "",
  "## Dicas para iniciantes",
  "",
  "1. Não confie em dinheiro fácil — não espere ser milionário em 2 semanas.",
  "2. Use NFT como uma ferramenta para mostrar seu trabalho.",
  "3. Não acredite em postagens do tipo deixe seu NFT aqui (engagement farm).",
  "4. Nunca crie a mesma arte em Blockchains diferentes.",
  "5. Não inunde bate-papos com mensagens demais.",
  "",
  "## Iniciativas Sociais",
  "",
  "A iniciativa **Balot NFT**, liderada pela Congolese Plantation Workers Art League (CATPC), usou a tecnologia NFT para reivindicar o patrimônio cultural e comprar de volta terras roubadas pelo plantation no Congo. Cada NFT Balot representa um hectare de terra, e os fundos são usados para replantar florestas.",
  "",
  "## Perspectiva Crítica",
  "",
  "> O ambiente virtual é apenas uma extensão do nosso mundo físico — obviamente reflete e reproduz os problemas sociais existentes na vida real. O cenário das NFTs não é isento de política. Toda tecnologia é uma ferramenta. O resultado do seu uso vai de quem estiver utilizando-a.",
].join("\n");

const platforms = [
  "Abaixo está uma visão geral de plataformas disponíveis em diferentes blockchains. Explore o **DappRadar** para descobrir plataformas em muitas outras redes.",
  "",
  "## Ethereum e suas L2s",
  "",
  "**Zora** — focada em criadores, mintagem gratuita",
  "**Super Rare** — marketplace curado de obras 1/1",
  "**Foundation** — plataforma curada por convite",
  "**Manifold** — ferramentas para contratos inteligentes personalizados",
  "**Rarible** — multi-chain, foco em royalties para criadores",
  "",
  "## Solana",
  "",
  "**3.land** — comunidade e exposições",
  "**Exchange Art** — arte digital curada",
  "**Magic Eden** — maior marketplace de Solana",
  "**Tensor** — trading e análises",
  "",
  "## Tezos",
  "",
  "**Objkt** — maior marketplace de Tezos",
  "**(fx)hash** — arte generativa",
  "**teia** — community-owned, centrada em artistas",
  "",
  "## Bitcoin Ordinals",
  "",
  "**Gamma** · **Magic Eden** · **Ordzaa**",
  "",
  "## Como escolher uma plataforma?",
  "",
  "**Taxas:** Tezos e Solana têm taxas muito baixas; Ethereum é mais alta.",
  "",
  "**Comunidade:** Diferentes plataformas atraem diferentes comunidades de colecionadores.",
  "",
  "**Curadoria:** Abertas (Objkt, Magic Eden) vs. curadas (Super Rare, Foundation).",
  "",
  "**Missão:** teia é community-owned; outras plataformas são comerciais.",
  "",
  "> Lembre-se: plataformas podem mudar e até fechar — mas as NFTs permanecem na blockchain. Esteja sempre preparada para se adaptar.",
].join("\n");

const communication = [
  "As comunidades NFTs se constroem em redes sociais essenciais. Estes espaços são necessários para conectar artistas e colecionadores.",
  "",
  "## X (Antigo Twitter)",
  "",
  "Uma das plataformas mais usadas para divulgar NFTs. Muitos artistas, traders e pessoas do meio cripto têm perfis dedicados a esse assunto. Apesar das mudanças recentes, ainda é uma rede importante para o mundo das NFTs.",
  "",
  "## Discord",
  "",
  "Outro lugar essencial para as comunidades de NFTs. Artistas, investidores e colecionadores podem se conectar, organizar e conversar. Muitas plataformas de NFTs, artistas e projetos têm seus próprios servidores no Discord.",
  "",
  "## Warpcast / Farcaster",
  "",
  "Aplicativo feito pela equipe do projeto Farcaster — uma **rede social descentralizada**. Tem foco em usuários do meio cripto. Valor anual para usar a plataforma.",
  "",
  "## Nostr",
  "",
  "Protocolo simples e aberto que permite mídias sociais globais, descentralizadas e resistentes à censura. Existem várias redes que utilizam esse protocolo.",
  "",
  "## Escolhendo suas plataformas",
  "",
  "Você não precisa estar em todo lugar. Comece com 1-2 plataformas e construa conexões genuínas antes de expandir. **Consistência e autenticidade importam mais do que volume.**",
].join("\n");

const marketing = [
  "## 1. Crie uma Identidade Sólida",
  "",
  "Desenvolva uma identidade visual e tenha um discurso consistente que representem sua personalidade.",
  "",
  "## 2. Seja Ativo nas Redes Sociais",
  "",
  "Interaja com sua audiência, compartilhe seu trabalho e participe de conversas relacionadas à sua área.",
  "",
  "## 3. Organização é Fundamental",
  "",
  "Utilize ferramentas de agendamento de postagens, mantenha um calendário de lançamentos e esteja sempre atento aos prazos e oportunidades.",
  "",
  "## 4. Construa Conexões Importantes",
  "",
  "Comente genuinamente no trabalho de outras pessoas. Participe de projetos compartilhados. Apareça consistentemente em comunidades que você se importa. Ofereça ajuda antes de pedir.",
  "",
  "## 5. Frequência de Lançamentos",
  "",
  "Encontre um ritmo sustentável para você. Burnout não ajuda ninguém.",
  "",
  "## 6. Estratégias de Precificação",
  "",
  "**Não se desvalorize!** Considere escassez, demanda, valor da moeda e seu tempo e ofício.",
  "",
  "## 7. Mantenha-se Criativo e Conectado",
  "",
  "Mesmo em períodos de vendas mais lentas, continue criando e mantendo-se conectado com sua audiência.",
  "",
  "## 8. Esteja Preparado para Mudanças",
  "",
  "Plataformas podem mudar e até fechar — o que não faz que as NFTs sumam, afinal estão na blockchain. É crucial estar sempre experimentando novas possibilidades.",
  "",
  "> Bom marketing no espaço NFT é sobre ser genuinamente presente, compartilhar autenticamente, construir relações antes de transações e manter consistência ao longo do tempo.",
].join("\n");

const about = [
  "**Computadores Fazem Arte** é um wiki educacional sobre Blockchain, Web3 e NFTs — desenvolvido como parte integrante de uma pesquisa de mestrado em **Design de Artefatos Digitais** na Universidade Federal de Pernambuco (UFPE), financiada pelo programa MAI/DAI do CNPq.",
  "",
  "## O Nome",
  "",
  "O nome do projeto vem de um verso de **Fred Zero Quatro**, vocalista da lendária banda recifense Mundo Livre S/A, da música *Computadores Fazem Arte*.",
  "",
  "> Computadores avançam / Artistas pegam carona / Cientistas criam o novo / Artistas levam a fama — Fred Zero Quatro",
  "",
  "A música é ao mesmo tempo uma observação e uma provocação — e deu nome a um projeto que tenta pensar criticamente o que significa para artistas habitar espaços tecnológicos.",
  "",
  "Assista a música: https://www.youtube.com/watch?v=KZg_m0z4NLI",
  "",
  "## Iniciação Científica",
  "",
  "Como parte da pesquisa, três estudantes de graduação foram orientados em diferentes áreas do conhecimento — uma escolha interdisciplinar deliberada que reflete os próprios valores do projeto.",
  "",
  "### Milena — Pedagogia",
  "Trouxe um olhar educacional ao projeto, ajudando a pensar como conceitos tecnológicos complexos podem ser tornados acessíveis a públicos diversos.",
  "",
  "### Vitória — Design",
  "Contribuiu com uma perspectiva visual e comunicacional, essencial para moldar como o wiki e seus materiais são apresentados.",
  "",
  "### Artur — Ciência da Computação · in memoriam",
  "Artur entrou na pesquisa como voluntário — movido inteiramente pela própria curiosidade e entusiasmo. Foi um dos participantes mais engajados e ativos do projeto, trazendo rigor técnico e empolgação genuína a cada encontro. Sua presença deixou uma marca nessa pesquisa que não se mede. Este projeto carrega um pedaço dele.",
  "",
  "## Curso Presencial — CTG/UFPE, 2024",
  "",
  "Em 2024, um curso presencial de quatro semanas foi realizado no Centro de Tecnologia e Geociências (CTG) da UFPE — reunindo estudantes de diferentes áreas para aprender sobre Blockchain, NFTs e comunidades digitais de arte.",
  "",
  "O encerramento do curso foi interrompido pelo **bloqueio do Twitter/X no Brasil** — um momento que se tornou parte da própria história do projeto e um estudo de caso ao vivo: um lembrete de que as mesmas plataformas que hospedam comunidades de arte digital estão sujeitas a decisões políticas, pressões regulatórias e poder corporativo.",
  "",
  "A regulação das plataformas de redes sociais não é um tema secundário — é central para qualquer conversa honesta sobre direitos digitais, liberdade de expressão e as condições nas quais artistas criam e distribuem seu trabalho. As plataformas devem ser responsabilizadas por garantir os direitos fundamentais dos usuários.",
  "",
  "## Publicação — WebMedia 2024",
  "",
  "O material desenvolvido nesta pesquisa foi publicado e apresentado no **WebMedia 2024**, realizado na Universidade Federal de Juiz de Fora (UFJF).",
  "",
  "[Acessar a publicação](https://books-sol.sbc.org.br/index.php/sbc/catalog/view/177/779/1513)",
  "",
  "## Disciplina — Design para Web3, UFPE 2025",
  "",
  "Em 2025, a pesquisa levou a um convite do **Professor Leonardo Castillo** para ministrar a disciplina *Design para Web3* no curso de Design da UFPE.",
  "",
  "## Contato",
  "",
  "**Numa** · [@numadessas](https://twitter.com/numadessas) · [contato@numadessas.com.br](mailto:contato@numadessas.com.br) · [numadessas.com.br](https://numadessas.com.br)",
].join("\n");

const references = [
  "## Obras Acadêmicas",
  "",
  "**ASSANGE, Julian et al.** Cypherpunks: Liberdade e o Futuro da Internet. São Paulo: Boitempo, 2013.",
  "",
  "**PANDA, Sandeep Kumar et al.** Bitcoin and Blockchain: History and Current Applications. 2020, CRC Press.",
  "",
  "**AL-SAQAF, Walid; SEIDLER, Nicolas.** Blockchain technology for social impact. 2017, Journal of Cyber Policy.",
  "",
  "**KENT, Charlotte.** Blockchain manifestos: fighting for the imagination of a culture. 2021, Burlington Contemporary Journal.",
  "",
  "**LIMA, Júnior César de; CARVALHO, Cedric L. de.** Uma Visão da Web Semântica. 2004, UFG.",
  "",
  "## Recursos Online",
  "",
  "- [Glossário CoinMarketCap](https://coinmarketcap.com/academy/en/glossary)",
  "- [Web3 Foundation](https://web3.foundation/)",
  "- [Chainlink — O que é um NFT Dinâmico?](https://chain.link/education-hub/what-is-dynamic-nft)",
  "- [DappRadar](https://dappradar.com/)",
  "- [Solana: A Primer — Shinobi Systems](https://www.shinobi-systems.com/primer.html)",
  "- [When the Social meets the Semantic: Social Semantic Web or Web 2.5 — Fernandez-Llatas & Traver](https://www.mdpi.com/1999-5903/4/3/852)",
  "",
  "## Sobre este Projeto",
  "",
  "Este wiki foi desenvolvido por **Numa** como parte integrante da pesquisa de mestrado em Design de Artefatos Digitais na UFPE, financiada pelo programa MAI/DAI do CNPq.",
  "",
  "Contato: [contato@numadessas.com.br](mailto:contato@numadessas.com.br)",
  "",
  "*Conteúdo disponível para distribuição livre e gratuita.*",
].join("\n");

export const wikiSections = [
  {
    id: "introduction",
    slug: "introduction",
    title: "Introdução",
    subtitle: "Sobre este wiki",
    tags: ["visão geral", "web3", "nft"],
    description: "O que é Computadores Fazem Arte e por que este conhecimento importa.",
    related: ["glossary", "internet-generations"],
    content: intro,
  },
  {
    id: "glossary",
    slug: "glossary",
    title: "Glossário",
    subtitle: "Termos essenciais",
    tags: ["referência", "terminologia"],
    description: "Vocabulário essencial para navegar no espaço Web3 e NFTs.",
    related: ["introduction", "blockchain"],
    isGlossary: true,
    content: "Vocabulário essencial para navegar no espaço Web3 e NFTs. Clique em qualquer termo para expandir sua definição.",
    glossaryTerms: [
      { term: "DYOR", definition: "Do Your Own Research — expressão para falar que cada um precisa fazer sua pesquisa, pois investir em cripto é algo muito volátil. O que dá certo para uma pessoa não necessariamente é o que dá para outra." },
      { term: "Flood", definition: "Mandar muitas mensagens sobre uma mesma coisa, chegando a ser uma poluição visual em chats e servidores." },
      { term: "FOMO", definition: "Fear Of Missing Out — medo de perder uma oportunidade. Muito comum em mercados voláteis, pode levar a decisões impulsivas." },
      { term: "WAGMI", definition: "We Are All Gonna Make It — expressão otimista usada nas comunidades NFT, algo como nos vamos conseguir." },
      { term: "Genesis", definition: "Primeira NFT que alguém lança em alguma rede/plataforma. Termo inspirado pelo genesis block, que é o primeiro bloco minerado de uma blockchain." },
      { term: "Hash", definition: "Sequência única de caracteres gerada a partir de dados de transações usando uma função matemática especial. Nas blockchains, os hashes verificam a integridade dos dados e conectam os blocos de forma segura." },
      { term: "Node / Nó", definition: "Computador que faz parte da estrutura de uma rede Blockchain. Cada nó tem uma cópia idêntica de todas as transações que ocorreram na rede." },
      { term: "Nonce", definition: "Abreviação de número usado uma vez — número gerado aleatoriamente e usado uma só vez em uma transação criptográfica." },
      { term: "Queimar / Burn NFT", definition: "Processo para tornar uma NFT inutilizada. Não é possível deletar uma NFT da blockchain, então essa ação é usada quando existe necessidade de remover uma NFT de circulação." },
      { term: "Scam", definition: "Termo em inglês para golpe, fraude. Muito comum no espaço cripto — desconfie sempre de propostas boas demais." },
      { term: "Phishing", definition: "Tipo de golpe virtual que rouba informações pessoais e financeiras, geralmente através de sites falsos ou mensagens que imitam serviços legítimos." },
      { term: "NFA", definition: "No Financial Advice — expressão usada quando alguém fala sobre algum projeto/moeda, indicando que cada pessoa deve ter sua própria avaliação financeira." },
      { term: "IRL", definition: "In Real Life — na vida real. Usado para a vida que acontece fora da internet." },
      { term: "Navegador de Blocos", definition: "Plataforma onde é possível acessar uma blockchain publicamente em tempo real. Cada rede possui um ou mais navegadores de blocos." },
      { term: "Whitepaper", definition: "Documento que explica os objetivos e tecnologias de um projeto cripto. É uma necessidade crucial para que projetos sejam considerados genuínos e profissionais." },
      { term: "Mintagem / Minting", definition: "Processo de criar e registrar uma NFT em uma blockchain — tornando-a um ativo digital oficial e verificável." },
      { term: "GM / GN", definition: "Good Morning / Good Night — saudações comuns nas comunidades NFT e cripto para criar conexão diária." },
    ],
  },
  {
    id: "internet-generations",
    slug: "internet-generations",
    title: "Gerações da Internet",
    subtitle: "Web1, Web2, Web3",
    tags: ["web3", "história", "tecnologia"],
    description: "Das páginas estáticas às redes semânticas e descentralizadas.",
    related: ["blockchain", "introduction"],
    content: internetGen,
  },
  {
    id: "blockchain",
    slug: "blockchain",
    title: "Tecnologia Blockchain",
    subtitle: "Como funciona",
    tags: ["blockchain", "tecnologia", "história"],
    description: "Livros digitais descentralizados, mecanismos de consenso, estrutura de blocos e aplicações.",
    related: ["consensus", "crypto-wallets", "nfts", "internet-generations"],
    content: blockchain,
  },
  {
    id: "consensus-mechanisms",
    slug: "consensus-mechanisms",
    title: "Mecanismos de Consenso",
    subtitle: "Mineração e Validação",
    tags: ["blockchain", "tecnologia", "consenso"],
    description: "Como redes descentralizadas concordam sobre transações: PoW, PoS, PoA e PoH.",
    related: ["blockchain", "cryptography", "crypto-wallets"],
    content: miningValidation,
  },
  {
    id: "cryptography",
    slug: "cryptography",
    title: "Criptografia",
    subtitle: "A base da blockchain",
    tags: ["blockchain", "tecnologia", "criptografia"],
    description: "Como a criptografia torna a blockchain possível — e por que cripto se chama cripto.",
    related: ["blockchain", "consensus-mechanisms"],
    content: cryptography,
  },
  {
    id: "crypto-wallets",
    slug: "crypto-wallets",
    title: "Crypto Wallets",
    subtitle: "Wallets, private keys and security",
    tags: ["segurança", "carteiras", "golpe"],
    description: "Como funcionam as carteiras de criptomoedas, o que são chaves privadas e como se proteger de golpes.",
    related: ["blockchain", "nfts"],
    content: security,
  },
  {
    id: "nfts",
    slug: "nfts",
    title: "NFTs",
    subtitle: "Tokens não fungíveis",
    tags: ["nft", "arte", "blockchain"],
    description: "O que são NFTs, como funcionam, metadados, NFTs dinâmicos e como criar um.",
    related: ["blockchain", "platforms", "communities"],
    content: nfts,
  },
  {
    id: "communities",
    slug: "communities",
    title: "Comunidades NFT",
    subtitle: "Construindo conexões",
    tags: ["comunidade", "nft", "cultura"],
    description: "Tipos de comunidades, como participar, iniciativas sociais e perspectiva crítica.",
    related: ["platforms", "communication", "marketing"],
    content: communities,
  },
  {
    id: "platforms",
    slug: "platforms",
    title: "Plataformas",
    subtitle: "Marketplaces de NFT",
    tags: ["nft", "plataformas", "ferramentas"],
    description: "Uma visão geral das plataformas de NFT em diferentes blockchains.",
    related: ["nfts", "communication", "blockchain"],
    content: platforms,
  },
  {
    id: "communication",
    slug: "communication",
    title: "Plataformas de Comunicação",
    subtitle: "Onde as comunidades vivem",
    tags: ["comunidade", "social", "ferramentas"],
    description: "As redes sociais e ferramentas de comunicação que as comunidades NFT usam.",
    related: ["communities", "marketing"],
    content: communication,
  },
  {
    id: "marketing",
    slug: "marketing",
    title: "Marketing",
    subtitle: "Divulgando seu trabalho",
    tags: ["marketing", "comunidade", "estratégia"],
    description: "Estratégias para promover seu trabalho NFT de forma ética e eficaz.",
    related: ["communities", "communication", "platforms"],
    content: marketing,
  },
  {
    id: "about",
    slug: "about",
    title: "Sobre o Projeto",
    subtitle: "Pesquisa e história",
    tags: ["pesquisa", "ufpe", "sobre"],
    description: "A origem do projeto, a pesquisa por trás dele e as pessoas que o construíram.",
    related: ["introduction", "references"],
    content: about,
  },
  {
    id: "references",
    slug: "references",
    title: "Referências",
    subtitle: "Bibliografia",
    tags: ["pesquisa", "bibliografia"],
    description: "Referências acadêmicas e online utilizadas neste wiki.",
    related: ["introduction"],
    content: references,
  },
];

export const allTags = [...new Set(wikiSections.flatMap(s => s.tags))];
export const getSectionBySlug = (slug) => wikiSections.find(s => s.slug === slug);
export const getRelatedSections = (slugs) => slugs.map(slug => wikiSections.find(s => s.slug === slug)).filter(Boolean);