// Conteúdo do wiki em Português
// Usa arrays de strings para evitar problemas com template literals

const internetGen = [
  "# Gerações da Internet",
  "",
  "Antes de tudo, é importante aprender sobre as três gerações existentes da internet. Vivemos em um momento onde a Web 2 e a Web3 existem simultaneamente — cada geração não são coisas à parte, mas apenas continuações da web que já conhecemos.",
  "",
  "---",
  "",
  "## Web 1.0 — A Internet Simples",
  "",
  "A primeira fase da Internet surgiu nos **anos 90** e consistia em páginas com hiperlinks. Os sites eram principalmente informativos com layouts muito básicos e a maioria do conteúdo baseado em texto. Só era possível acessar, ler e mudar de página.",
  "",
  "Características: largura de banda limitada, dispositivos limitados (somente desktop), nenhuma interação real.",
  "",
  "## Web 2.0 — A Internet Social",
  "",
  "Surgiu por volta de **2004** — fase que trouxe mais conteúdo gerado pelo usuário e recursos visuais. Os usuários puderam compartilhar mais informações entre si e se conectar mais facilmente. Marcada por maior interatividade e colaboração, mas com **plataformas centralizadas** (Google, Facebook, Instagram) detendo os dados dos usuários.",
  "",
  "## Web3 — A Internet Semântica",
  "",
  "A partir de **2008**, quando a tecnologia Blockchain entrou em ação através do Bitcoin. Os princípios da Web3 têm a intenção de permitir que os usuários possuam seus próprios dados, ao invés de empresas.",
  "",
  "Conhecida também como **Web Semântica**, pois tem o objetivo de tornar a informação compreensível para o computador — através do machine learning.",
  "",
  "> Apesar disso, muitos discursos sobre Blockchain estão ligados a ideias neoliberais. Mesmo com o ideal sobre descentralização, as Blockchains na prática concentram poder nas mãos de poucos desenvolvedores e mineradores. — MENOTTI, 2021",
].join("\n");

const blockchain = [
  "# Tecnologia Blockchain",
  "",
  "## O que é Blockchain?",
  "",
  "As Blockchains são como **livros de registros digitais e descentralizados**. Redes online onde os dados são salvos nos computadores de cada usuário da Blockchain, não apenas em um só servidor.",
  "",
  "Uma analogia útil: a blockchain é como uma grande **planilha compartilhada** replicada em milhares de computadores. Essa planilha é atualizada constantemente e cada nó verifica cada nova entrada.",
  "",
  "---",
  "",
  "## História",
  "",
  "A tecnologia Blockchain teve suas origens em **1991**, quando Stuart Haber e W. Scott Stornetta publicaram um artigo sobre como colocar um carimbo de data e hora em documentos digitais de forma segura. Em 2008, *Satoshi Nakamoto* publicou o artigo do Bitcoin, e em 2009 o primeiro bloco foi minerado.",
  "",
  "---",
  "",
  "## Como funciona uma Blockchain?",
  "",
  "**1. Usuário Solicita Transação** — codificada em um bloco com remetente, destinatário e valor.",
  "",
  "**2. Transação transmitida para a rede** — todos os nós verificam a validade.",
  "",
  "**3. Processo de consenso** — os nós concordam qual bloco adicionar (mineração/validação).",
  "",
  "**4. Transação finalizada** — adicionada imutavelmente à cadeia. Não pode ser alterada ou revertida.",
  "",
  "---",
  "",
  "## Mecanismos de Consenso",
  "",
  "| Mecanismo | Descrição | Exemplos |",
  "|-----------|-----------|---------|",
  "| **Prova de Trabalho (PoW)** | Mineradores competem para resolver problemas matemáticos complexos | Bitcoin, Litecoin |",
  "| **Prova de Participação (PoS)** | Validadores escolhidos pela quantidade de cripto em stake | Ethereum, Solana, Cardano |",
  "| **Prova de Autoridade (PoA)** | Validadores pré-selecionados e autorizados | Binance Coin, XRP |",
  "",
  "---",
  "",
  "## Propriedades da Blockchain",
  "",
  "**Descentralização:** Sem autoridade central — o controle é distribuído entre todos os participantes da rede.",
  "",
  "**Transparência:** Todas as transações são públicas e rastreáveis via navegadores de blocos.",
  "",
  "**Imutabilidade:** Uma vez registrado, o dado não pode ser alterado.",
  "",
  "**Anonimato:** Usuários têm endereços públicos (não identidade pessoal).",
  "",
  "---",
  "",
  "## Camadas das Blockchains",
  "",
  "| Camada | Função | Exemplos |",
  "|--------|--------|---------|",
  "| L0 | Infraestrutura, interoperabilidade | Polkadot, Cosmos |",
  "| L1 | Blockchains principais, consenso | Bitcoin, Ethereum, Solana |",
  "| L2 | Escalabilidade, redução de taxas | Optimism, Polygon, Arbitrum |",
  "| L3 | Camada de aplicação cross-chain | IBC Protocol, Quant |",
].join("\n");

const security = [
  "# Segurança",
  "",
  "## Carteiras de Criptomoedas",
  "",
  "A **carteira (wallet)** é como uma conta bancária para suas moedas digitais. Feita para armazenar cripto obtida através de compra, transferência ou mineração/validação. É o principal meio de interagir com sites e aplicativos da Web3.",
  "",
  "---",
  "",
  "## Chaves de Segurança",
  "",
  "**Chaves Públicas:** Como os números das contas bancárias — uma sequência de números e letras gerada aleatoriamente ao criar uma carteira. É a informação necessária para transferir ou receber ativos digitais. Seguro compartilhar.",
  "",
  "**Chaves Privadas / Frase-Semente:** Devem ser mantidas em sigilo e local físico seguro. A frase-semente é a parte mais importante da segurança — com ela é possível recuperar a mesma conta em diferentes dispositivos.",
  "",
  "> Atenção: Essas chaves não devem ser mantidas de maneira nenhuma em arquivos digitais ou e-mails. Uma vez que você perder a seed-phrase, é impossível resgatar sua carteira. Não existe sistema de recuperação.",
  "",
  "---",
  "",
  "## Tipos de Carteiras",
  "",
  "**Carteira Digital (Hot Wallet):** Software usado em desktop e mobile, conectado à internet. Indicada para interações e operações casuais. Exemplos: Phantom (Solana), MetaMask (Ethereum), Temple (Tezos).",
  "",
  "**Carteira de Hardware (Cold Wallet):** Dispositivo físico não conectado à internet. Recomendado para armazenamento de longo prazo. Marcas: Ledger, Trezor, Ngrave.",
  "",
  "---",
  "",
  "## Golpes Comuns",
  "",
  "**Perfis Falsos no Instagram:** Se passam por colecionadores e oferecem preços altos pela sua obra, depois pedem uma taxa para finalizar a venda — que nunca acontece.",
  "",
  "**Propostas de Trabalho Falsas:** Oferecem comissões ou testes de jogos com arquivos infectados com malware que vasculham o computador para invadir carteiras.",
  "",
  "**Sites Fraudulentos:** Clones de projetos populares. Quando você conecta sua carteira, drenam todos os fundos.",
  "",
  "---",
  "",
  "## Medidas de Segurança",
  "",
  "- Não clique em links desconhecidos",
  "- Não abra anexos de perfis desconhecidos",
  "- Não conecte sua carteira em qualquer site",
  "- Duvide de propostas muito exorbitantes",
  "- Nunca compartilhe suas chaves",
  "- Armazene em local físico seguro",
  "- Use extensões anti-phishing (Pocket Universe, Wallet Guard)",
].join("\n");

const nfts = [
  "# NFTs",
  "",
  "## O que são NFTs?",
  "",
  "Podemos entender **NFT** como o **certificado digital de propriedade de um item**. Esse certificado é criado e registrado em uma rede Blockchain e pode conter arquivos, links, texto ou códigos.",
  "",
  "NFT significa **Non-Fungible Token** (ficha não fungível). Fungível = substituível (dinheiro, carros). Infungível = único, insubstituível (obras de arte, bens imóveis).",
  "",
  "---",
  "",
  "## Metadados",
  "",
  "Metadados NFT são como etiquetas com as propriedades de um ativo digital: descrição do arquivo, nome, categorias, histórico de transações, data e hora.",
  "",
  "**On-chain:** A informação fica diretamente na rede Blockchain, integrada ao próprio NFT.",
  "",
  "**Off-chain:** A informação fica em servidores ou sistemas de armazenamento em nuvem (IPFS). A maioria dos metadados é armazenada off-chain como arquivo JSON.",
  "",
  "---",
  "",
  "## NFTs Dinâmicos (dNFTs)",
  "",
  "NFTs cujas características podem mudar — também conhecidos como semi fungíveis ou NFT vivo. Bastante usados em jogos DeFi (insígnias que evoluem) e nas artes (peças que mudam conforme regras definidas pelo artista).",
  "",
  "Exemplo: Os NFTs do jogador de basquete LaMelo Ball incorporam dados esportivos na rede e mudam dependendo do resultado dos jogos.",
  "",
  "---",
  "",
  "## Como fazer NFT",
  "",
  "**Passo 1:** Escolher a Blockchain (Ethereum, Solana, Tezos...)",
  "",
  "**Passo 2:** Escolher a Plataforma (veja seção Plataformas)",
  "",
  "**Passo 3:** Gerar um arquivo (sua arte, música, vídeo, código...)",
  "",
  "**Passo 4:** Mintar o arquivo na Plataforma",
  "",
  "**Passo 5:** Listar a NFT (preço, edição, condições)",
  "",
  "**Passo 6:** Divulgação — construa visibilidade pela sua comunidade",
].join("\n");

const communities = [
  "# Comunidades NFT",
  "",
  "Uma **comunidade NFT** é um grupo digital de pessoas interessadas em NFTs, que se reúnem para discutir, criar, comprar, vender e trocar esses tokens. As comunidades são cruciais — é impossível prosperar sem comunidade nesse ambiente.",
  "",
  "---",
  "",
  "## Tipos de Comunidades NFT",
  "",
  "**Comunidades de projeto:** Centradas em torno de um projeto NFT específico, como uma coleção de arte digital.",
  "",
  "**Comunidades de colecionadores:** Reúnem pessoas interessadas em colecionar NFTs, independentemente do projeto.",
  "",
  "**Comunidades de artistas:** Focadas em artistas digitais que criam NFTs.",
  "",
  "**Comunidades de investidores:** Compostas por pessoas que investem em NFTs com fins lucrativos.",
  "",
  "---",
  "",
  "## Como participar",
  "",
  "Utilize as plataformas sociais comuns: Discord, Twitter/X e Warpcast. Seja consistente e paciente — construir uma comunidade leal leva tempo e esforço. Seja autêntico e transparente sobre seus objetivos.",
  "",
  "---",
  "",
  "## Dicas para iniciantes",
  "",
  "1. Não confie em dinheiro fácil — não espere ser milionário em 2 semanas.",
  "2. Use NFT como uma ferramenta para mostrar seu trabalho.",
  "3. Não acredite em postagens do tipo deixe seu NFT aqui (engagement farm).",
  "4. Nunca crie a mesma arte em Blockchains diferentes.",
  "5. Não inunde bate-papos com mensagens demais.",
  "",
  "---",
  "",
  "## Iniciativas Sociais",
  "",
  "A iniciativa **Balot NFT**, liderada pela Congolese Plantation Workers Art League (CATPC), usou a tecnologia NFT para reivindicar o patrimônio cultural e comprar de volta terras roubadas pelo plantation no Congo. Cada NFT Balot representa um hectare de terra, e os fundos são usados para replantar florestas.",
  "",
  "---",
  "",
  "## Perspectiva Crítica",
  "",
  "> O ambiente virtual é apenas uma extensão do nosso mundo físico — obviamente reflete e reproduz os problemas sociais existentes na vida real. O cenário das NFTs não é isento de política. Toda tecnologia é uma ferramenta. O resultado do seu uso vai de quem estiver utilizando-a.",
].join("\n");

const platforms = [
  "# Plataformas de NFTs",
  "",
  "Abaixo está uma visão geral de plataformas disponíveis em diferentes blockchains. Explore o **DappRadar** para descobrir plataformas em muitas outras redes.",
  "",
  "---",
  "",
  "## Ethereum e suas L2s",
  "",
  "**Zora** — focada em criadores, mintagem gratuita",
  "**Super Rare** — marketplace curado de obras 1/1",
  "**Foundation** — plataforma curada por convite",
  "**Manifold** — ferramentas para contratos inteligentes personalizados",
  "**Rarible** — multi-chain, foco em royalties para criadores",
  "",
  "## Solana",
  "",
  "**3.land** — comunidade e exposições",
  "**Exchange Art** — arte digital curada",
  "**Magic Eden** — maior marketplace de Solana",
  "**Tensor** — trading e análises",
  "",
  "## Tezos",
  "",
  "**Objkt** — maior marketplace de Tezos",
  "**(fx)hash** — arte generativa",
  "**teia** — community-owned, centrada em artistas",
  "",
  "## Bitcoin Ordinals",
  "",
  "**Gamma** · **Magic Eden** · **Ordzaa**",
  "",
  "---",
  "",
  "## Como escolher uma plataforma?",
  "",
  "**Taxas:** Tezos e Solana têm taxas muito baixas; Ethereum é mais alta.",
  "",
  "**Comunidade:** Diferentes plataformas atraem diferentes comunidades de colecionadores.",
  "",
  "**Curadoria:** Abertas (Objkt, Magic Eden) vs. curadas (Super Rare, Foundation).",
  "",
  "**Missão:** teia é community-owned; outras plataformas são comerciais.",
  "",
  "> Lembre-se: plataformas podem mudar e até fechar — mas as NFTs permanecem na blockchain. Esteja sempre preparada para se adaptar.",
].join("\n");

const communication = [
  "# Plataformas de Comunicação",
  "",
  "As comunidades NFTs se constroem em redes sociais essenciais. Estes espaços são necessários para conectar artistas e colecionadores.",
  "",
  "---",
  "",
  "## X (Antigo Twitter)",
  "",
  "Uma das plataformas mais usadas para divulgar NFTs. Muitos artistas, traders e pessoas do meio cripto têm perfis dedicados a esse assunto. Apesar das mudanças recentes, ainda é uma rede importante para o mundo das NFTs.",
  "",
  "---",
  "",
  "## Discord",
  "",
  "Outro lugar essencial para as comunidades de NFTs. Artistas, investidores e colecionadores podem se conectar, organizar e conversar. Muitas plataformas de NFTs, artistas e projetos têm seus próprios servidores no Discord.",
  "",
  "---",
  "",
  "## Warpcast / Farcaster",
  "",
  "Aplicativo feito pela equipe do projeto Farcaster — uma **rede social descentralizada**. Tem foco em usuários do meio cripto. Valor anual para usar a plataforma.",
  "",
  "---",
  "",
  "## Nostr",
  "",
  "Protocolo simples e aberto que permite mídias sociais globais, descentralizadas e resistentes à censura. Existem várias redes que utilizam esse protocolo.",
  "",
  "---",
  "",
  "## Escolhendo suas plataformas",
  "",
  "Você não precisa estar em todo lugar. Comece com 1-2 plataformas e construa conexões genuínas antes de expandir. **Consistência e autenticidade importam mais do que volume.**",
].join("\n");

const marketing = [
  "# Marketing",
  "",
  "## 1. Crie uma Identidade Sólida",
  "",
  "Desenvolva uma identidade visual e tenha um discurso consistente que representem sua personalidade.",
  "",
  "---",
  "",
  "## 2. Seja Ativo nas Redes Sociais",
  "",
  "Interaja com sua audiência, compartilhe seu trabalho e participe de conversas relacionadas à sua área.",
  "",
  "---",
  "",
  "## 3. Organização é Fundamental",
  "",
  "Utilize ferramentas de agendamento de postagens, mantenha um calendário de lançamentos e esteja sempre atento aos prazos e oportunidades.",
  "",
  "---",
  "",
  "## 4. Construa Conexões Importantes",
  "",
  "Comente genuinamente no trabalho de outras pessoas. Participe de projetos compartilhados. Apareça consistentemente em comunidades que você se importa. Ofereça ajuda antes de pedir.",
  "",
  "---",
  "",
  "## 5. Frequência de Lançamentos",
  "",
  "Encontre um ritmo sustentável para você. Burnout não ajuda ninguém.",
  "",
  "---",
  "",
  "## 6. Estratégias de Precificação",
  "",
  "**Não se desvalorize!** Considere escassez, demanda, valor da moeda e seu tempo e ofício.",
  "",
  "---",
  "",
  "## 7. Mantenha-se Criativo e Conectado",
  "",
  "Mesmo em períodos de vendas mais lentas, continue criando e mantendo-se conectado com sua audiência.",
  "",
  "---",
  "",
  "## 8. Esteja Preparado para Mudanças",
  "",
  "Plataformas podem mudar e até fechar — o que não faz que as NFTs sumam, afinal estão na blockchain. É crucial estar sempre experimentando novas possibilidades.",
  "",
  "> Bom marketing no espaço NFT é sobre ser genuinamente presente, compartilhar autenticamente, construir relações antes de transações e manter consistência ao longo do tempo.",
].join("\n");

const about = [
  "# Sobre o Projeto",
  "",
  "**Computadores Fazem Arte** é um wiki educacional sobre Blockchain, Web3 e NFTs — desenvolvido como parte integrante de uma pesquisa de mestrado em **Design de Artefatos Digitais** na Universidade Federal de Pernambuco (UFPE), financiada pelo programa MAI/DAI do CNPq.",
  "",
  "---",
  "",
  "## O Nome",
  "",
  "O nome do projeto vem de um verso de **Fred Zero Quatro**, vocalista da lendária banda recifense Mundo Livre S/A, da música *Computadores Fazem Arte*.",
  "",
  "> Computadores avançam / Artistas pegam carona / Cientistas criam o novo / Artistas levam a fama — Fred Zero Quatro",
  "",
  "A música é ao mesmo tempo uma observação e uma provocação — e deu nome a um projeto que tenta pensar criticamente o que significa para artistas habitar espaços tecnológicos.",
  "",
  "Assista a música: https://www.youtube.com/watch?v=KZg_m0z4NLI",
  "",
  "---",
  "",
  "## Iniciação Científica",
  "",
  "Como parte da pesquisa, três estudantes de graduação foram orientados em diferentes áreas do conhecimento — uma escolha interdisciplinar deliberada que reflete os próprios valores do projeto.",
  "",
  "### Milena — Pedagogia",
  "Trouxe um olhar educacional ao projeto, ajudando a pensar como conceitos tecnológicos complexos podem ser tornados acessíveis a públicos diversos.",
  "",
  "### Vitória — Design",
  "Contribuiu com uma perspectiva visual e comunicacional, essencial para moldar como o wiki e seus materiais são apresentados.",
  "",
  "### Artur — Ciência da Computação · in memoriam",
  "Artur entrou na pesquisa como voluntário — movido inteiramente pela própria curiosidade e entusiasmo. Foi um dos participantes mais engajados e ativos do projeto, trazendo rigor técnico e empolgação genuína a cada encontro. Sua presença deixou uma marca nessa pesquisa que não se mede. Este projeto carrega um pedaço dele.",
  "",
  "---",
  "",
  "## Curso Presencial — CTG/UFPE, 2024",
  "",
  "Em 2024, um curso presencial de quatro semanas foi realizado no Centro de Tecnologia e Geociências (CTG) da UFPE — reunindo estudantes de diferentes áreas para aprender sobre Blockchain, NFTs e comunidades digitais de arte.",
  "",
  "O encerramento do curso foi interrompido pelo **bloqueio do Twitter/X no Brasil** — um momento que se tornou parte da própria história do projeto e um estudo de caso ao vivo: um lembrete de que as mesmas plataformas que hospedam comunidades de arte digital estão sujeitas a decisões políticas, pressões regulatórias e poder corporativo.",
  "",
  "A regulação das plataformas de redes sociais não é um tema secundário — é central para qualquer conversa honesta sobre direitos digitais, liberdade de expressão e as condições nas quais artistas criam e distribuem seu trabalho. As plataformas devem ser responsabilizadas por garantir os direitos fundamentais dos usuários.",
  "",
  "---",
  "",
  "## Publicação — WebMedia 2024",
  "",
  "O material desenvolvido nesta pesquisa foi publicado e apresentado no **WebMedia 2024**, realizado na Universidade Federal de Juiz de Fora (UFJF).",
  "",
  "[Acessar a publicação](https://books-sol.sbc.org.br/index.php/sbc/catalog/view/177/779/1513)",
  "",
  "---",
  "",
  "## Disciplina — Design para Web3, UFPE 2025",
  "",
  "Em 2025, a pesquisa levou a um convite do **Professor Leonardo Castillo** para ministrar a disciplina *Design para Web3* no curso de Design da UFPE.",
  "",
  "---",
  "",
  "## Contato",
  "",
  "**Numa** · [@numadessas](https://twitter.com/numadessas) · [contato@numadessas.com.br](mailto:contato@numadessas.com.br) · [numadessas.com.br](https://numadessas.com.br)",
].join("\n");

const references = [
  "# Referências",
  "",
  "## Obras Acadêmicas",
  "",
  "**MENOTTI, Gabriel.** Criptoarte: A Metafísica do NFT e a Tecnocolonização da Autenticidade. 2021, Revista do Centro de Pesquisa e Formação / No 13.",
  "",
  "**ASSANGE, Julian et al.** Cypherpunks: Liberdade e o Futuro da Internet. São Paulo: Boitempo, 2013.",
  "",
  "**PANDA, Sandeep Kumar et al.** Bitcoin and Blockchain: History and Current Applications. 2020, CRC Press.",
  "",
  "**AL-SAQAF, Walid; SEIDLER, Nicolas.** Blockchain technology for social impact. 2017, Journal of Cyber Policy.",
  "",
  "**KENT, Charlotte.** Blockchain manifestos: fighting for the imagination of a culture. 2021, Burlington Contemporary Journal.",
  "",
  "**LIMA, Júnior César de; CARVALHO, Cedric L. de.** Uma Visão da Web Semântica. 2004, UFG.",
  "",
  "---",
  "",
  "## Recursos Online",
  "",
  "- [Glossário CoinMarketCap](https://coinmarketcap.com/academy/en/glossary)",
  "- [Web3 Foundation](https://web3.foundation/)",
  "- [Chainlink — O que é um NFT Dinâmico?](https://chain.link/education-hub/what-is-dynamic-nft)",
  "- [DappRadar](https://dappradar.com/)",
  "",
  "---",
  "",
  "## Sobre este Projeto",
  "",
  "Este wiki foi desenvolvido por **Numa** como parte integrante da pesquisa de mestrado em Design de Artefatos Digitais na UFPE, financiada pelo programa MAI/DAI do CNPq.",
  "",
  "Contato: [contato@numadessas.com.br](mailto:contato@numadessas.com.br)",
  "",
  "*Conteúdo disponível para distribuição livre e gratuita.*",
].join("\n");

export const wikiSections = [
  {
    id: "introduction",
    slug: "introduction",
    title: "Introdução",
    subtitle: "Sobre este wiki",
    tags: ["visão geral", "web3", "nft"],
    description: "O que é Computadores Fazem Arte e por que este conhecimento importa.",
    related: ["glossary", "internet-generations"],
    content: intro,
  },
  {
    id: "glossary",
    slug: "glossary",
    title: "Glossário",
    subtitle: "Termos essenciais",
    tags: ["referência", "terminologia"],
    description: "Vocabulário essencial para navegar no espaço Web3 e NFTs.",
    related: ["introduction", "blockchain"],
    isGlossary: true,
    content: "Vocabulário essencial para navegar no espaço Web3 e NFTs. Clique em qualquer termo para expandir sua definição.",
    glossaryTerms: [
      { term: "DYOR", definition: "Do Your Own Research — expressão para falar que cada um precisa fazer sua pesquisa, pois investir em cripto é algo muito volátil. O que dá certo para uma pessoa não necessariamente é o que dá para outra." },
      { term: "Flood", definition: "Mandar muitas mensagens sobre uma mesma coisa, chegando a ser uma poluição visual em chats e servidores." },
      { term: "FOMO", definition: "Fear Of Missing Out — medo de perder uma oportunidade. Muito comum em mercados voláteis, pode levar a decisões impulsivas." },
      { term: "WAGMI", definition: "We Are All Gonna Make It — expressão otimista usada nas comunidades NFT, algo como nos vamos conseguir." },
      { term: "Genesis", definition: "Primeira NFT que alguém lança em alguma rede/plataforma. Termo inspirado pelo genesis block, que é o primeiro bloco minerado de uma blockchain." },
      { term: "Hash", definition: "Sequência única de caracteres gerada a partir de dados de transações usando uma função matemática especial. Nas blockchains, os hashes verificam a integridade dos dados e conectam os blocos de forma segura." },
      { term: "Node / Nó", definition: "Computador que faz parte da estrutura de uma rede Blockchain. Cada nó tem uma cópia idêntica de todas as transações que ocorreram na rede." },
      { term: "Nonce", definition: "Abreviação de número usado uma vez — número gerado aleatoriamente e usado uma só vez em uma transação criptográfica." },
      { term: "Queimar / Burn NFT", definition: "Processo para tornar uma NFT inutilizada. Não é possível deletar uma NFT da blockchain, então essa ação é usada quando existe necessidade de remover uma NFT de circulação." },
      { term: "Scam", definition: "Termo em inglês para golpe, fraude. Muito comum no espaço cripto — desconfie sempre de propostas boas demais." },
      { term: "Phishing", definition: "Tipo de golpe virtual que rouba informações pessoais e financeiras, geralmente através de sites falsos ou mensagens que imitam serviços legítimos." },
      { term: "NFA", definition: "No Financial Advice — expressão usada quando alguém fala sobre algum projeto/moeda, indicando que cada pessoa deve ter sua própria avaliação financeira." },
      { term: "IRL", definition: "In Real Life — na vida real. Usado para a vida que acontece fora da internet." },
      { term: "Navegador de Blocos", definition: "Plataforma onde é possível acessar uma blockchain publicamente em tempo real. Cada rede possui um ou mais navegadores de blocos." },
      { term: "Whitepaper", definition: "Documento que explica os objetivos e tecnologias de um projeto cripto. É uma necessidade crucial para que projetos sejam considerados genuínos e profissionais." },
      { term: "Mintagem / Minting", definition: "Processo de criar e registrar uma NFT em uma blockchain — tornando-a um ativo digital oficial e verificável." },
      { term: "GM / GN", definition: "Good Morning / Good Night — saudações comuns nas comunidades NFT e cripto para criar conexão diária." },
    ],
  },
  {
    id: "internet-generations",
    slug: "internet-generations",
    title: "Gerações da Internet",
    subtitle: "Web1, Web2, Web3",
    tags: ["web3", "história", "tecnologia"],
    description: "Das páginas estáticas às redes semânticas e descentralizadas.",
    related: ["blockchain", "introduction"],
    content: internetGen,
  },
  {
    id: "blockchain",
    slug: "blockchain",
    title: "Tecnologia Blockchain",
    subtitle: "Como funciona",
    tags: ["blockchain", "tecnologia", "história"],
    description: "Livros digitais descentralizados, mecanismos de consenso, estrutura de blocos e aplicações.",
    related: ["security", "nfts", "internet-generations"],
    content: blockchain,
  },
  {
    id: "security",
    slug: "security",
    title: "Segurança",
    subtitle: "Carteiras e proteção",
    tags: ["segurança", "carteiras", "golpe"],
    description: "Carteiras de criptomoedas, chaves privadas e como se proteger de golpes.",
    related: ["blockchain", "nfts"],
    content: security,
  },
  {
    id: "nfts",
    slug: "nfts",
    title: "NFTs",
    subtitle: "Tokens não fungíveis",
    tags: ["nft", "arte", "blockchain"],
    description: "O que são NFTs, como funcionam, metadados, NFTs dinâmicos e como criar um.",
    related: ["blockchain", "platforms", "communities"],
    content: nfts,
  },
  {
    id: "communities",
    slug: "communities",
    title: "Comunidades NFT",
    subtitle: "Construindo conexões",
    tags: ["comunidade", "nft", "cultura"],
    description: "Tipos de comunidades, como participar, iniciativas sociais e perspectiva crítica.",
    related: ["platforms", "communication", "marketing"],
    content: communities,
  },
  {
    id: "platforms",
    slug: "platforms",
    title: "Plataformas",
    subtitle: "Marketplaces de NFT",
    tags: ["nft", "plataformas", "ferramentas"],
    description: "Uma visão geral das plataformas de NFT em diferentes blockchains.",
    related: ["nfts", "communication", "blockchain"],
    content: platforms,
  },
  {
    id: "communication",
    slug: "communication",
    title: "Plataformas de Comunicação",
    subtitle: "Onde as comunidades vivem",
    tags: ["comunidade", "social", "ferramentas"],
    description: "As redes sociais e ferramentas de comunicação que as comunidades NFT usam.",
    related: ["communities", "marketing"],
    content: communication,
  },
  {
    id: "marketing",
    slug: "marketing",
    title: "Marketing",
    subtitle: "Divulgando seu trabalho",
    tags: ["marketing", "comunidade", "estratégia"],
    description: "Estratégias para promover seu trabalho NFT de forma ética e eficaz.",
    related: ["communities", "communication", "platforms"],
    content: marketing,
  },
  {
    id: "about",
    slug: "about",
    title: "Sobre o Projeto",
    subtitle: "Pesquisa e história",
    tags: ["pesquisa", "ufpe", "sobre"],
    description: "A origem do projeto, a pesquisa por trás dele e as pessoas que o construíram.",
    related: ["introduction", "references"],
    content: about,
  },
  {
    id: "references",
    slug: "references",
    title: "Referências",
    subtitle: "Bibliografia",
    tags: ["pesquisa", "bibliografia"],
    description: "Referências acadêmicas e online utilizadas neste wiki.",
    related: ["introduction"],
    content: references,
  },
];

export const allTags = [...new Set(wikiSections.flatMap(s => s.tags))];
export const getSectionBySlug = (slug) => wikiSections.find(s => s.slug === slug);
export const getRelatedSections = (slugs) => slugs.map(slug => wikiSections.find(s => s.slug === slug)).filter(Boolean);
